### ISSUE TITLE
ASUS DSL AX82U PROBLEM

### ISSUE THREAD

**Issue by grup2008** [gnuton/asuswrt-merlin.ng#100]
ASUS DSL AX82U PRAOBLEM

hello vdsl i am using 100 mbit internet

Although I did the stability setting to 6 db, the snr setting of 8.3 db remains locked

My defined speed is 102398 but I can't pull 6 db because the stability setting is not working.

Speed stays at 92500 as SNR 8.3 db is stuck

Stability settings are not working in vdsl I ask you to fix the problem

**Comment by gnuton** [comment]
does it work with the stock firmware?

**Comment by grup2008** [comment]
dns filter does not work on the latest software 386.02_2

https://imgur.com/VCw5865

**Comment by gnuton** [comment]
Please open different ticket for differet issues. DNS filtering works on DSL-AC68U. Not tested on DSL-AX82U yet... but the code should be the same one. I will give it a try.

**Comment by gnuton** [comment]
dns filter has been fixed and the other issue has been already reported in another issue
