### ISSUE TITLE
Open NAT Game Profile's not saving

### ISSUE THREAD

**Issue by chalkybriman** [gnuton/asuswrt-merlin.ng#118]
**Firmware Version Affected **
386.03_2-gnuton1

**Is this bug present in upstream Merlin releases too?**
Not sure

**Describe the bug**
On the OpenNAT tab on the left under general the game profile does not want to save and apply.

**To Reproduce**
Steps to reproduce the behaviour:
1. Go to Open NAT
2. Click on Enable Port Forwarding > Add Profile > Select Game > Select Internal IP > Click OK > Apply

**Expected behaviour**
I expect game profiles to be listed for my internal IP

**Screenshots**
Not Necessary

**Comment by gnuton** [comment]
hi, DSL-AX82U or DSL-AC68u?

**Comment by gnuton** [comment]
just tested on DSL-AX82U and it works.

**Comment by chalkybriman** [comment]
DSL-AC68U

**Comment by gnuton** [comment]
Bug confirmed. Affecting only DSL-AC68U.

**Comment by chalkybriman** [comment]
No worries thanks for confirming I'm not going mad :D

**Comment by gnuton** [comment]
Fixed. I am building a new stable with ROG and Open NAT enabled.
The new stable with the fix will be available in a few hours: please update
to 386.03_2-gnuton2 once available.

**Comment by chalkybriman** [comment]
awesome thanks

**Comment by chalkybriman** [comment]
Sorry I have that version already few hours yet before a new release?

**Comment by gnuton** [comment]
I have not published it yet. I am testing it once more before release..

**Comment by gnuton** [comment]
released 386.03_2-gnuton2.
I think you had 386.03_2-gnuton1

**Comment by chalkybriman** [comment]
confirmed working now

**Comment by gnuton** [comment]
Eccellent! Thabks a lot for reporting!;)
