### ISSUE TITLE
Skynet not working - IPSet Extensions not supported?

### ISSUE THREAD

**Issue by akulumbeg** [gnuton/asuswrt-merlin.ng#123]
**Firmware Version Affected **
386.03_2-gnuton4 @ DSL-AX82U (also earlier 386.03 versions)

**Is this bug present in upstream Merlin releases too?**
Do not know

**Describe the bug**
When trying to run the Skynet firewall extension, the error shown in the screenshot appears. Now I would normally report this to the Skynet author, but the problem appears to reside within router kernel files where the path
_/lib/modules/"$(uname -r)"/kernel/net/netfilter/ipset/ip_set_hash_ipmac.ko_ does not exist.
It worked fine on DSL-AC86U, so I wonder if this is on purpose. I googled in repos and on the SMB forums before filing the bug, but found nothing.

**To Reproduce**
1. Install amtm/entware
2. Install Skynet via amtm
3. (Try to) Run Skynet

**Expected behavior**
Skynet should run as it did on DSL-AC68U (?)

**Screenshots**
![image](https://user-images.githubusercontent.com/19264137/138857259-6d1d7186-823a-46c3-b700-41e6a647994e.png)

**Comment by akulumbeg** [comment]
I can confirm that Skynet runs now (thanks!), but there is a problem with the IPTables check failing. Not sure if this is an issue to be resolved by you or the author of Skynet.

![image](https://user-images.githubusercontent.com/19264137/139535663-b2e9cd14-7b74-47e2-a412-c180a732d050.png)

from [Skynet source](https://raw.githubusercontent.com/Adamm00/IPSet_ASUS/master/firewall.sh), the code checking the rules is the following:

`
if [ "$filtertraffic" = "all" ] || [ "$filtertraffic" = "inbound" ]; then

		iptables -t raw -C PREROUTING -i "$iface" -m set ! --match-set Skynet-Whitelist src -m set --match-set Skynet-Master src -j DROP 2>/dev/null || fail="${fail}#6 "

	fi

	if [ "$filtertraffic" = "all" ] || [ "$filtertraffic" = "outbound" ]; then

		iptables -t raw -C PREROUTING -i br+ -m set ! --match-set Skynet-Whitelist dst -m set --match-set Skynet-Master dst -j DROP 2>/dev/null || fail="${fail}#7 "

		iptables -t raw -C OUTPUT -m set ! --match-set Skynet-Whitelist dst -m set --match-set Skynet-Master dst -j DROP 2>/dev/null || fail="${fail}#8 "

	fi
`

...

`
if [ "$logmode" = "enabled" ]; then

		if [ "$filtertraffic" = "all" ] || [ "$filtertraffic" = "inbound" ]; then

			iptables -t raw -C PREROUTING -i "$iface" -m set ! --match-set Skynet-Whitelist src -m set --match-set Skynet-Master src -j LOG --log-prefix "[BLOCKED - INBOUND] " --log-tcp-sequence --log-tcp-options --log-ip-options 2>/dev/null || fail="${fail}#14 "

		fi

		if [ "$filtertraffic" = "all" ] || [ "$filtertraffic" = "outbound" ]; then

			iptables -t raw -C PREROUTING -i br+ -m set ! --match-set Skynet-Whitelist dst -m set --match-set Skynet-Master dst -j LOG --log-prefix "[BLOCKED - OUTBOUND] " --log-tcp-sequence --log-tcp-options --log-ip-options 2>/dev/null || fail="${fail}#15 "

			iptables -t raw -C OUTPUT -m set ! --match-set Skynet-Whitelist dst -m set --match-set Skynet-Master dst -j LOG --log-prefix "[BLOCKED - OUTBOUND] " --log-tcp-sequence --log-tcp-options --log-ip-options 2>/dev/null || fail="${fail}#16 "

		fi
`

meaning that the cause is probably that the whole iptables package is missing from the DSL-AX82U build (?).

**Comment by gnuton** [comment]
Hi, there may be other moduels required
Eg if I run
# iptables -t raw -C PREROUTING -i "br0" -m set ! --match-set Skynet-Whitelist src -m set --match-set Skynet-Master src -j LOG --log-prefix "[BLOCKED - INBOUND] " --log-tcp-seq
uence --log-tcp-options --log-ip-options

I get 
iptables v1.4.15: Kernel module xt_set is not loaded in.

Please try to collect the missing modules and I can see if I can enable them. thanks

**Comment by gnuton** [comment]
I have building  xt_set  module now.. is there any other module required?

**Comment by akulumbeg** [comment]
Thanks for getting back to the issue! 
Regardless of which iptables command from the abovementioned ones I run, I get this:

_iptables: No chain/target/match by that name._

**Comment by gnuton** [comment]
That means you have skipped a iptable command before in order to create a
chain/target

BTW can you test this image
https://1489-175516287-gh.circle-artifacts.com/0/workspace/release/DSL-AX82U_386.3_2_cferom_pureubi.w
This contains the missing kernel module
Please run and let me know if there is anything still missing.

**Comment by akulumbeg** [comment]
Everything seems to be working like a charm now (at least Skynet-wise)! Thanks for your time and patience!

**Comment by gnuton** [comment]
Awesome. I will tag it as alpha now. Thanks a lot for finding this. I think
this affects upstream ax56/8u build i will contact Eric for this .
Cheers

**Comment by gnuton** [comment]
Tagged 386.03_2-gnuton5_beta1 with all this fixes. 
If it works fine I can close this issue.

**Comment by Katana1074** [comment]
Works fine for me..
![blah](https://user-images.githubusercontent.com/93548773/139729414-1a5f387f-db78-477d-84c3-00bbdff705e4.jpg)

**Comment by gnuton** [comment]
awesome thannks! I will close this issue since the changes are already in the master branch.
