### ISSUE TITLE
SSH Certificate error

### ISSUE THREAD

**Issue by GitKobo** [gnuton/asuswrt-merlin.ng#125]
**Firmware Version Affected **
386.03_2-gnuton4

**Is this bug present in upstream Merlin releases too?**
Do not know

**Describe the bug**
If using or trying to use or produce a certificate for router with certificate option in administration and system tab, there are always default IP in certificate. Can this be corrected any way?

**To Reproduce**
1. Go to 'Administration'
2. Click on 'System tab'
3. Scroll down to 'Service' and export Certificate
4. Expand Cert.tar and See error in IP and other details if Router has set to use any other IP than default 192.168.1.1

**Expected behavior**
Exported certificate should use modified IP and other settings from DSL setup

**Screenshots**
![Cert](https://user-images.githubusercontent.com/93470622/139578828-9c325ce0-2813-486f-8e0c-d78338b34ae2.jpg)

**Comment by GitKobo** [comment]
My mistage, after 3rd factory reset, changing ip, creating new certificate in WAN with using DDNS tab certificate shows finally correct ip, I must have done some mistages earlier.

**Comment by gnuton** [comment]
no worries! :D
