### ISSUE TITLE
DEV_45958_3 RT-AX82U

### ISSUE THREAD

**Issue by washran** [gnuton/asuswrt-merlin.ng#131]
**Firmware Version Affected **
386.RT-AX82U-45958_3

**Is this bug present in upstream Merlin releases too?**
Merlin not supporting RT-AX82U

**Describe the bug**
1. client list showing wired clients only.
2. General, Aimesh empty.
3. Diversion module Lan, Diversion not showing anything after 4.2.1 upgrade.
4. Cannot set ip on inbound firewall rules.
5. System log showing kernel: CPU: 1 PID: 17073 Comm: dcd Tainted: P           O    4.1.52 #6 frequently.
6. Bandwidth monitor showing wired clients

**To Reproduce**

**Expected behavior**

**Screenshots**
If applicable, add screenshots to help explain your problem or remove this section

**Comment by gnuton** [comment]
Please do not use 45958 because it's not for RT-AX82U yet.

**Comment by gnuton** [comment]
fixed mergiing hte latest RT-AX82U GPL.
