### ISSUE TITLE
gnuton-master+GPL_45958 RT-AX82U repeating bug.

### ISSUE THREAD

**Issue by washran** [gnuton/asuswrt-merlin.ng#133]
**Firmware Version Affected **
386.4_alpha3

**Is this bug present in upstream Merlin releases too?**
Unknown

**Describe the bug**
get_cfg_clientlist and wired_list show no arrays.

**To Reproduce**
1. Click on F12 to open http console
2. type in get_cfg_clientlist or wired_list
3. see response

**Expected behavior**
This is an unusual issue from Asus, probably. Can be fixed by substituting clientlist files for rt-ax58u.

**Screenshots**
If applicable, add screenshots to help explain your problem or remove this section

**Comment by gnuton** [comment]
I got the latest RT-AX82U GPL from Asus and I merged it into gnuton-master+GPL_45958_2. 
Built and it works nicely now.
