### ISSUE TITLE
VDSL2+ Setting & SNR Adjustmen not showing

### ISSUE THREAD

**Issue by JustifYI** [gnuton/asuswrt-merlin.ng#136]
**Firmware Version Affected **
386.03_2-gnuton5

**Is this bug present in upstream Merlin releases too?**
Don't know

**Describe the bug**
VDSL advanced settings are "hidden", and I can't set VDSL SNR adjustment with negative values as I could on Asuswrt firmware before.

**To Reproduce**
1. Go to http://192.168.50.1/Advanced_ADSL_Content.asp

**Expected behavior**
See all the advanced settings and be able to set **negative** SNR adjustment on VDSL2+ again, since I can't reach the DataRate speed as before.

**Screenshots**
Now: ![whatIsee](https://user-images.githubusercontent.com/47337816/146549114-4d7928b3-8c32-4848-81d6-be41d07a8f9b.jpg)
Before (ex.): 
![WhatShouldIsee](https://user-images.githubusercontent.com/47337816/146549215-084599f5-c77f-45ea-b922-2c744db6e848.jpg)
SNR Adj. now: 
![StabilityAdjNow](https://user-images.githubusercontent.com/47337816/146549337-ed65c7b2-ab76-407b-a8db-132d061223ad.jpg)
SNR Adj before (ex.): 
![SNRadjBefore](https://user-images.githubusercontent.com/47337816/146549529-b8da8122-1679-4d2e-a5d9-d233a0cd7f5b.jpg)
DataRate before: 
![DataRateBefore](https://user-images.githubusercontent.com/47337816/146549778-88c85a6d-afb3-4cc0-9c19-06893c77e3cd.jpg)
DataRate now: 
![DataRateNow](https://user-images.githubusercontent.com/47337816/146549807-115cd57c-6b8d-4c5a-b71d-f77d3c3386b4.jpg)

**Comment by gnuton** [comment]
working on this.

**Comment by gnuton** [comment]
SNR Adj has been fixed and it's in the latest published beta.

BTW from where this comes from? is this a DSL-AX82 config page?
It's a mix of VDSL and ADSL options...
https://user-images.githubusercontent.com/47337816/146549215-084599f5-c77f-45ea-b922-2c744db6e848.jpg

**Comment by JustifYI** [comment]
The screen is just an example since I don't have access to the original page, but yes, a lot of features like "UBPO", "ESNP" are gone now from my "DSL Setting" page.

Actually, the most important setting for me is the "Stability Adjustment" (VDSL2), since I could set it to -2 and gain about 15.000 Kbps in Downstream Data Rate.. but now I can only set positive values only (with the actual firmware: 386.03_2-gnuton5)

I'm gonna try your latest release now :)

And yes, my modem is a "DSL-AX82U"

**Comment by JustifYI** [comment]
Okay, now I can set negative values on "Stability Adjustment", but the SNR target remains at 6.2dB, even if I try to manually set the SNR via command. Do you have any advice?

[Can set negative]
![canSetNegativeNow](https://user-images.githubusercontent.com/47337816/147825425-330de272-60f6-4025-a853-ebd5851feb82.jpg)

[Target still at 6dB]
![snrTargetStill6](https://user-images.githubusercontent.com/47337816/147825445-8ce91926-263d-4e20-91e3-94936a050f02.jpg)

[Tryied with cmds]
![snrWithCmd](https://user-images.githubusercontent.com/47337816/147825452-446d664e-f219-4eb5-bc28-7ea5f489e4d9.jpg)

**Comment by gnuton** [comment]
let me take a better look at this and I will come back.

**Comment by gnuton** [comment]
Hi,
I had a quick look at this today and my understanding is that it would work in case the DSLAM would not ignore it.
I can be wrong, but at moment that was my understanding and what I have seen.
in the firmware I have not found anything wrong.
There is chance also to play with 3rd-party dsl drivers too.. but I am not sure how that would work.
The driver is in /etc/adsl/adsl_phy.bin
You could google for alternative ones in case they have some "improved" capabilities

**Comment by JustifYI** [comment]
I've tried to find something new for the driver, but I think that mine is the latest version(?), actually running "A2pv6L046w.d27m". (But to be honest, I don't know so much about it)

The sad thing is that I could adjust the SNR with Asus stock firmware, so I'll try the following:

1) Bring back the stock firmware and see if the SNR adjustment is working.
2) If it does then I'll put back your latest release and try again to adjust the SNR.

I'll let you know. Thank you for your support btw! :)

**Comment by gnuton** [comment]
yes please let me know if you see differences between my builds and the
stock.
If you spot anything different I will come back to you and fix it.
Thanks for your help

**Comment by JustifYI** [comment]
Okay, with the stock firmware the SNR Adjustment is working. I've tried with -3dB and +10dB. 
Then I put back your latest build and sadly the feature was not working anymore.

Stock FW used: DSL-AX82U_3.0.0.4_386_45660-g37ee6d6
Custom FW used: DSL-AX82U_386.04_0-gnuton1_beta3

[-3dB stock fw]
![Stock_SNR-3dB](https://user-images.githubusercontent.com/47337816/147935082-c4a0b6dc-cc11-41b6-8475-20bd069539c2.jpg)

[+10dB stock fw]
![Stock_SNR+10dB](https://user-images.githubusercontent.com/47337816/147935110-84d53253-84d0-426f-9e7e-656dde17b97e.jpg)

[-3dB custom fw]
![Custom_SNR-3dB](https://user-images.githubusercontent.com/47337816/147935157-89d94e35-4513-4126-a8df-ca524617abf7.jpg)

**Comment by gnuton** [comment]
different driver version. It was missing in the GPL that i got from Asus
then i used the one in my previous version.
I will release a new image with new driver and let's see if that fixes it.
I will ping you once available.

**Comment by JustifYI** [comment]
Should it work if I replace the adsl_phy.bin taking it from the stock FW and placing it in the custom FW?

**Comment by gnuton** [comment]
you must rebuild the firmware for that to work.

**Comment by winter2222** [comment]
I also noticed that DSL driver in your latest build is quite old, nice to see that you are gonna update it soon.

**Comment by JustifYI** [comment]
By the way, I've noticed that even in the stock FW the following settings are not showing anymore:

Rx AGC GAIN Adjustment
UPBO - Upstream Power Back Off
ESNP - Enhanced Sudden Noise Protection
G.vector (G.993.5)
Non-standard G.vector (G.993.5)

Do you have any idea about why they are not shown anymore?

**Comment by gnuton** [comment]
I am not sure yet why these have been removed. Sometimes they are hidden in the page.
I should check the code.

BTW I have built a new image with updated ADSL driver
Please test this if you have some time and let me know if this fixes the problem.
https://1776-175516287-gh.circle-artifacts.com/0/workspace/release/DSL-AX82U_386.4_beta3_cferom_puresqubi.w
thanks al lot

**Comment by JustifYI** [comment]
Just tested and YES, the SNR Adjustment is working now! :)

[SNR Adj. working]
![SNR_workingOnCustomFW](https://user-images.githubusercontent.com/47337816/147995669-3f560633-8eaa-4007-9adb-208f88f397d6.jpg)

Just one last question before closing: I've tried to build the FW by myself following your guide, but I got stuck on the "permissions" while trying to clone the git. Following the troubleshooting, the "id" cmd is not working on PowerShell. Do I need to use a Linux environment? 

(I apologize for the naive questions, but I'm new to this environment)

[git permissions]
![gitPermissions](https://user-images.githubusercontent.com/47337816/147996404-436e7946-1593-471d-b45c-d8b47d58cc92.jpg)

**Comment by gnuton** [comment]
the problem you have is with your github rights.
But I do not think you can sucesfully clone on the repo on a windows FS (which is not case sensitive) and compile it in a linux (case sensitive) environment. 
You will get into troubles.
To build asuswrt I suggest you VMWare or a linux machine.. you can test also WSL/2.
I will close this.
The new driver is in master so it will come withing the next images too.
thanks again.
