### ISSUE TITLE
Firmware upgrade is only accessible through Optus server.

### ISSUE THREAD

**Issue by gnuton** [gnuton/asuswrt-merlin.ng#144]
Check why this code is still here. 

if(isSupport("is_ax5400_i1"))
{
$("#fw_note2").hide();
$("#fw_note3").show();
$("#fw_note3").html("Firmware upgrade is only accessible through Optus server."); //Untranslated
}
my file
https://github.com/gnuton/asuswrt-merlin.ng/commits/gnuton-master/release/src/router/www/Advanced_FirmwareUpgrade_Content.asp

upstream
https://github.com/RMerl/asuswrt-merlin.ng/commits/master/release/src/router/www/Advanced_FirmwareUpgrade_Content.asp

Thread
https://www.snbforums.com/threads/fork-dsl-testers-gnutons-alpha-beta-merlin-builds.71150/page-6

**Comment by gnuton** [comment]
280f469c8d438104c4519d2542e7c57ebe1995d2 fixes it

**Comment by DJE007** [comment]
Yes I confirm it's fixed in 386.04_0-gnuton1_beta4, thank you

**Comment by gnuton** [comment]
awesome! I will close this.
Thakns a lot for your support!
