### ISSUE TITLE
Support for TUF-AX5400

### ISSUE THREAD

**Issue by gnuton** [gnuton/asuswrt-merlin.ng#147]
This thread is about supporting TUF-AX5400.
Feel free to ask questions here. 

Status:
- [x] received GPL
- [x] received development unit
- [x] Merged GPL to feature-branch
- [x] Initial testing & Bugfixing phase
- [x] Public pre-alphas
- [x] Alpha released
- [x] collecting testing reports  & Bugfixing phase
- [x] Beta released
- [x] collecting testing reports  & Bugfixing phase
- [x] Stable released

ETAs:
alpha: End Feb
beta: TBD
stable: TBD

**Comment by salavattvb** [comment]
We are very much waiting for a new firmware from you.

**Comment by Duckface21** [comment]
Is it possible to enable theme shange  so we can switch to  orginal Gray theme insted of the new black one its hard to se on the new asus black theme

**Comment by gnuton** [comment]
The first version is going to be just plain merln. so most probably the theme will be the standard blue one.
@salavattvb can you elaborate more about WiFi gain restrictions?

**Comment by salavattvb** [comment]
> can you elaborate more about WiFi gain restrictions?
For Europe, wi-fi power has been cut. For China, wi-fi is not cut and coverage is greater. I apologize for the Google translation)

**Comment by DPandMe** [comment]
SMB 2.1, 3.0 Plz !!!

**Comment by gnuton** [comment]
@DPandMe SMB upgrade will benefit all routers, for this reason this should come from upstram Merlin. 
I am more keen to add model specific changes.
@salavattvb AFAIK this is not something I can unlock since the firmwareis closed source

**Comment by Duckface21** [comment]
an estimate when do you tink the  merlin firmware is out in first beta os so?

**Comment by gnuton** [comment]
@Duckface21 It depends on when I get the device.. I hope to have the beta by end of Feb.

**Comment by gnuton** [comment]
Update: 
- GPL received.
- The dev unit is scheduled to arrive during middle of Feb.

**Comment by gnuton** [comment]
Update:

- The GPL has been partially merged and it builds and it's in GIT. WWW files must be cherry-picked but I do not have a development unit yet for testing, so I will do that later.

**Comment by gnuton** [comment]
Update:

- I got the dev unit from Asus

- I have merged the GPL into Merlin base code and I do have[ a working branch for TUF-AX5400](https://github.com/gnuton/asuswrt-merlin.ng/tree/DEV_TUF_AX5400) now. I will be releasing the alpha once I do fix most of biggest issues

**Comment by gnuton** [comment]
**PRE-ALPHA TESTING PHASE**

## versions:
1. First[ pre-alpha image is available](https://1930-175516287-gh.circle-artifacts.com/0/workspace/release/TUF-AX5400_386.4_0_cferom_puresqubi.w). PLease do not look at versioning in the page yet.

## WHAT DOESN'T WORK
- [ ] AURA RGB is not working. not able to choose RGB color due to missing ledg.o in the GPL
- [ ] speedtest doesn't work
- [ ] Missing VPN Director


## Basic things to be tested
- [ ] various QOS
- [ ] AIMesh
- [ ] TrendMicro
- [ ] VPNs
- [ ] amtm
- [ ] guest networks
- [ ]

**Comment by gnuton** [comment]
@salavattvb wireguard will come from upstream merlin that is already planned.

**Comment by salavattvb** [comment]
![2022-02-19_00-54-33](https://user-images.githubusercontent.com/97063951/154772096-43ec1b05-9cac-405a-87de-a45f1c423469.png)
Спасибо. Я установил и тестирую. Ззаметил  что не показывает полоски.

**Comment by salavattvb** [comment]
Feb 19 09:17:04 ovpn-client1[4215]: AEAD Decrypt error: bad packet ID (may be a replay): [ #4094 ] -- see the man page entry for --no-replay and --replay-window for more info or silence this warning with --mute-replay-warnings
Feb 19 09:17:04 ovpn-client1[4215]: AEAD Decrypt error: bad packet ID (may be a replay): [ #4095 ] -- see the man page entry for --no-replay and --replay-window for more info or silence this warning with --mute-replay-warnings
Feb 19 09:17:04 ovpn-client1[4215]: AEAD Decrypt error: bad packet ID (may be a replay): [ #4096 ] -- see the man page entry for --no-replay and --replay-window for more info or silence this warning with --mute-replay-warnings
Feb 19 09:17:04 ovpn-client1[4215]: AEAD Decrypt error: bad packet ID (may be a replay): [ #4097 ] -- see the man page entry for --no-replay and --replay-window for more info or silence this warning with --mute-replay-warnings
Feb 19 09:17:04 ovpn-client1[4215]: AEAD Decrypt error: bad packet ID (may be a replay): [ #4098 ] -- see the man page entry for --no-replay and --replay-window for more info or silence this warning with --mute-replay-warnings
Feb 19 09:17:04 ovpn-client1[4215]: AEAD Decrypt error: bad packet ID (may be a replay): [ #4099 ] -- see the man page entry for --no-replay and --replay-window for more info or silence this warning with --mute-replay-warnings
Feb 19 09:17:04 ovpn-client1[4215]: AEAD Decrypt error: bad packet ID (may be a replay): [ #4100 ] -- see the man page entry for --no-replay and --replay-window for more info or silence this warning with --mute-replay-warnings
Feb 19 09:17:04 ovpn-client1[4215]: AEAD Decrypt error: bad packet ID (may be a replay): [ #4101 ] -- see the man page entry for --no-replay and --replay-window for more info or silence this warning with --mute-replay-warnings
Feb 19 09:17:04 ovpn-client1[4215]: AEAD Decrypt error: bad packet ID (may be a replay): [ #4102 ] -- see the man page entry for --no-replay and --replay-window for more info or silence this warning with --mute-replay-warnings
Feb 19 09:17:04 ovpn-client1[4215]: AEAD Decrypt error: bad packet ID (may be a replay): [ #4103 ] -- see the man page entry for --no-replay and --replay-window for more info or silence this warning with --mute-replay-warnings
Feb 19 09:17:04 ovpn-client1[4215]: AEAD Decrypt error: bad packet ID (may be a replay): [ #4104 ] -- see the man page entry for --no-replay and --replay-window for more info or silence this warning with --mute-replay-warnings
Feb 19 09:17:04 ovpn-client1[4215]: AEAD Decrypt error: bad packet ID (may be a replay): [ #4105 ] -- see the man page entry for --no-replay and --replay-window for more info or silence this warning with --mute-replay-warnings
Feb 19 09:17:04 ovpn-client1[4215]: AEAD Decrypt error: bad packet ID (may be a replay): [ #4106 ] -- see the man page entry for --no-replay and --replay-window for more info or silence this warning with --mute-replay-warnings
Feb 19 09:17:04 ovpn-client1[4215]: AEAD Decrypt error: bad packet ID (may be a replay): [ #4107 ] -- see the man page entry for --no-replay and --replay-window for more info or silence this warning with --mute-replay-warnings
Feb 19 09:17:04 ovpn-client1[4215]: AEAD Decrypt error: bad packet ID (may be a replay): [ #4108 ] -- see the man page entry for --no-replay and --replay-window for more info or silence this warning with --mute-replay-warnings
Feb 19 09:17:04 ovpn-client1[4215]: AEAD Decrypt error: bad packet ID (may be a replay): [ #4109 ] -- see the man page entry for --no-replay and --replay-window for more info or silence this warning with --mute-replay-warnings
Feb 19 09:17:04 ovpn-client1[4215]: AEAD Decrypt error: bad packet ID (may be a replay): [ #4110 ] -- see the man page entry for --no-replay and --replay-window for more info or silence this warning with --mute-replay-warnings
Feb 19 09:17:04 ovpn-client1[4215]: AEAD Decrypt error: bad packet ID (may be a replay): [ #4111 ] -- see the man page entry for --no-replay and --replay-window for more info or silence this warning with --mute-replay-warnings
Feb 19 09:17:04 ovpn-client1[4215]: AEAD Decrypt error: bad packet ID (may be a replay): [ #4112 ] -- see the man page entry for --no-replay and --replay-window for more info or silence this warning with --mute-replay-warnings
Feb 19 09:17:04 ovpn-client1[4215]: AEAD Decrypt error: bad packet ID (may be a replay): [ #4113 ] -- see the man page entry for --no-replay and --replay-window for more info or silence this warning with --mute-replay-warnings
Feb 19 09:17:04 ovpn-client1[4215]: AEAD Decrypt error: bad packet ID (may be a replay): [ #4114 ] -- see the man page entry for --no-replay and --replay-window for more info or silence this warning with --mute-replay-warnings
Feb 19 09:17:04 ovpn-client1[4215]: AEAD Decrypt error: bad packet ID (may be a replay): [ #4115 ] -- see the man page entry for --no-replay and --replay-window for more info or silence this warning with --mute-replay-warnings
Feb 19 09:17:04 ovpn-client1[4215]: AEAD Decrypt error: bad packet ID (may be a replay): [ #4116 ] -- see the man page entry for --no-replay and --replay-window for more info or silence this warning with --mute-replay-warnings
Feb 19 09:17:04 ovpn-client1[4215]: AEAD Decrypt error: bad packet ID (may be a replay): [ #4117 ] -- see the man page entry for --no-replay and --replay-window for more info or silence this warning with --mute-replay-warnings
Feb 19 09:17:04 ovpn-client1[4215]: AEAD Decrypt error: bad packet ID (may be a replay): [ #4118 ] -- see the man page entry for --no-replay and --replay-window for more info or silence this warning with --mute-replay-warnings
Feb 19 09:17:04 ovpn-client1[4215]: AEAD Decrypt error: bad packet ID (may be a replay): [ #4119 ] -- see the man page entry for --no-replay and --replay-window for more info or silence this warning with --mute-replay-warnings
Feb 19 09:17:04 ovpn-client1[4215]: AEAD Decrypt error: bad packet ID (may be a replay): [ #4120 ] -- see the man page entry for --no-replay and --replay-window for more info or silence this warning with --mute-replay-warnings
Feb 19 09:17:04 ovpn-client1[4215]: AEAD Decrypt error: bad packet ID (may be a replay): [ #4121 ] -- see the man page entry for --no-replay and --replay-window for more info or silence this warning with --mute-replay-warnings
Feb 19 09:17:04 ovpn-client1[4215]: AEAD Decrypt error: bad packet ID (may be a replay): [ #4122 ] -- see the man page entry for --no-replay and --replay-window for more info or silence this warning with --mute-replay-warnings
Feb 19 09:17:04 ovpn-client1[4215]: AEAD Decrypt error: bad packet ID (may be a replay): [ #4123 ] -- see the man page entry for --no-replay and --replay-window for more info or silence this warning with --mute-replay-warnings
Feb 19 09:17:04 ovpn-client1[4215]: AEAD Decrypt error: bad packet ID (may be a replay): [ #4124 ] -- see the man page entry for --no-replay and --replay-window for more info or silence this warning with --mute-replay-warnings
Feb 19 09:17:04 ovpn-client1[4215]: AEAD Decrypt error: bad packet ID (may be a replay): [ #4125 ] -- see the man page entry for --no-replay and --replay-window for more info or silence this warning with --mute-replay-warnings
Feb 19 09:17:04 ovpn-client1[4215]: AEAD Decrypt error: bad packet ID (may be a replay): [ #4126 ] -- see the man page entry for --no-replay and --replay-window for more info or silence this warning with --mute-replay-warnings
Feb 19 09:17:04 ovpn-client1[4215]: AEAD Decrypt error: bad packet ID (may be a replay): [ #4127 ] -- see the man page entry for --no-replay and --replay-window for more info or silence this warning with --mute-replay-warnings
Feb 19 09:17:04 ovpn-client1[4215]: AEAD Decrypt error: bad packet ID (may be a replay): [ #4128 ] -- see the man page entry for --no-replay and --replay-window for more info or silence this warning with --mute-replay-warnings
Feb 19 09:18:18 ovpn-client1[4215]: AEAD Decrypt error: bad packet ID (may be a replay): [ #9529 ] -- see the man page entry for --no-replay and --replay-window for more info or silence this warning with --mute-replay-warnings
Feb 19 09:18:18 ovpn-client1[4215]: AEAD Decrypt error: bad packet ID (may be a replay): [ #9530 ] -- see the man page entry for --no-replay and --replay-window for more info or silence this warning with --mute-replay-warnings
Feb 19 09:18:18 ovpn-client1[4215]: AEAD Decrypt error: bad packet ID (may be a replay): [ #9531 ] -- see the man page entry for --no-replay and --replay-window for more info or silence this warning with --mute-replay-warnings
Feb 19 09:18:18 ovpn-client1[4215]: AEAD Decrypt error: bad packet ID (may be a replay): [ #9532 ] -- see the man page entry for --no-replay and --replay-window for more info or silence this warning with --mute-replay-warnings
Feb 19 09:18:18 ovpn-client1[4215]: AEAD Decrypt error: bad packet ID (may be a replay): [ #9533 ] -- see the man page entry for --no-replay and --replay-window for more info or silence this warning with --mute-replay-warnings
Feb 19 09:18:18 ovpn-client1[4215]: AEAD Decrypt error: bad packet ID (may be a replay): [ #9534 ] -- see the man page entry for --no-replay and --replay-window for more info or silence this warning with --mute-replay-warnings
Feb 19 09:18:18 ovpn-client1[4215]: AEAD Decrypt error: bad packet ID (may be a replay): [ #9535 ] -- see the man page entry for --no-replay and --replay-window for more info or silence this warning with --mute-replay-warnings
Feb 19 09:18:18 ovpn-client1[4215]: AEAD Decrypt error: bad packet ID (may be a replay): [ #9536 ] -- see the man page entry for --no-replay and --replay-window for more info or silence this warning with --mute-replay-warnings
Feb 19 09:18:18 ovpn-client1[4215]: AEAD Decrypt error: bad packet ID (may be a replay): [ #9537 ] -- see the man page entry for --no-replay and --replay-window for more info or silence this warning with --mute-replay-warnings
Feb 19 09:18:18 ovpn-client1[4215]: AEAD Decrypt error: bad packet ID (may be a replay): [ #9538 ] -- see the man page entry for --no-replay and --replay-window for more info or silence this warning with --mute-replay-warnings
Feb 19 09:18:18 ovpn-client1[4215]: AEAD Decrypt error: bad packet ID (may be a replay): [ #9539 ] -- see the man page entry for --no-replay and --replay-window for more info or silence this warning with --mute-replay-warnings
Feb 19 09:18:18 ovpn-client1[4215]: AEAD Decrypt error: bad packet ID (may be a replay): [ #9540 ] -- see the man page entry for --no-replay and --replay-window for more info or silence this warning with --mute-replay-warnings
Feb 19 09:18:18 ovpn-client1[4215]: AEAD Decrypt error: bad packet ID (may be a replay): [ #9541 ] -- see the man page entry for --no-replay and --replay-window for more info or silence this warning with --mute-replay-warnings
Feb 19 09:18:18 ovpn-client1[4215]: AEAD Decrypt error: bad packet ID (may be a replay): [ #9542 ] -- see the man page entry for --no-replay and --replay-window for more info or silence this warning with --mute-replay-warnings
Feb 19 09:18:18 ovpn-client1[4215]: AEAD Decrypt error: bad packet ID (may be a replay): [ #9543 ] -- see the man page entry for --no-replay and --replay-window for more info or silence this warning with --mute-replay-warnings
Feb 19 09:18:18 ovpn-client1[4215]: AEAD Decrypt error: bad packet ID (may be a replay): [ #9544 ] -- see the man page entry for --no-replay and --replay-window for more info or silence this warning with --mute-replay-warnings
Feb 19 09:18:18 ovpn-client1[4215]: AEAD Decrypt error: bad packet ID (may be a replay): [ #9545 ] -- see the man page entry for --no-replay and --replay-window for more info or silence this warning with --mute-replay-warnings
Feb 19 09:18:18 ovpn-client1[4215]: AEAD Decrypt error: bad packet ID (may be a replay): [ #9546 ] -- see the man page entry for --no-replay and --replay-window for more info or silence this warning with --mute-replay-warnings
Feb 19 09:18:18 ovpn-client1[4215]: AEAD Decrypt error: bad packet ID (may be a replay): [ #9547 ] -- see the man page entry for --no-replay and --replay-window for more info or silence this warning with --mute-replay-warnings
Feb 19 09:18:18 ovpn-client1[4215]: AEAD Decrypt error: bad packet ID (may be a replay): [ #9548 ] -- see the man page entry for --no-replay and --replay-window for more info or silence this warning with --mute-replay-warnings
Feb 19 09:18:18 ovpn-client1[4215]: AEAD Decrypt error: bad packet ID (may be a replay): [ #9549 ] -- see the man page entry for --no-replay and --replay-window for more info or silence this warning with --mute-replay-warnings
Feb 19 09:18:18 ovpn-client1[4215]: AEAD Decrypt error: bad packet ID (may be a replay): [ #9550 ] -- see the man page entry for --no-replay and --replay-window for more info or silence this warning with --mute-replay-warnings
Feb 19 09:18:18 ovpn-client1[4215]: AEAD Decrypt error: bad packet ID (may be a replay): [ #9551 ] -- see the man page entry for --no-replay and --replay-window for more info or silence this warning with --mute-replay-warnings
Feb 19 09:18:18 ovpn-client1[4215]: AEAD Decrypt error: bad packet ID (may be a replay): [ #9552 ] -- see the man page entry for --no-replay and --replay-window for more info or silence this warning with --mute-replay-warnings
Feb 19 09:18:18 ovpn-client1[4215]: AEAD Decrypt error: bad packet ID (may be a replay): [ #9553 ] -- see the man page entry for --no-replay and --replay-window for more info or silence this warning with --mute-replay-warnings
Feb 19 09:18:18 ovpn-client1[4215]: AEAD Decrypt error: bad packet ID (may be a replay): [ #9554 ] -- see the man page entry for --no-replay and --replay-window for more info or silence this warning with --mute-replay-warnings
Feb 19 09:18:18 ovpn-client1[4215]: AEAD Decrypt error: bad packet ID (may be a replay): [ #9555 ] -- see the man page entry for --no-replay and --replay-window for more info or silence this warning with --mute-replay-warnings
Feb 19 09:18:18 ovpn-client1[4215]: AEAD Decrypt error: bad packet ID (may be a replay): [ #9556 ] -- see the man page entry for --no-replay and --replay-window for more info or silence this warning with --mute-replay-warnings
Feb 19 09:18:18 ovpn-client1[4215]: AEAD Decrypt error: bad packet ID (may be a replay): [ #9557 ] -- see the man page entry for --no-replay and --replay-window for more info or silence this warning with --mute-replay-warnings
Feb 19 09:18:18 ovpn-client1[4215]: AEAD Decrypt error: bad packet ID (may be a replay): [ #9558 ] -- see the man page entry for --no-replay and --replay-window for more info or silence this warning with --mute-replay-warnings
Feb 19 09:18:18 ovpn-client1[4215]: AEAD Decrypt error: bad packet ID (may be a replay): [ #9559 ] -- see the man page entry for --no-replay and --replay-window for more info or silence this warning with --mute-replay-warnings
Feb 19 09:18:18 ovpn-client1[4215]: AEAD Decrypt error: bad packet ID (may be a replay): [ #9560 ] -- see the man page entry for --no-replay and --replay-window for more info or silence this warning with --mute-replay-warnings
Feb 19 09:18:18 ovpn-client1[4215]: AEAD Decrypt error: bad packet ID (may be a replay): [ #9561 ] -- see the man page entry for --no-replay and --replay-window for more info or silence this warning with --mute-replay-warnings
Feb 19 09:18:18 ovpn-client1[4215]: AEAD Decrypt error: bad packet ID (may be a replay): [ #9562 ] -- see the man page entry for --no-replay and --replay-window for more info or silence this warning with --mute-replay-warnings
Feb 19 09:18:18 ovpn-client1[4215]: AEAD Decrypt error: bad packet ID (may be a replay): [ #9563 ] -- see the man page entry for --no-replay and --replay-window for more info or silence this warning with --mute-replay-warnings
Feb 19 09:18:18 ovpn-client1[4215]: AEAD Decrypt error: bad packet ID (may be a replay): [ #9564 ] -- see the man page entry for --no-replay and --replay-window for more info or silence this warning with --mute-replay-warnings
Feb 19 09:18:18 ovpn-client1[4215]: AEAD Decrypt error: bad packet ID (may be a replay): [ #9565 ] -- see the man page entry for --no-replay and --replay-window for more info or silence this warning with --mute-replay-warnings
Feb 19 09:18:18 ovpn-client1[4215]: AEAD Decrypt error: bad packet ID (may be a replay): [ #9566 ] -- see the man page entry for --no-replay and --replay-window for more info or silence this warning with --mute-replay-warnings
Feb 19 09:18:18 ovpn-client1[4215]: AEAD Decrypt error: bad packet ID (may be a replay): [ #9567 ] -- see the man page entry for --no-replay and --replay-window for more info or silence this warning with --mute-replay-warnings
Feb 19 09:18:18 ovpn-client1[4215]: AEAD Decrypt error: bad packet ID (may be a replay): [ #9568 ] -- see the man page entry for --no-replay and --replay-window for more info or silence this warning with --mute-replay-warnings
Feb 19 09:18:18 ovpn-client1[4215]: AEAD Decrypt error: bad packet ID (may be a replay): [ #9569 ] -- see the man page entry for --no-replay and --replay-window for more info or silence this warning with --mute-replay-warnings
Feb 19 09:18:18 ovpn-client1[4215]: AEAD Decrypt error: bad packet ID (may be a replay): [ #9570 ] -- see the man page entry for --no-replay and --replay-window for more info or silence this warning with --mute-replay-warnings
Feb 19 09:18:18 ovpn-client1[4215]: AEAD Decrypt error: bad packet ID (may be a replay): [ #9571 ] -- see the man page entry for --no-replay and --replay-window for more info or silence this warning with --mute-replay-warnings
Feb 19 09:18:18 ovpn-client1[4215]: AEAD Decrypt error: bad packet ID (may be a replay): [ #9572 ] -- see the man page entry for --no-replay and --replay-window for more info or silence this warning with --mute-replay-warnings
Feb 19 09:18:18 ovpn-client1[4215]: AEAD Decrypt error: bad packet ID (may be a replay): [ #9573 ] -- see the man page entry for --no-replay and --replay-window for more info or silence this warning with --mute-replay-warnings
Feb 19 09:18:18 ovpn-client1[4215]: AEAD Decrypt error: bad packet ID (may be a replay): [ #9574 ] -- see the man page entry for --no-replay and --replay-window for more info or silence this warning with --mute-replay-warnings
Feb 19 09:18:18 ovpn-client1[4215]: AEAD Decrypt error: bad packet ID (may be a replay): [ #9575 ] -- see the man page entry for --no-replay and --replay-window for more info or silence this warning with --mute-replay-warnings
Feb 19 09:18:18 ovpn-client1[4215]: AEAD Decrypt error: bad packet ID (may be a replay): [ #9576 ] -- see the man page entry for --no-replay and --replay-window for more info or silence this warning with --mute-replay-warnings
Feb 19 09:18:18 ovpn-client1[4215]: AEAD Decrypt error: bad packet ID (may be a replay): [ #9577 ] -- see the man page entry for --no-replay and --replay-window for more info or silence this warning with --mute-replay-warnings
Feb 19 09:18:18 ovpn-client1[4215]: AEAD Decrypt error: bad packet ID (may be a replay): [ #9578 ] -- see the man page entry for --no-replay and --replay-window for more info or silence this warning with --mute-replay-warnings
Feb 19 09:18:18 ovpn-client1[4215]: AEAD Decrypt error: bad packet ID (may be a replay): [ #9579 ] -- see the man page entry for --no-replay and --replay-window for more info or silence this warning with --mute-replay-warnings
Feb 19 09:18:18 ovpn-client1[4215]: AEAD Decrypt error: bad packet ID (may be a replay): [ #9580 ] -- see the man page entry for --no-replay and --replay-window for more info or silence this warning with --mute-replay-warnings
Feb 19 09:18:18 ovpn-client1[4215]: AEAD Decrypt error: bad packet ID (may be a replay): [ #9581 ] -- see the man page entry for --no-replay and --replay-window for more info or silence this warning with --mute-replay-warnings
Feb 19 09:18:18 ovpn-client1[4215]: AEAD Decrypt error: bad packet ID (may be a replay): [ #9582 ] -- see the man page entry for --no-replay and --replay-window for more info or silence this warning with --mute-replay-warnings
Feb 19 09:18:18 ovpn-client1[4215]: AEAD Decrypt error: bad packet ID (may be a replay): [ #9583 ] -- see the man page entry for --no-replay and --replay-window for more info or silence this warning with --mute-replay-warnings

**Comment by VyachesDram** [comment]
Make a brightness adjustment LEDs.

**Comment by gnuton** [comment]
@VyachesDram LED is completely broken in this build. I am wairing for a fix from ASUS.

**Comment by gnuton** [comment]
@salavattvb as for the 
'''Feb 19 09:18:18 ovpn-client1[4215]: AEAD Decrypt error: bad packet ID (may be a replay): [ #9583 ] -- see the man page entry for --no-replay and --replay-window for more info or silence this warning with --mute-replay-warnings'''
https://www.snbforums.com/threads/openvpn-client-expressvpn-on-asus-merlin-386-1-not-uploading-correctly-vpn-client-disconnects-after-midnight.70442/

**Comment by vladut123** [comment]
> @VyachesDram LED is completely broken in this build. I am wairing for a fix from ASUS.

Waiting?

**Comment by gnuton** [comment]
@vladut123 yes sorry for the typo. I am waiting for Asus to send me new GPLs.
They promomise I will get all new ones by the end of this week.

**Comment by gnuton** [comment]
Beta available here https://github.com/gnuton/asuswrt-merlin.ng/releases/tag/386.05_0-gnuton0_beta1

**Comment by JPatrick2398** [comment]
Nice work @gnuton. Is there a chance that you'll also support TUF-AX3000? Or just the TUF AX-5400?
I have an AC68U and TUF-AX3000, I can say that AC68u with merlin firmware is much more stable than the TUF AX-3000 considering their hardware specifications, in which the TUF-AX3000 has a higher specs than the AC68u, firmware really has a greater impact.

**Comment by gnuton** [comment]
Please add your thumb up here. There is chance for me to support more
models, but at moment no plans yet.
https://github.com/gnuton/asuswrt-merlin.ng/issues/140

**Comment by gizmosngadgetz** [comment]
Thanks for your hardwork and contributions! I can't seem to find the DNSfilter tab under LAN. Is it hidden away somewhere else or not included in this beta? 

The router also doesn't seem to read my nat-start script in /jffs/scripts/ ...though perhaps this is my fault since its my first time doing this. I've made the file executable and used Notepad++ so it had proper UNIX headers. Anything else I should check?

**Comment by gnuton** [comment]
d1e82842ee fixes DL/UP invisible bars. Fix in the next beta.

**Comment by gnuton** [comment]
@gizmosngadgetz DNSFilter fixed (more info here https://github.com/gnuton/asuswrt-merlin.ng/issues/169)

**Comment by pyadvichuk** [comment]
Nice work @gnuton, thanks a bunch. Is it possible to add `usbip` host modules to the build? like
```
CONFIG_USBIP_CORE=y
CONFIG_USBIP_HOST=y
```

**Comment by Absent83** [comment]
Is there any information about the **OpenVPN client**? Does it work?

**Comment by gnuton** [comment]
@pyadvichuk please open a ticket for that since it's an enanchement. 
Please describe the reason and why other people would need that too.

**Comment by gnuton** [comment]
@Absent83 I have not tested that but TUF-AX5400 but if that's a merlin option you should have it on my images too and if it's not there please ping me

**Comment by Absent83** [comment]
I have bought TUF-AX5400 and updated with **Unstable 386.05_0-gnuton0_beta1 Pre-release**

There is a parameter, that I mentioned before.

![изображение](https://user-images.githubusercontent.com/38653973/159711350-23651d89-5f1d-4d98-896e-ff1bd9da0277.png)


I will check how it works.

**Comment by Fatmajk** [comment]
Amazing work @gnuton . Highly appreciated works, really. Looking forward to see a stable build! 
**Thanks a lot!**

**Comment by swiffer** [comment]
Tested OpenVPN Client Setup after flashing the Firmware (works finde!) However VPN Director Policy Based Routing ist Missing From the GUI as Well as VPN Status

 https://github.com/RMerl/asuswrt-merlin.ng/wiki/VPN-Director

**Comment by gizmosngadgetz** [comment]
> @gizmosngadgetz DNSFilter fixed (more info here #169)

Thanks! Reading through your changes log, I realized the feature is activated and I can access it directly through .../DNSFilter.asp

Likewise, I noticed that **Advanced VPN Director** tab is missing, but is an activated feature that I can access directly through .../Advanced_VPNDirector.asp

**Comment by swiffer** [comment]
@gizmosngadgetz thanks! Works like a charm!

**Comment by Bilk0** [comment]
Flashed it last night and am impressed how stable  it is for a beta release.  So far so good. Thank you for your hard work.

**Comment by gnuton** [comment]
Stable released! Enjoy!

**Comment by Bilk0** [comment]
Installed the stable release and its working well, no issues identified and thank you once again for your hard work in getting this working on the AX5400.

**Comment by RichMD** [comment]
Will the GS-AX5400 be supported (almost identical hardware)?

**Comment by gnuton** [comment]
@RichMD no plans as for now.
Please add your vote here https://github.com/gnuton/asuswrt-merlin.ng/issues/140 btw

**Comment by Bilk0** [comment]
One thing I have noted is that RAM usage appears to be lower using this Merlin Firmware, on stock FW I would often see only around 55MB free, with this FW this has risen to around 150MB free.

**Comment by Duckface21** [comment]
is it possible to add support fpr NTP server in merlin så  every comp sync time  whit router

**Comment by gnuton** [comment]
@Duckface21 ilocal NTP server is already in the image. you can enable from http://router.asus.com/Advanced_System_Content.asp

**Comment by fededim** [comment]
Flashed yesterday, custom hosts file works perfectly, @gnuton thank you very much for this release!

**Comment by Bilk0** [comment]
@gnuton , 

I have VPN Client on, (using VPN Director to assign various devices to WAN or VPN), I have checked and my VPN is working. 
I also have AI Protection on , QOS (Adaptive) on, Traffic Analyser On, LAG on and a USB RAID connected to USB port, but RAM usage is still lower than stock FW (Currently have 130MB free).  Its been rock solid , I fact, I was just testing the AX5400 as I have a complete Unifi setup on my home network (USG Pro 4 (Upgraded to 4GB), 6 switches, 4x APs , Unfi Protect with 4 cameras), but I have deactivated the USG Pro and 2xAPs and am using the AX5400 as I am liking the additional features. 
I am very pleased with the firmware you have provided, kudos for doing such a great job and to Merlin of course.

**Comment by fauxfongers** [comment]
> Stable released! Enjoy!

Is there a reason why ax5400 isn't on SourceForge, but is available on GitHub?
At first I saw only the Alpha cause it didn't appear on merlin website nor on SF.

**Comment by gnuton** [comment]
@fauxfongers 
This github is maintained by a different person.
SF is the main project and he maintains some models, but he cannot maintain all of them.
I have started with DSL routers but then I got asked by the lead merlin dev to support more routers..

**Comment by ajdee2** [comment]
i have TUF-AX5400 is't any working stable version to this router ?
and is there any version that has support for wireguard in vpn

**Comment by Duckface21** [comment]
HI under Open VPN server is there a chanse to enable more then one Server instance 2 is not the best for my use

**Comment by gnuton** [comment]
It was decreased in order to avoid stability issue due to low RAM

**Comment by Duckface21** [comment]
oki but wold it be possible to enable more  but add a stability warning whit more then 2 running so usersn know

**Comment by gnuton** [comment]
I am not sure I need to check it. This was an upstream change btw, so other merlin routers with latest firmware have same limitation.

**Comment by Duckface21** [comment]
oki wold be nice if u can check
