### ISSUE TITLE
Administration - Firmware Upgrade

### ISSUE THREAD

**Issue by zendilar** [gnuton/asuswrt-merlin.ng#15]
when you go to
http://router.asus.com/Advanced_FirmwareUpgrade_Content.asp
for the seting of Scheduled check for new firmware availability yes or no option can not be saved
for the Firmware Version if you click check the page displayed is https://www.asus.com/kr/

check if it can that be fixed when you can.

**Comment by gnuton** [comment]
That's a missing feature, I was planning to add it.
It requires some back-end infrastructure too to host the manifest file which contains the releases. 
It's in the TODO list

**Comment by gnuton** [comment]
![image](https://user-images.githubusercontent.com/576580/58050513-3949ff00-7b58-11e9-830d-e71e0b65adae.png)
Ok implemented and now in testing! :D

**Comment by gnuton** [comment]
tested and it will be part of the next release!

**Comment by zendilar** [comment]
you are the man mate. if you want send me a link so I can test it from my side to

**Comment by gnuton** [comment]
Here it is https://github.com/gnuton/asuswrt-merlin.ng/releases/tag/384.11-gnuton3_alpha1

**Comment by gnuton** [comment]
This feature has been released. There is a bug in the merlin script which checks for the updates which doesn't check minor firmware version by string. This has been fixed already and it's in testing in 384.11_2-gnuton2_alpha1.

**Comment by gnuton** [comment]
Implemented and released the fix https://github.com/gnuton/asuswrt-merlin.ng/releases/tag/384.11_2-gnuton2
