### ISSUE TITLE
Traffic monitoring slows down lan

### ISSUE THREAD

**Issue by Revenger** [gnuton/asuswrt-merlin.ng#150]
**Router Model Affected**
Models: (eg: DSL-AC68U)

**Firmware Version Affected**
386.03_2-gnuton5

**Is this bug present in upstream Merlin releases too?**
Yes

**Describe the bug**
Running traffic monitoring slows lan upload down speedtest showed significant speedloss.
Wifi is fine, affects LAN devices.

**To Reproduce**
1. Turn on traffic monitoring
2. Speedtest.net
3. Upload went from 25Mbps to 4Mbps
4. Turn off monitoring upload back to normal.

**Expected behavior**
No speed loss

**Screenshots**
Traffic Manager Off
https://imgur.com/XAr1zsB

Traffic Manager On
https://imgur.com/aQkopw7

Thread for the RT-88U where the issue was found.
https://www.snbforums.com/threads/slow-upload-on-386-2_4-asus-rt-ac88u.72483/page-2

**Comment by Revenger** [comment]
Changed Stability and Dynamic Line Adjustment to off and the Annax from B to A and upload is fine on traffic manager both on and off.
Will keep a eye on things.

Could be one of those settings causing it.

**Comment by gnuton** [comment]
Hi can you please test the beta firmware too. It should be stable now...

**Comment by gnuton** [comment]
The next release will be based on the current beta and since it's fine I think this problem doesn't exist for it.
right?
if so can we close this task or is there any reason to keep this open? (you can always re-open it)

**Comment by Revenger** [comment]
Upload is fine now so yea can close this and will reopen of needed.
