### ISSUE TITLE
Support for DNS over HTTPS (DOH)?

### ISSUE THREAD

**Issue by HamidZaeri** [gnuton/asuswrt-merlin.ng#152]
Hi

Does this firmware support DOH for DSL-Ac68U?
If yes, where is the option for it or how can i config it? (I did not find any settings related to DOH)

If no, is there any plan to implement this must have feature?

**Comment by gnuton** [comment]
hi @HamidZaeri it's supported I think there has been a bad merge..
I will enable it with next release.

**Comment by gnuton** [comment]
[just for me]
To fix this I need to reapply this patch
https://github.com/gnuton/asuswrt-merlin.ng/commit/f9c224d6896b8171c7934113a29f16550247dcf5#diff-456a4177443b2c80afe01e949cfbbdce1b0485a1d88b0df11cfee6fb00ccea9a

**Comment by gnuton** [comment]
Test images:
those are safe to install just current stable + fix for DNS SEC + dns over tls
https://1832-175516287-gh.circle-artifacts.com/0/workspace/release/DSL-AX82U_386.4_0_cferom_puresqubi.w
https://1830-175516287-gh.circle-artifacts.com/0/workspace/release/DSL-AC68U_386.4_0_DSL_1.0.5.3.trx
Any feedback  is welcome

**Comment by TrilIiard** [comment]
Everything seems to work great so far

**Comment by gnuton** [comment]
@TrilIiard have you tested DOH?

**Comment by TrilIiard** [comment]
Working, but cant test secure sni because i just dont know how

**Comment by Hello-olleH** [comment]
> Test images: those are safe to install just current stable + fix for DNS SEC + dns over tls https://1832-175516287-gh.circle-artifacts.com/0/workspace/release/DSL-AX82U_386.4_0_cferom_puresqubi.w https://1830-175516287-gh.circle-artifacts.com/0/workspace/release/DSL-AC68U_386.4_0_DSL_1.0.5.3.trx Any feedback is welcome

Before Update: 
<img width="807" alt="Screen Shot 2022-01-28 at 23 05 09" src="https://user-images.githubusercontent.com/45637723/151629929-c6023512-89ac-463e-9c66-bfd8303d09a4.png">

After Update: 
<img width="690" alt="Screen Shot 2022-01-28 at 23 17 17" src="https://user-images.githubusercontent.com/45637723/151629948-09a0eee2-6d4a-47ce-a6d8-ad97287275ab.png">

Test Result: 
https://cloudflare-dns.com/help/
<img width="630" alt="Screen Shot 2022-01-28 at 23 24 16" src="https://user-images.githubusercontent.com/45637723/151629968-feb777fd-1dd2-4014-b558-71b1312964f9.png">


Thank You!

**Comment by Hello-olleH** [comment]
A little bug: 
It says to me, there is an Update :D 

<img width="1026" alt="Screen Shot 2022-01-28 at 23 41 55" src="https://user-images.githubusercontent.com/45637723/151631530-a9d92d21-2c29-460f-b55d-816524ad985b.png">

**Comment by gnuton** [comment]
@Hello-olleH that's not a but.. that's fine. It just try to make you move back to stable since this is an internal build which has random version. 
Thanks a lot for testing

**Comment by gnuton** [comment]
changes released within the latest stable: https://github.com/gnuton/asuswrt-merlin.ng/issues/152

**Comment by HamidZaeri** [comment]
> changes released within the latest stable: #152

This feature is not supported for ADSL ?

**Comment by Hello-olleH** [comment]
Disabled DoT but Server List can't be deleted

**Comment by Hello-olleH** [comment]
@gnuton
