### ISSUE TITLE
RT-AC88U WPS Problem

### ISSUE THREAD

**Issue by mihu15** [gnuton/asuswrt-merlin.ng#155]
**Router Model Affected**
Models: RT-AC88U

**Firmware Version Affected**
386.4

**Describe the bug**
When pressing WPS button on device it is flash twice and turn off. Checked in web gui and when I proceed to discover new devices it jus refresh the page. On stock firmware working normal without problems.

**Comment by gnuton** [comment]
I do not support this model sorry.
