### ISSUE TITLE
VPN policy based on Wi-Fi SSID

### ISSUE THREAD

**Issue by HamidZaeri** [gnuton/asuswrt-merlin.ng#157]
Hi

It's nice to be able to use a vpn by connecting to a specific wi-fi (e.g a Wi-Fi guest SSID).

And not use VPN (direct connection) by connecting to another SSID.

**Comment by gnuton** [comment]
Hi,
This is nice and I agree. Some people have done this already and the instructions are in forum.

**Comment by HamidZaeri** [comment]
> Hi, This is nice and I agree. Some people have done this already and the instructions are in forum.

you mean snb by forum? right?

**Comment by gnuton** [comment]
I will close this issue than
