### ISSUE TITLE
Support for ZenWifi XT8

### ISSUE THREAD

**Issue by gnuton** [gnuton/asuswrt-merlin.ng#158]
This thread is about supporting TUF-AX5400.
Feel free to ask questions here. 

Status:
- [x] received GPL
- [x] received development unit
- [x] Merged GPL to feature-branch
- [x] Initial testing & Bugfixing phase
- [x] Public pre-alphas
- [x] Alpha released
- [x] collecting testing reports  & Bugfixing phase
- [x] Beta released
- [x] collecting testing reports  & Bugfixing phase
- [x] Stable released

ETAs:
alpha: TBD
beta: TBD
stable: TBD

**Comment by gnuton** [comment]
Note:
 The following sw has been added and prebuilds copy tool must be updated:
 - router/i2c-tools-2013-12-15
 - btconfig
 - bluez

**Comment by gnuton** [comment]
Beta available here https://github.com/gnuton/asuswrt-merlin.ng/releases/tag/386.05_0-gnuton0_beta1

**Comment by sadoneli** [comment]
RT-AX95Q (ZenWiFi_AX6600) Tools_Sysinfo.asp page error

1. missing model RT-AX95Q: https://github.com/gnuton/asuswrt-merlin.ng/blob/gnuton-master/release/src/router/httpd/sysinfo.c#L632
2. missing model `MODEL_RTAX95Q`: https://github.com/gnuton/asuswrt-merlin.ng/blob/gnuton-master/release/src/router/httpd/sysinfo.c#L199

![image](https://user-images.githubusercontent.com/10495520/156935666-a62dbe50-fb11-4dbf-a18a-6f37723e9ff0.png)

**Comment by woudt** [comment]
One minor issue found, otherwise the firmware seems to werk perfectly fine for me!

The WiFi Radar option is shown on the menu, but leads to a page not found error.

<img width="746" alt="Screenshot 2022-03-08 153240" src="https://user-images.githubusercontent.com/1714338/157259682-9bd758a7-ed2f-4f22-aa08-96b1487c7ffc.png">

<img width="770" alt="Screenshot 2022-03-08 153043" src="https://user-images.githubusercontent.com/1714338/157259491-fe30348f-31ef-4b09-a6f1-a992d18f4f95.png">

**Comment by gnuton** [comment]
I will try to fix this with the next beta

**Comment by gnuton** [comment]
just for myself... the fix for this is similar as in a561e6a7a2a

**Comment by gnuton** [comment]
all issues fixed and stable released!

**Comment by axeloz** [comment]
Thanks a lot @gnuton for your work. I was waiting for this for quite some time. 
I'm just a little bit confused: you are talking of the XT8 but you wrote:
`This thread is about supporting TUF-AX5400.`

For me, the XT8 is AX6600 as confirmed here: https://www.asus.com/fr/Networking-IoT-Servers/Whole-Home-Mesh-WiFi-System/ZenWiFi-WiFi-Systems/ASUS-ZenWiFi-AX-XT8/techspec/
The one I own is the XT8 (B-1-PK) has shown on the link above. Is it compatible?

Thanks a lot

**Comment by clementchong** [comment]
Possible to enable link aggregation or is this limited by hardware?

**Comment by gnuton** [comment]
XT8 merlin images are provided by me and I do release them only on github
and not on the website.
This is in any case an official fork.

**Comment by sirdragonlord** [comment]
Hi,

Just got the XT8 twin pack and wondered if this fixes issues with guest networking, as asus firmware says supports all nodes, but doesn't actually work and can only use guest from main unit set as router.

Thanks

**Comment by gnuton** [comment]
@sirdragonlord AiMesh and guest networks are closed source components the expectation is merlin would work just like stock firmware when it comes to this

**Comment by gnuton** [comment]
Correct. I would expect the same behaviour

**Comment by idaband** [comment]
Does this also work with the et8?

**Comment by jazzyblu** [comment]
I've read that AiMesh only worked with Ethernet connected (in the beginning?) Is this still the case with the current version? Can I "set up" with Ethernet, disconnect and unplug the satellite and power on somewhere else and have it work via WLAN only? I have a base and two satellites that currently run fine without cable on stock FW.

**Comment by duncdog** [comment]
Unsure if this is the place for it, but I don't see it stated anywhere. ASUS began shipping a V2 of this hardware, and explicitly states they need to use their own bespoke versions of the firmware on the main site vs V1 hardware. As this code predates the V2 hardware, I understand this supports V1 hardware. Curious if you could add a clarifier for this hardware sku on the relevant pages for future reference or confusion removal? Thanks!

**Comment by rshoover2001** [comment]
Having this precise issue, and bought a third node which happens to be HW V2.

nvram get productid returns "XT8_V2"

The RT-AX95U firmware does not work on this device. Will there be support in the future?

**Comment by nuller1joe** [comment]
I just bought another 2 XT8 nodes, however, they are hardware version 2. 
Like @rshoover2001 asked, is there any chance this firmware will support the hw ver v2?
I think the XT8 is more or less useless with stock firmware

**Comment by jimjim413** [comment]
I have just brought a XT8 V2 , wondering if I can use Merlin firmware on it ? Thanks

**Comment by sanjeroHUN** [comment]
Hi jimjim413! 
I am asking the same question... I have tried to upload the firmware, but nothing happened. Have you tried?

**Comment by jimjim413** [comment]
> Hi jimjim413! 
> 
> I am asking the same question... I have tried to upload the firmware, but nothing happened. Have you tried?

Hi ,

I haven't tried it because I believe that V2 using different firmware from V1, so waiting for Merlin firmware for V2 before trying.

**Comment by gnuton** [comment]
V2 has different firmware that is build from a different SDK

**Comment by ehb224** [comment]
> V2 has different firmware that is build from a different SDK
Does that mean it won't be supported?

**Comment by gnuton** [comment]
@ehb224 no it doesn't mean that. It's just a difference which software wise makes the router really different even if the hardware may be similar

**Comment by ehb224** [comment]
Any idea on the time frame for v2 firmware? I just bought a pair of these and if I need to return them for a different model I will.  However if we are only looking at a few months I can live with stock firmware. I thank you in advance.

**Comment by ABitBA** [comment]
Hey, thanks for your effort to keep the device alive with new firmware and improve it. I only had problems with the V1 as far as a stable backhaul connection is concerned. Hence the change now!

I have installed the firmware 3004.388.4_0-gnuton1 and I noticed that I can only manage 720Mbit via the node with activated backhaul instead of 930Mbit WAN (ASUS official firmware). My computer is connected to the node with 1Gbit and my 1Gbit Internet line could be almost completely exhausted before. On the main router the 930Mbt are fully available... The utilization of the CPU and RAM is not particularly high during the test. The connection between the node and the main router is great

**Comment by gnuton** [comment]
@ABitBA I am not sure how you get these values, you can try to reset to factory and try with a fresh installation without previous settings and see if that helps. I am not aware of anything which can cause this.

**Comment by ABitBA** [comment]
Thank you for your quick reply. I have reset the router to factory settings and reconfigured it manually. (no old data imported)

**Comment by Alfiegerner** [comment]
All those adding comments requesting v2 make sure you add a thumbs up on the requested devices tracker:
 https://github.com/gnuton/asuswrt-merlin.ng/issues/523

**Comment by haneefmubarak** [comment]
Hey @gnuton! Sent over an email you about hopefully helping with XT8 v2 support. Just a heads up in case you check GitHub more. Will also join the Discord in case that is easier to chat on. Cheers!
