### ISSUE TITLE
DNS over TLS preset servers missing

### ISSUE THREAD

**Issue by gnuton** [gnuton/asuswrt-merlin.ng#16]
![image](https://user-images.githubusercontent.com/576580/57717068-0ea50580-7683-11e9-9308-415a944b0da4.png)

**Comment by juwgxibz** [comment]
I can't find it in 384.11-gnuton2-alpha1

**Comment by juwgxibz** [comment]
shall I switch to Italian?

**Comment by gnuton** [comment]
LOL, :D the localization is quite good.. so if you can understand some
italian.. why not? be my guest.
no jokes. sorry next time I will switch to english.

**Comment by gnuton** [comment]
I missed your first comment.. here it's is in English and the place where you can find it in the menus
![image](https://user-images.githubusercontent.com/576580/57725889-e7f0ca00-7696-11e9-9125-de2b3747f29c.png)

**Comment by juwgxibz** [comment]
I'm can't figure out, I'm flashed 384.11-gnuton2-alpha1, but there is not DoT in WAN in DSL WAN. The same situation I was wrote in SNB. Sorry.

**Comment by juwgxibz** [comment]
What information you need if you planned to fix it?

**Comment by gnuton** [comment]
The first thing I would like to know if you have the variable "dnspriv": 1
in http://router.asus.com/state.js
[image: image.png]

**Comment by Keltere** [comment]
@gnuton dnspriv present for me but no DNS over TLS settings.

**Comment by gnuton** [comment]
is it set to 1 or 0?
I have just published this pre-release which fixes the presets
https://github.com/gnuton/asuswrt-merlin.ng/releases/tag/384.11-gnuton2-alpha2 (which was the bug of this issue)

**Comment by gnuton** [comment]
I will close this issue since the bug described has been fixed.
Please flash the latest pre-release (link above) and factory reset the router if you can.
Hopefully, you will see DOT in the WAN menu.
 If not please open a new issue and we will try to figure out why you cannot see it.. or why I can see it.. or I dunno :D

**Comment by Keltere** [comment]
It is set to 1 on alpha2 and even on alpha1. I've installed the alpha 2 but still no DNS over TLS.

**Comment by gnuton** [comment]
@Keltere I filled this issue https://github.com/gnuton/asuswrt-merlin.ng/issues/17 I think we can talk about this there.
