### ISSUE TITLE
TUF-AX5400 386.5 Tools_Sysinfo.asp page menu portal missing

### ISSUE THREAD

**Issue by sadoneli** [gnuton/asuswrt-merlin.ng#164]
**Router Model Affected**
Models: TUF-AX5400

**Firmware Version Affected**
386.5

**Is this bug present in upstream Merlin releases too?**
No

**Describe the bug**
TUF-AX5400 386.5 Tools_Sysinfo.asp page is avaliable, however menu portal is missing

**Screenshots**
![FireShot Capture 026 - ASUS Wireless Router TUF-AX5400 - System Information - 192 168 50 1](https://user-images.githubusercontent.com/10495520/156974461-5629659c-ae71-491d-9e66-033a9d5ad8ba.png)

**Comment by vladut123** [comment]
Edit the firmware version is 386.5 not 384

**Comment by gnuton** [comment]
ed81a13711 should fix this issue

**Comment by gnuton** [comment]
tested but icon missing..

**Comment by sadoneli** [comment]
new golden icon for this page maybe needed？

**Comment by gnuton** [comment]
can you elaborate more?

**Comment by gnuton** [comment]
fixed in the latest stable
