### ISSUE TITLE
Hi, would you like to add a new support for tuf-ax3000?

### ISSUE THREAD

**Issue by yk00365** [gnuton/asuswrt-merlin.ng#165]
Hi, would you like to add a new support for tuf-ax3000?
Because the hardware of tuf-ax3000 same as tuf-5400,only the cfe is not same,so I would like you to add the support for tuf-ax3000.

https://www.asus.com/Networking-IoT-Servers/WiFi-Routers/ASUS-Gaming-Routers/TUF-Gaming-AX3000/

Thank you.

**Comment by gnuton** [comment]
Hi, please use the chat for sending me questions and let's keep this for issues.

**Comment by yk00365** [comment]
> Hi, please use the chat for sending me questions and let's keep this for issues.

Okay， thank you.
