### ISSUE TITLE
Telnet/SSH options hidden (DSL-AX5400)

### ISSUE THREAD

**Issue by seiken27** [gnuton/asuswrt-merlin.ng#168]
**Router Model Affected**
Models: DSL-AX5400 (Optus)

**Firmware Version Affected**
386.04

**Is this bug present in upstream Merlin releases too?**
Yes

**Describe the bug**
The DSL-AX5400 Optus Version has the telnet/ssh option removed from the administration/system page. 

**Screenshots**
default (currently on beta firmware)
![image](https://user-images.githubusercontent.com/77923907/158009887-18a97e10-d23b-4522-88fd-6e1b334c7efc.png)

exposed using a chrome plugin which allowed me to enable SSH and flash your merlin software on a locked version :D
![image](https://user-images.githubusercontent.com/77923907/158009949-88a9ca3b-06b0-4cf7-9038-0d518b31f308.png)

**Comment by DJE007** [comment]
you can get around this with Chrome Devtools open and passing this on the console

document.getElementById("telnetd_sshd_table").style.display = "";

document.getElementById('sshd_enable_tr').style.display = "";
document.getElementById('sshd_port_tr').style.display = "";
document.getElementById('sshd_password_tr').style.display = "";
document.getElementById('auth_keys_tr').style.display = "";
                
document.form.telnetd_enable[0].disabled = false;
document.form.telnetd_enable[1].disabled = false;
document.form.sshd_enable.disabled = false;

**Comment by seiken27** [comment]
yep i used a tool to have it revealed but thought it might be worthwhile to have it exposed for non technical people.

Also not sure if it's possible, but remove any reference to the specific optus model in the firmware as it might be hiding all the AiProtection /adaptive qos which were taken out for this ISP supplied model :(.

**Comment by gnuton** [comment]
ae671ed2ef should fix this and it will be part of the next beta

**Comment by seiken27** [comment]
awesome! great stuff mate!

**Comment by gnuton** [comment]
please feel free to re-open this if something is not right.

**Comment by seiken27** [comment]
yep been fixed in the latest update 👍
