### ISSUE TITLE
OpenVpn Username and Password

### ISSUE THREAD

**Issue by Master-A2** [gnuton/asuswrt-merlin.ng#170]
**Router Model Affected**
Models: (eg: DSL-AX82U/RT-AX82U/...)

**Firmware Version Affected**
386.04_0-gnuton2

HI Antonio,

like you said i made a thread in snbforums.
Here is the Link with the issue on the Firmware.

https://www.snbforums.com/threads/386-04_0-gnuton2-openvpn.77959/

**Comment by gnuton** [comment]
Tested on DSL-AX82U with the latest beta and the passwords are there.
If this was an issue on 386.04_0-gnuton2 this seems all right to me on the newer firmware.
For this reason I will close this issue.
Please feel free to re-open or keep on adding comment if you want. i will reply.
![image](https://user-images.githubusercontent.com/576580/160025475-5e4e4d8c-854e-45ff-bd40-0541c1e6cf8c.png)
