### ISSUE TITLE
Please do a version for DSL-AC88U

### ISSUE THREAD

**Issue by thedarkjester** [gnuton/asuswrt-merlin.ng#171]
**Is your feature request related to a problem? Please describe.**
I would like to use an old router/modem combo as just a router with Merlin/Gnuton

**Describe the solution you'd like**
Merlin features etc on the device

**Describe alternatives you've considered**
Purchasing a compatible one, but would like to use what I have.

**Additional context**
Not much else to add

**Comment by gnuton** [comment]
the DSL-AC88U doesn't run AsusWRT
