### ISSUE TITLE
xt8 second 5g wifi

### ISSUE THREAD

**Issue by evlo** [gnuton/asuswrt-merlin.ng#174]
Hi, 
thanks for porting asus wrt to this router.
I'm wondering if 5g-2 network is only available for backhaul or if it can be made available to the clients?
Or should it already be available and I'm doing something wrong?

**Comment by gnuton** [comment]
Please use the forum for support requests.
This thread is maybe what you are looking for:
https://www.snbforums.com/threads/asus-zenwifi-ax-xt8-5ghz-2-backhaul.72463/
