### ISSUE TITLE
Wireguard client

### ISSUE THREAD

**Issue by yadiejuned** [gnuton/asuswrt-merlin.ng#175]
**Is your feature request related to a problem? Please describe.**
None

**Describe the solution you'd like**
A wireguard client in the GUI

**Describe alternatives you've considered**
No alternatives, those are only for selected Asus routers I believed.

**Additional context**
None

**Comment by Roki100** [comment]
Seems to be already requested in #129

**Comment by yadiejuned** [comment]
Okay that's wonderful. Sorry for the double post. 

Looking forward!
