### ISSUE TITLE
Asus ZenWiFi XD6 Router.

### ISSUE THREAD

**Issue by tzgroute** [gnuton/asuswrt-merlin.ng#176]
Please support the Asus ZenWiFi XD6 Router.
Thank you very much !

https://www.asus.com/Networking-IoT-Servers/Whole-Home-Mesh-WiFi-System/ZenWiFi-WiFi-Systems/ASUS-ZenWiFi-XD6/

**Comment by gnuton** [comment]
Please list your router here  https://github.com/gnuton/asuswrt-merlin.ng/issues/140 if you wanna have more chance to get it supported.
Thanks a lot!
