### ISSUE TITLE
Bluetooth interference

### ISSUE THREAD

**Issue by spinett** [gnuton/asuswrt-merlin.ng#178]
**Router Model Affected**
RT-AX82U

**Firmware Version Affected**
386.5_2

**Describe the bug**
After installing the new firmware, there's a lot of interference with Bluetooth audio devices. On stock firmware I used to walk around the house (different rooms, two stories) with my BT headset/different sets of earbuds and there were certain places where I was losing connection but other than that, BT worked great. On modified firmware I can't really walk too far away from the source of playback, because it will disconnect/lose range. Besides installing Gnuton, I also connected a USB 3.0 HDD to the router, those are the only two changes. 

**Expected behavior**
Is there a setting that can be changed to lessen the router's interference into Bluetooth devices?

**Comment by gnuton** [comment]
Please file issues only when you are sure it's a bug. 
In order to understand if it's a bug or in order to get support please use the forum.
This thread may be what you are looking for
https://www.snbforums.com/threads/bluetooth-co-existence.38469/
