### ISSUE TITLE
GRE/IPIP Tunnel support

### ISSUE THREAD

**Issue by Roki100** [gnuton/asuswrt-merlin.ng#180]
**Is your feature request related to a problem? Please describe.**
The problem with making GRE/IPIP tunnels is that it sometimes requires effort to get it to work as it should

**Describe the solution you'd like**
A GRE/IPIP Tunnel support inside of a router itself, configurable via the web interface

**Describe alternatives you've considered**
Not using such tunnels (bad idea in my case)

**Additional context**
Im pretty sure its not currently possible to be done,
So basically when selfhosting a larger-scale server for some sort of a game or service, theres a high probability of getting hit by DDoS attacks causing it to get nullrouted, sadly thats what a shady competitors commonly do, and the "fix" for that is just tunneling via GRE/IPIP to a protected server to get more reliable service, currently it is kinda painful to configure it properly and requires terminal configuration in both host and remote server, with such feature it would only require a terminal configuration on the remote server, it would be great if it was just somehow implemented into port forwarding features, im not sure if asuswrt compiles kernel with GRE support or not, but if not maybe IPIP would work,
more context: https://wiki.buyvm.net/doku.php/gre_tunnel https://wiki.buyvm.net/doku.php/ipip_tunnel

Basically what i would expect from it is:
- My ip is lets say 256.178.23.17
- I start a new service at port 1337
- To protect it i make a gre tunnel
- Remote server IP which would route the tunnel is lets say 256.179.20.16
- The port 1337 of local host 192.168.1.192 gets routed via the tunnel (256.179.20.16) instead of 256.178.23.17, and users connect via it

**Comment by gnuton** [comment]
Hi,
honestly this is not a feature that a lot will requirea and I do see it more as simple script (bash?) or an amtm script (with or without web ui that you can install via https://diversion.ch/amtm.html )
The problem is that GRE require changes to kernel config to work and AFAIK that's not there and kernel configs are different from model to model and can break other closed source kernel components.
