### ISSUE TITLE
No telnet option on latest firmware (RT-AC66U)

### ISSUE THREAD

**Issue by Cliffback** [gnuton/asuswrt-merlin.ng#183]
**Router Model Affected**
Models: (eg: RT-AC66U/AC86U...)

**Firmware Version Affected**
384.5_2

**Is this bug present in upstream Merlin releases too?**
Yes

**Describe the bug**
No telnet option in the Administration/System panel on the RT-AC66U B1 using the latest firmware. I remember it was there earlier.

**Screenshots**
![2022-05-05 02-34-35](https://user-images.githubusercontent.com/51080320/166923974-bf425e91-ddc2-486a-a423-e18017bcf648.png)

**Comment by gnuton** [comment]
RT-AC66U/AC86 are not models that I maintain.
