### ISSUE TITLE
TUF-AX5400 wrong picture in Administration - Operation Mode

### ISSUE THREAD

**Issue by GaselK** [gnuton/asuswrt-merlin.ng#187]
**Router Model Affected**
Model: TUF-AX5400

**Firmware Version Affected**
[386.5_2-gnuton0]

**Is this bug present in upstream Merlin releases too?**
No

**Describe the bug**
Cosmetic display of TUF AX5400 is from ROG Rapture GT-AC2900

**To Reproduce**
Go to Administration - Operation Mode

![ac2900](https://user-images.githubusercontent.com/100087871/168464145-09d636b1-1296-4e35-ae73-771c1563f05f.jpg)

**Comment by gnuton** [comment]
good catch! :D I will maybe fix in the next GPL.. very low prio althogh

**Comment by gnuton** [comment]
this should be fixed in the next release.
The file involved is TUF-AX5400/ap.jpg

**Comment by GaselK** [comment]
Fixed on latest beta.

**Comment by gnuton** [comment]
Awesome!
