### ISSUE TITLE
Advanced_Wireless_Survey may disconnect clients from the wireless AP

### ISSUE THREAD

**Issue by gnuton** [gnuton/asuswrt-merlin.ng#19]
**Firmware Version Affected **
384.11-gnuton2

**Is this bug present in upstream Merlin releases too?**
?

**Describe the bug**
The wireless connection may be lost for a few minutes when the scanning goes on.
The router DOESN'T reboot in the meanwhile. The list of wireless networks in the end is shown correctly.

**To Reproduce**
1. Go to http://router.asus.com/Advanced_Wireless_Survey.asp
2. Run scan
3. you get disconnected from the wireless lan

**Expected behavior**
You do not get disconnected.

**Comment by gnuton** [comment]
I tried it once again and I have seen it just takes long time to scan. Eventually the list appears.

**Comment by zendilar** [comment]
I followed your instructions to reproduce the problem, and nothing happens, everything seams to work fine, no disconnections and the list appears almost immediately.

I checked three times and the outcome is the same.
running: DSL-AC68U_384.11_2-gnuton1_DSL_1.0.4.7.trx
