### ISSUE TITLE
Unable to save WAN configuration with DoT enabled

### ISSUE THREAD

**Issue by ChargedByte** [gnuton/asuswrt-merlin.ng#191]
**Router Model Affected**
Models: DSL-AX82U

**Firmware Version Affected**
386.5_2-gnuton0

**Is this bug present in upstream Merlin releases too?**
Not that I could find.

**Describe the bug**
WAN configuration cannot be saved if DNS-over-TLS (DoT) is enabled, also adding items to the DoT Server List does not work.

**To Reproduce**
Steps to reproduce the behaviour:
1. Go to WAN settings
2. Select DoT from the DNS Privacy Protocol list
3. Type details into the DoT Server List and click on the "plus" sign, nothing happens (no newline)
4. Scroll to the bottom and click "Ok", nothing happens

**Expected behaviour**
Expected to be able to enable DoT, add servers to list and save.

**Screenshots**
![firefox_HOaMOUAn9h_mod](https://user-images.githubusercontent.com/8603727/170204542-b63c80fc-91eb-4c31-9d06-012eb805e915.gif)

![firefox_7aUhAVvCu0](https://user-images.githubusercontent.com/8603727/170204615-0656a653-e1d9-48c1-8ef6-6556c70f3b99.png)

**Comment by gnuton** [comment]
Hi,
I have just tested this on my router and all works fine. Please reset to factory.
Here is the proof
![image](https://user-images.githubusercontent.com/576580/170442446-773022c8-9f41-4b40-9569-9fe4a1996ced.png)

**Comment by ChargedByte** [comment]
I did just factory reset the device and tried again but the issue remains.

**Comment by gnuton** [comment]
Interesting.. 
We are getting new GPLs. I will try to get it fixed in the next release. I will keep this ticket open

**Comment by gnuton** [comment]
This should be fixed now in the beta, does anybody confirm that?

**Comment by ChargedByte** [comment]
I can confirm. This is fixed in 386.07_0-gnuton0_beta1.

There was a malformed entry in the list (see image), but hitting remove on it worked, and it seems to have gone away for good. I also checked with Cloudflare's Connection Information (https://1.1.1.1/help) and everything was working as expected.

![firefox_O6mDw9ulGy](https://user-images.githubusercontent.com/8603727/176075332-02d9a71f-02b5-4b26-9546-fe3746a8fbe3.png)
