### ISSUE TITLE
Survey scan non functional.

### ISSUE THREAD

**Issue by ghost** [gnuton/asuswrt-merlin.ng#193]
**Router Model Affected**
Models: DSL-AX82U

**Firmware Version Affected**
386.5_2-gnuton0

**Is this bug present in upstream Merlin releases too?**
Unsure.

**Describe the bug**
Starting survey produces no results except your own SSID.

**To Reproduce**
Initiate /WiFi_Insight.asp - Survey and start the collection. 

**Expected behavior**
Other SSIDs that are within the area.

**Comment by gnuton** [comment]
go to http://router.asus.com/configure.asp and start collecting data. then you will see other SSIDs
