### ISSUE TITLE
Add support for GS-AX3000

### ISSUE THREAD

**Issue by Rovasteen** [gnuton/asuswrt-merlin.ng#195]
Hope it is OK to add a separate issue for adding support of the ROG STRIX GS-AX3000 which is the same FCC ID and hardware as the RT-AX58U and RT-AX3000 variants which Merlin supports. The GS-AX3000 could ideally be supported at the same time as the TUF-AX3000, which is yet another gaming variant of the same basic hardware using the Broadcom BCM6750 chipset. It appears the only difference between models is CFE.

Asus Web Page for GS-AX3000: https://rog.asus.com/us/networking/rog-strix-gs-ax3000-model/helpdesk_bios
Current GS-AX3000 firmware: https://dlcdnets.asus.com/pub/ASUS/wireless/GS-AX3000/FW_GS_AX3000_300438643588.zip

Version 3.0.0.4.386.43588
2021/08/17 51.82 MBytes
ASUS ROG STRIX GS-AX3000 Firmware version 3.0.0.4.386.43588

**Comment by gnuton** [comment]
Thanks for adding this but I would prefer to add the task by myself once I start to work on the router or I do have some plans for it.
There are a lot of routers which are similar, but they require time to be merged, testing and so on. 
So it's  hard to cover all of them, for this reason I try to pick the most popular ones first.
follow https://github.com/gnuton/asuswrt-merlin.ng/issues/140 for updates
