### ISSUE TITLE
check if VPN is working with ping

### ISSUE THREAD

**Issue by Sia7ash** [gnuton/asuswrt-merlin.ng#196]
Hi mate
I have 2 VPN connection that always runs with modem start , and sometimes one of my VPN is not working and i have to disable it and enable it again manually though it is still connect but doesn't open anything , is there any chance that you add some feature that test a vpn connection occasionally with ping and if the vpn is not working then switch to next vpn connection automatically ? something like the failover section in Dual WAN mode ?
thank you very much

**Comment by gnuton** [comment]
Hi,
try to reach the forum and there may be already some scripts for this. 
The only enanchments I add are usually model specific. Changes that are common to all models should come from upstream.
