### ISSUE TITLE
Control Channel in Wireless - General not showing the channel selected

### ISSUE THREAD

**Issue by kuki68ster** [gnuton/asuswrt-merlin.ng#198]
**Router Model Affected**
Models: RT-AX82U

**Firmware Version Affected**
386.07_0-gnuton0_alpha0

**Is this bug present in upstream Merlin releases too?**
Unable to say

**Describe the bug**
The control channel in wireless - General doesn´t show the channel selected

**To Reproduce**
1. Go to 'Wireless - General'
2. Click on 'Control Channel'
3. Select the "Auto" option and Apply

**Expected behavior**
When the "Auto" option is selected and applied, it shoud be visible as the option selected

**Screenshots**
If applicable, add screenshots to help explain your proble
<img width="746" alt="Captura de ecrã 2022-06-10 190023" src="https://user-images.githubusercontent.com/93822905/173124595-0d235e9b-fab6-46f5-aa81-22ea06f4ec66.png">
m or remove this section

**Comment by gnuton** [comment]
fixed in the next beta
![image](https://user-images.githubusercontent.com/576580/175803635-f8897b1e-06e1-445f-b3d4-8a56a6ac93d6.png)
