### ISSUE TITLE
No operation mode settings in DSL-AX82U firmware

### ISSUE THREAD

**Issue by Hansxsourse** [gnuton/asuswrt-merlin.ng#199]
**Router Model Affected**
Models: DSL-AX82U

**Firmware Version Affected**
386.5_2-gnuton0

**Is this bug present in upstream Merlin releases too?**
Not sure

**Describe the bug**
There is not the operation model settings in the page, where I cannot set the mode to AP.

**Screenshots**
![image](https://user-images.githubusercontent.com/40091878/173194169-37c6dc1c-b9ed-44a2-8af8-13e4cf110c3b.png)

**Comment by gnuton** [comment]
I canont reproduce it.
Operation modes are at this page and visible in Adrminstration page for me.

http://router.asus.com/Advanced_OperationMode_Content.asp

Please reset to factory your router and try again.
![image](https://user-images.githubusercontent.com/576580/175803370-d4ed08e8-98b5-4a5c-bc2f-e4419de72fbc.png)
