### ISSUE TITLE
GUI issues with new alpha code

### ISSUE THREAD

**Issue by SkrubbinBubb1es** [gnuton/asuswrt-merlin.ng#200]
**Router Model Affected**
Models: TUF5400

**Firmware Version Affected**
[386.07_0-gnuton0_alpha0]

**Is this bug present in upstream Merlin releases too?**
No

**Describe the bug**
under general wifi settings, 2.4Ghz section, the gui is messed up. the 5ghz section is fine though. does not affect anything as my settings from before the upgrade are still good. 

**Expected behavior**

**Screenshots**
![image](https://user-images.githubusercontent.com/107686734/174293543-4b57b8e8-663f-4146-b4c8-171e9cb2f219.png)

**Comment by GaselK** [comment]
+1 for my TUF AX5400. Same behavior.

**Comment by gnuton** [comment]
Thakns for reporting this. just tested the new beta and this has been fixed. Doing some verifications then it willbe available

**Comment by SkrubbinBubb1es** [comment]
Just loaded the new beta and I can confirm that this issue is resolved, thank you.
