### ISSUE TITLE
WAN - Internet Connection -  doesn´t show option : pvc edit and add/delete

### ISSUE THREAD

**Issue by ICIOMAGO** [gnuton/asuswrt-merlin.ng#201]
**Router Model Affected**
DSL-AX82U

**Firmware Version Affected**
386.5_2-gnuton0

**Is this bug present in upstream Merlin releases too?**
No

**Describe the bug**
Doesn´t show wan option : pvc edit and add/delete

**To Reproduce**
1. Go to 'wan'
2. Click on 'internet connection....'
3. See error

**Expected behavior**
Doesn't show wan option pvc edit and add/delete

**Screenshots**
![2022-06-18_10-37-34_169](https://user-images.githubusercontent.com/107748307/174429940-f1d9d5fd-18dd-412a-a28c-fb5cff2ba8f5.png)

**Comment by gnuton** [comment]
That's a stable version.
This issue should disappear if you reset to factory

**Comment by gnuton** [comment]
![image](https://user-images.githubusercontent.com/576580/176510883-cbfa7496-9039-42fa-8655-32adc98f40bf.png)
this seems to be fine also with the latest pre-release for me.
closing the ticket
