### ISSUE TITLE
dsl ac68u reporting out of nvram

### ISSUE THREAD

**Issue by CHazz** [gnuton/asuswrt-merlin.ng#203]
hi i try latest beta 386.07_0-gnuton0_beta1
after upgrade router no have free nvram .. after flash back is all ok again

**Comment by gnuton** [comment]
tested. the fix works. You can also see the nvram usage vs the total which is now correctly displayed
![image](https://user-images.githubusercontent.com/576580/176526106-21da07ca-107e-4481-847e-673c94f73e38.png)
