### ISSUE TITLE
Memory Leak

### ISSUE THREAD

**Issue by trebleta** [gnuton/asuswrt-merlin.ng#208]
**Router Model **
DSL Ax82u 

**Firmware Version Affected**
Lastest beta 2

**Is this bug present in upstream Merlin releases too?**
Dont know

**Describe the bug**
Installed the beta 2 noticed more memory was in use by 10ish Mb left it 3 hours noticed it was now 20-30 mb I was at 14* mb free normaly around 170mb

Is a screen shot of the last stable on snbforum beta thread.

**Comment by trebleta** [comment]
I will do more tests on the beta 2 tomorrow 6 july and will let you know.

**Comment by gnuton** [comment]
@trebleta can I close this now that we agreed the RAM usage is stable ?

**Comment by trebleta** [comment]
Sure
