### ISSUE TITLE
AC68U - WAN disconnected downloading torrent files

### ISSUE THREAD

**Issue by damocle81** [gnuton/asuswrt-merlin.ng#209]
**Router Model Affected**
DSL-AC68U

**Firmware Version Affected**
386.5_2-gnuton0

**Describe the bug**
The WAN connection is disconnected while downloading some torrent files with qBittorrent app.
The download speed is good, but after some minutes the WAN is disconnected, too many connections?
Please could you help me to solve this problem?

Thank you

**Comment by gnuton** [comment]
what happened is written in the logs

**Comment by damocle81** [comment]
Hello,

please could you check the attached log of the last disconnection?

![log](https://user-images.githubusercontent.com/95082090/178433023-9a9b9d11-7bd9-490b-a59a-257467012929.png)


Thank you

**Comment by gnuton** [comment]
@damocle81 it seems like your ISP disconnects your modem

**Comment by damocle81** [comment]
Thank you, I will try otherwise I will request support from my ISP.
