### ISSUE TITLE
Is it possible to implement "tunnet 4rd" in IPv6 settings ?

### ISSUE THREAD

**Issue by fabouygue** [gnuton/asuswrt-merlin.ng#21]
Almost all the ISP in France are changing to IPV6 via "tunnel 4rd" but there's only "tunnel 6rd" in DSL-AC68U" settings...
THX

**Comment by gnuton** [comment]
Hi,
At moment there is no plan to add this feature, but if this it is coming from upstream codes (Asus or Merlin) then it will be part of my firmware too.
If you wanna have this feature right  now you can write a script for it.
