### ISSUE TITLE
New project: DSL-AC88U?

### ISSUE THREAD

**Issue by fisher54** [gnuton/asuswrt-merlin.ng#210]
**Is your feature request related to a problem? Please describe.**
I'm one of those unlucky to have a DSL-AC88U. Great router, but hardware too unique I guess for anyone to tackle. Main issue for me is I just want OpenVPN 2.4.x or higher in the firmware. Router won't talk to a lot of VPN servers out there.

**Describe the solution you'd like**
Beta for DSL-AC88U?

**Describe alternatives you've considered**
Merlin will not attempt
ASUS, well, maybe 1,000 users would have to stand on their heads to get noticed? Their latest fw update was 2021 so maybe they would consider.

**Additional context**

Thank you!

**Comment by gnuton** [comment]
Merlin cannot run on DSL-AC88U.
