### ISSUE TITLE
TUF AX5400 icons missing

### ISSUE THREAD

**Issue by GaselK** [gnuton/asuswrt-merlin.ng#212]
**Router Model Affected**
Models: TUF AX 5400

**Firmware Version Affected**
TUF-AX5400_386.07_0-gnuton0_beta2_cferom_puresqubi

**Describe the bug**
Icons missing from WiFi Radar

**To Reproduce**
1. Go to Wireless
2. Click on WiFi Radar

**Screenshots**
![t54](https://user-images.githubusercontent.com/100087871/178114800-29f9f08a-6420-4dda-bbf1-59f3d65e2264.jpg)

**Comment by gnuton** [comment]
thanks I fixed this the other night! 
![image](https://user-images.githubusercontent.com/576580/178123803-82a83a2e-0dcf-4423-b2fd-d2fd571f8401.png)

**Comment by d3v3l15h** [comment]
Hi,

First, thanks for these firmwares.

Just want to say I have this very same issue on XT8 with build 386.07_2-gnuton1. Not sure if the fix has been deployed though.

EM

**Comment by gnuton** [comment]
@d3v3l15h I am preparing the 388 builds I will keep an aye on the new ones. 
In theory this should not be the case for XT8, usually missing icons issues are found only in the first images I release for a model.

**Comment by d3v3l15h** [comment]
OK Thanks.

![image](https://user-images.githubusercontent.com/10949893/201674989-65335b01-86f5-4384-bc48-8e1bb7aebdf4.png)

EM
