### ISSUE TITLE
RT-AX82U - Disable 11b doesn't work

### ISSUE THREAD

**Issue by gnuton** [gnuton/asuswrt-merlin.ng#213]
**Router Model Affected**
Models:RT-AX82U

**Firmware Version Affected**
386.07

Found another small issue, Under, Wireless, General tab, 2.4GHz, if selecting 'Disable 11b' , after hitting the apply button, you are unable to deselect it again.

![image](https://user-images.githubusercontent.com/576580/179213550-4f2329b8-24db-44fd-a415-81de0b9debcf.png)

**Comment by gnuton** [comment]
see b757e2ebe4e84e6cc4127875a3197271cc462c47

**Comment by gnuton** [comment]
canont reproduce it. 
and the fix is already applied

**Comment by neil1962** [comment]
Can confirm fixed in beta 3 for RT-AX82U
