### ISSUE TITLE
RT-AX82U. Question mark shown in the page

### ISSUE THREAD

**Issue by gnuton** [gnuton/asuswrt-merlin.ng#214]
**Router Model Affected**
Models: RT-Ax82u
![image](https://user-images.githubusercontent.com/576580/179215366-4ed62c48-e503-4b57-98d0-343eaa09b2a6.png)

**Comment by gnuton** [comment]
the offending code is this
 if(nt_center_support)
                banner_code +='<td width="30" id="notification_status_td"><div><div id="noti_event_count" style="display:none"><div id="noti_event_num"></div></div><div id="notification_status"></div></div><div id="notification_desc"></div></td>\n';
        else
                banner_code +='<td width="30" id="notification_status1" class="notificationOn"><div id="notification_status" class="notificationOn"></div><div id="notification_desc" class=""></div></td>\n';

nt_center_support is 0 so the second banner_code is appened.

 var nt_center_support = (isSupport("nt_center") && isSupport("nt_center_ui"))

**Comment by gnuton** [comment]
![image](https://user-images.githubusercontent.com/576580/179324045-0579ffed-6028-4ba5-8a94-968b9e9695ee.png)
BRoken

**Comment by gnuton** [comment]
![image](https://user-images.githubusercontent.com/576580/179324076-3f37c6f9-2f77-4909-b903-05b00640da5f.png)
the working one on DSL-AX82U

**Comment by gnuton** [comment]
fixed 
![image](https://user-images.githubusercontent.com/576580/179346813-57457057-487d-4691-a3cf-36de41921fd3.png)

**Comment by neil1962** [comment]
Tahnks will try on your next firmware release.

**Comment by gnuton** [comment]
this fixed is part of beta4

**Comment by neil1962** [comment]
I can confirm problem is fixed,  thank you

**Comment by neil1962** [comment]
Thanks

Sent From My Mobile Device
________________________________
