### ISSUE TITLE
TUF AX5400 gui font mismatch

### ISSUE THREAD

**Issue by GaselK** [gnuton/asuswrt-merlin.ng#215]
**Router Model Affected**
Models: TUF AX5400

**Firmware Version Affected**
386.07_0-gnuton0_beta3

**Describe the bug**
In WAN screen font is mismatch from main font used and a strange icon appears over qos settings icon

**To Reproduce**
1. Go to WAN

**Screenshots**
If applicable, add screenshots to help explain your problem or remove this section
![r1](https://user-images.githubusercontent.com/100087871/179236433-a753cfd4-ab29-4a5c-ac75-1cfb5f823bf6.jpg)

**Comment by gnuton** [comment]
this glitch as this https://github.com/gnuton/asuswrt-merlin.ng/issues/214

**Comment by GaselK** [comment]
Fixed in 386.07_2-gnuton0_beta4
