### ISSUE TITLE
shadowsocks

### ISSUE THREAD

**Issue by LeonGinger** [gnuton/asuswrt-merlin.ng#22]
我想在这个上面安装shadowsocks 或者v2ray不知道可不可以  因为在rt-ac68u上我能找到相关可以安装这些脚本的第三方merlin固件，但是在dsl-ac68u上却找不到相关的固件 

/*
I want to install shadowsocks or v2ray on it. I don't know if it's OK because I can find the third-party Merlin firmware that can install these scripts on rt-ac68u, but I can't find it on dsl-ac68u.

*/

**Comment by gnuton** [comment]
Hi, 
Theoretically scripts for rt-ac68u should work on dsl version too.
