### ISSUE TITLE
RT-AC85U Support

### ISSUE THREAD

**Issue by 5n1perwo1f** [gnuton/asuswrt-merlin.ng#229]
Hello, I was just checking to see if there is any support for this device, or if support will be added for it? I was told that another version of Merlin designed for a different device may work, but I just wanted to verify first. Thanks!

**Comment by gnuton** [comment]
Hi,
No plans to support this device.
Asus latest stock firmware is from beginning of last year so it won't run
the latest Merlin firmware either.
