### ISSUE TITLE
Change snr upload

### ISSUE THREAD

**Issue by MarcoCITA** [gnuton/asuswrt-merlin.ng#23]
Can you add a setting to be able to change the snr  upload like the download one?

**Comment by gnuton** [comment]
what the web ui does is setting some values in the NVRAM. Those values are read from the some ASUS proprietary code.
The variables we are talking about here are dslx_vdsl_target_snrm (for the download). There is no similar variable for upload. So if you wanna have this feature I am afraid you should ask ASUS.
