### ISSUE TITLE
Support of DSL-AC88U

### ISSUE THREAD

**Issue by gereblye79** [gnuton/asuswrt-merlin.ng#233]
**Is your feature request related to a problem? Please describe.**
The router resets itself in random time. Sometime the router does not start, sometime it takes several hours to start. 

**Describe the solution you'd like**
Could you support the DSL-AC88U router also?

**Describe alternatives you've considered**
???

**Additional context**
-

**Comment by gnuton** [comment]
no it cannot technically be supported by Merlin
