### ISSUE TITLE
DSL-AX82U Freeze completely after firmware upgrade

### ISSUE THREAD

**Issue by dimvas243** [gnuton/asuswrt-merlin.ng#244]
**Router Model Affected**
Models: DSL-AX82U

**Firmware Version Affected**
386.07_2-gnuton1 - 386.08_0-gnuton0_beta1

**Is this bug present in upstream Merlin releases too?**
No

**Describe the bug**
In both firmware the router freezes complete after some time no internet, no wifi, no lan with out changing any settings from firmware 386.5_2-gnuton0 help me please to debug it i don't know how to get the logs after freeze so i can help you further.

thank you in advance

**Comment by gnuton** [comment]
have you reset the router to factory?

**Comment by dimvas243** [comment]
thanks for the response i didn't try it  one small question, can i do factory reset and restore setting from backup or i must restore them manually

Thank you in advance

**Comment by trebleta** [comment]
Do a hard reset, by turning off the router holding the wps button switching on then wait till the led changes the switch of and on again.
Yes manualy do all setting, to rule that out

**Comment by gnuton** [comment]
@dimvas243 @trebleta is right do not use backups. Merlin is similar but not the same as stock firmware.

**Comment by dimvas243** [comment]
i have hard reseted, manual reconfigure evrething stil freezes red light on dsl, no  ssh connection with the message  "kex_exchange_identification: read: Connection reset", the page will not open. The freeze happend after 1 - 2 hours i have install flex qos

**Comment by trebleta** [comment]
And if flex QOS is not installed?

**Comment by dimvas243** [comment]
without flexqos running 24+ hours straight without any problem

**Comment by dimvas243** [comment]
i have tested with the developement repo and no freeze for 24 hours i am closing it
