### ISSUE TITLE
Web pages in AiProtection section not displaying properly - DSL-AC68U

### ISSUE THREAD

**Issue by Randi1115** [gnuton/asuswrt-merlin.ng#249]
Hi Gnuton,

The GUI in the AiProtection section in DSL-AC68U doesn't display properly most of the time. If I reload it several times it works once or twice. This is a hit and miss. Clearing browser cache and resetting the router settings have had no effect on this. If I navigate away from the AiProtection section the GUI works properly. The issue seems to happen particularly on the AiProtection section. Navigating to tabs in the section sometimes work and sometimes don't. Can this be looked at please? Please see the attached screenshot. Thank you.

![AI-ProtectionPage](https://user-images.githubusercontent.com/98433740/189544354-5b335898-afdb-4d86-b315-d6fe36e3f8eb.png)

**Comment by gnuton** [comment]
Hi,
This seems to be a caching issue of your browser. Clean the cache or better open the page using chrome/firefox in incognito mode. Let me know if this works

**Comment by gnuton** [comment]
closing this since it's defintley a browser issue.
