### ISSUE TITLE
asus tuf ax5400 ipv6 passthrough

### ISSUE THREAD

**Issue by ThrnSC87** [gnuton/asuswrt-merlin.ng#253]
**Router Model Affected**
Models: Tuf AX5400

**Firmware Version Affected**
386.07_2

**Is this bug present in upstream Merlin releases too?**
No idea.

**Describe the bug**
When enabling ipv6 passthrough sys log gets spammed with this
kernel: protocol 0000 is buggy, dev archer

**To Reproduce**
1. Enable ipv6 passthrough
2. Check sys log

**Comment by gnuton** [comment]
Duplicate of https://github.com/gnuton/asuswrt-merlin.ng/issues/226
