### ISSUE TITLE
Does the fw upgrade really available for this router?

### ISSUE THREAD

**Issue by F640** [gnuton/asuswrt-merlin.ng#255]
**Router Model Affected**
Models: RT-AX82U

**Firmware Version Affected**
386.07_2-gnuton1

**Is this bug present in upstream Merlin releases too?**
No

**Describe the bug**
My router says it has update and changelog said "only available for DSL-AX82U and RT-AX92U"

**To Reproduce**
1. Go to Administration
2. Click on Firmware Update
3. Check for update
4. Click on latest version (386.08-gnuton1)
5. It said something like in description

**Expected behavior**
No firmware upgrade for now like what changelog says

**Screenshots**
![IMG_20221009_182351](https://user-images.githubusercontent.com/92260436/194754451-d0e943a5-182c-4664-a557-602f7c5c5960.jpg)

**Comment by Camology** [comment]
Came to post the exact same thing.

**Comment by gnuton** [comment]
Hi,
thanks for reporting.
You should not see anymore this notification.
