### ISSUE TITLE
Beta Firmware for AT8 isn't .trx

### ISSUE THREAD

**Issue by toddgonzo74** [gnuton/asuswrt-merlin.ng#257]
Current firmware on beta page is .w file extension. Should it be .trx?

**Router Model Affected**
Models: RT-AX95Q

**Firmware Version Affected**
384.xx

**Describe the bug**
Current firmware on beta page is .w file extension. Should it be .trx?

**Comment by gnuton** [comment]
no TRX are for AC routers, this is an AX.

**Comment by gnuton** [comment]
no problem. :D
