### ISSUE TITLE
Asus AX5400

### ISSUE THREAD

**Issue by ThrnSC87** [gnuton/asuswrt-merlin.ng#258]
**Is your feature request related to a problem? Please describe.**
Can we get a update with GPL 386_50224 for AX5400 in future as it fixes some system stability issues with lan ports turning off and on randomly ?

**Comment by Rovasteen** [comment]
There is now a 388 based build for the TUF-AX5400.  So hopefully that will be next!

**Comment by gnuton** [comment]
I will close this since we do have 388 for all AX devices
