### ISSUE TITLE
AiMesh BIND not working

### ISSUE THREAD

**Issue by toddgonzo74** [gnuton/asuswrt-merlin.ng#260]
**Router Model Affected**
Models: AT8

**Firmware Version Affected**
**386.05_0-gnuton0_beta1**

**Is this bug present in upstream Merlin releases too?**
No

**Describe the bug**
In the AiMesh screen, I want to bind a client to a specific node.  In the stock firmware, you click bind and the bind button stays lit.  In this beta, when you try to bind, it says successful, prints the message, and then the binding isn't in effect once you click OK.  Binding doesn't appear to work. 

**To Reproduce**
1. Go to AiMesh
2. Click on Any client bind button (chain b utton to the right of the client MAC and IP).
3. Click bind and then click OK.  Wait a few seconds and you get a success message.
4. Click OK
5. note that client is not bound.

**Comment by gnuton** [comment]
HI,
have you tried to reset to factory and try again? It should work (not tested no XT8, but on DSL-AX82U and it works)

**Comment by gnuton** [comment]
reconfig from scratch. please do not use config files.

**Comment by toddgonzo74** [comment]
That appears to have fixed it.  Gratzie.

**Comment by gnuton** [comment]
I knew that! :D Awsesome!
