### ISSUE TITLE
388.1 builds

### ISSUE THREAD

**Issue by Rovasteen** [gnuton/asuswrt-merlin.ng#266]
Merlin has released his 388.1 builds as alpha.  Asus has also released its own 3.0.0.4.388.21224 builds as generally available.  What is the timing of the Gnuton 388 based builds?

Thank you!!!

**Comment by gnuton** [comment]
Hi,
388 will be only available for selected models. Models not supported by 388 will in any case receive an updated 386 version.
Your router will get 388 if ASUS has already release a 388 for it.
 
I have not received the GPLs yet, and not even Eric got all of them.

My expectation is to see something coming late november, defintely before the end of the year.

off-topic: Please do not open tickets for questions if possible. use the forum or the the chat instead.  Thanks a lot.
