### ISSUE TITLE
388 series Firmware for ASUS TUF 5400 (incl. Wireguard)

### ISSUE THREAD

**Issue by swiffer** [gnuton/asuswrt-merlin.ng#269]
Asus published Firmware Version  3.0.0.4.388.21224 on 21st october incl. Wireguard and more.

Is an Update planned?

https://dlcdnets.asus.com/pub/ASUS/wireless/TUF-AX5400/FW_TUF_AX5400_COMBO_300438821224.zip.zip

**Comment by gnuton** [comment]
Yes. All ax routers will receive 388 Merlin in the coming weeks. I am working on it.you will soon know more.

**Comment by gnuton** [comment]
closing this since 388 alpha are already out
