### ISSUE TITLE
can't save port forwarding settings

### ISSUE THREAD

**Issue by myyc** [gnuton/asuswrt-merlin.ng#27]
**Firmware Version Affected**
384.12

**Is this bug present in upstream Merlin releases too?**
Not sure.

**Describe the bug**
I tried to set up port forwarding. adding a record doesn't save it, it seems like it lacks a save button.

**To Reproduce**
1. Add a port forwarding rule
2. Refresh the page

**Comment by gnuton** [comment]
Hi,
To solve this issue please reset to factory, then try again.
We tested the firmware and this was not an issue. For this reason I will close this issue. Feel free to join the below thread for further support. Thanks.
https://www.snbforums.com/threads/dsl-ac68u-asuswrt-merlin-builds-for-dsl-routers.55985/page-21
