### ISSUE TITLE
SNMP support for RT-AX92U

### ISSUE THREAD

**Issue by vdbseb1983** [gnuton/asuswrt-merlin.ng#271]
Hello, juste a suggestion, it'll be great to enable SNMP inside RT_AX92, so geeks/nerds like us can monitor the status of the equipment on their servers.

Thanks!

Regards!

vdbseb1983

**Comment by Dima-Kal** [comment]
I use a usb flash drive with node_exporter, works great
https://www.jeffgeerling.com/blog/2022/monitoring-my-asus-rt-ax86u-router-prometheus-and-grafana

**Comment by gnuton** [comment]
@vdbseb1983 I will enable SNMPD within the next 388 alpha

**Comment by gnuton** [comment]
This has been enabled and I will close this request
