### ISSUE TITLE
RT-AX58U ASUSWrt Merlin Firmware Hakkında

### ISSUE THREAD

**Issue by Biyan21** [gnuton/asuswrt-merlin.ng#272]
Merhaba,

RT-AX58U Ruter cihazıma ASUSWrt Merlin Firmware yüklemek istiyorum. Ruter arayüzünde Cake menüsüne ulaşmak istiyorum Ancak bir türlü yapamıyorum. Bana www uzantılı dosyayı gönderebilirmisiniz. Bende ruter cihazıma yükleme yapayım. Teşekürler.

**Comment by gnuton** [comment]
I do not get a single word of what's written here. English please

**Comment by Biyan21** [comment]
First of all, I apologize for not knowing English, so I wrote in Turkish.  I have a DSL-AX82U model device.  Modem, I want to install merlin on it.  So as with the RT-AX82U.

**Comment by Biyan21** [comment]
I want to install ASUSWrt Merlin Firmware on my DSL-AX58U Modem Ruter.  I want to reach the Cake view in the modem interface, but I can't do it.  I wonder if there is no Merlin firmware for the modem?  Thanks.

**Comment by gnuton** [comment]
Cake is only available on RT/DSL-AX devices and not on RT/DSL-AC ones, so no cake for DSL-AC68U.

**Comment by Biyan21** [comment]
Thanks for the answer, I have the DSL-AX82U.

15 Kas 2022 Sal 12:19 tarihinde Antonio Aloisio ***@***.***>
şunu yazdı:

**Comment by gnuton** [comment]
DSL-AX82U supports cake and you can find hte firmware in the download page
