### ISSUE TITLE
Upload / Download speeds into Adaptive QoS page are swapped

### ISSUE THREAD

**Issue by WillyTP** [gnuton/asuswrt-merlin.ng#273]
**Router Model Affected**
Models: (DSL-AX82U, maybe others)

UPDATED 27-Nov-2022

**Firmware Version Affected**
386.08, 388.1_0-gnuton0_alpha1

**Is this bug present in upstream Merlin releases too?**
Don't know

**Describe the bug**
Into Adaptive QOS, Bandwidth monitor page, Upload / Download speeds are swapped.

**To Reproduce**
1. Enable Traffic Analyzer (Traffic Analyzer -> Statistics -> Turn ON)
2. Put something to download as test...
3. Go to Adaptive QoS page
4. Look at Speedometers. Upload and Download are swapped.

**Expected behavior**
They shouldn't be swapped...

**Screenshots**
<img width="748" alt="Schermata 2022-11-03 alle 17 37 47" src="https://user-images.githubusercontent.com/15254201/199781977-4165e40a-4285-4a23-8753-760de5a74e5d.png">

**Comment by WillyTP** [comment]
Hi,
Looks like Traffic Analyzer is the cause.
By disabling it, upload and download speeds are NOT swapped anymore.

**Comment by WillyTP** [comment]
First post updated.
BTW, I tried too to do another test. Going to Traffic Analyzer -> Statistics page caused Web UI to crash (GUI interface not available for some minutes...)
Rebooting the router solved WebUI issue.
I confirm again Traffic Analyzer <-> swapped speeds, I've been able to replicate them.

**Comment by gnuton** [comment]
@WillyTP are you able to reproduce it? crashes btw is different issue.
If you are able to reproduce it all time please create a new ticket so that we can properly track it.

**Comment by WillyTP** [comment]
Looks like issue has been solved in 388 Beta1.
