### ISSUE TITLE
dualwan load balance frequent disconnects, intermittent

### ISSUE THREAD

**Issue by jsnepo** [gnuton/asuswrt-merlin.ng#278]
TUF AX3000 v1

**Firmware Version Affected**
386_49780

**Is this bug present in upstream Merlin releases too?**
N/A

**Describe the bug**
enabling load balance causes intermittent connection, high jitter, massive lag

primary WAN = DHCP
secondary WAN = PPPoE
1:1, 2:3

**To Reproduce**
1. Go to 'dual wan'
2. Click on dual wan mode
3. Select load balanace

**Expected behavior**
low jitter, no intermittency, low lag

**Comment by gnuton** [comment]
Massive high chance this is due to your network.386_49780
386_49780 is Asus firmware so please contact them
