### ISSUE TITLE
AiMesh setup fails for DSL-AC68U + DSL-AC68U

### ISSUE THREAD

**Issue by philbo** [gnuton/asuswrt-merlin.ng#279]
**Router Model Affected**
DSL-AC68U for both router and node

**Firmware Version Affected**
386.07_2-gnuton1 on both

**Is this bug present in upstream Merlin releases too?**
Don't know

**Describe the bug**
The node is found via the search on the router, but adding the node always fails.

**To Reproduce**
1. Go to AiMesh click Add Node
2. Click Search
3. Node device is found
4. Click add, progress bar goes to 100% then error dialog is show

**Expected behavior**
Node to be added

**Screenshots**
![Screenshot from 2022-11-08 14-13-33](https://user-images.githubusercontent.com/107669/200588844-9eb7eae6-f57d-4c36-ab03-bb12bd4dc437.png)
![Screenshot from 2022-11-08 14-14-03](https://user-images.githubusercontent.com/107669/200588849-a36dcf3d-0f11-4f67-9d26-74606afc5dfe.png)

General Log
```
Nov  8 14:07:13 rc_service: cfg_server 18749:notify_rc restart_obd_monitor
Nov  8 14:09:21 rc_service: cfg_server 19652:notify_rc restart_obd_monitor
Nov  8 14:10:31 syslog: wlceventd_proc_event(508): eth2: Disassoc <MAC>, status: 0, reason: Disassociated because sending station is leaving (or has left) BSS (8), rssi:-77
Nov  8 14:13:05 rc_service: cfg_server 20616:notify_rc restart_obd_monitor
Nov  8 14:13:37 rc_service: cfg_server 20877:notify_rc start_wps_method_ob
Nov  8 14:13:43 rc_service: cfg_server 20878:notify_rc stop_wps_method_ob
Nov  8 14:14:00 syslog: wlceventd_proc_event(527): eth2: Auth <MAC>, status: Successful (0), rssi:0
Nov  8 14:14:00 syslog: wlceventd_proc_event(556): eth2: Assoc <MAC>, status: Successful (0), rssi:0
Nov  8 14:14:01 dnsmasq-dhcp[5633]: DHCPREQUEST(br0) 192.168.1.244 <MAC> 
Nov  8 14:14:01 dnsmasq-dhcp[5633]: DHCPACK(br0) 192.168.1.244 <MAC> M-C02ZV132LVDF
Nov  8 14:14:16 kernel: nvram: consolidating space!
Nov  8 14:15:14 rc_service: cfg_server 21132:notify_rc restart_obd_monitor
Nov  8 14:15:27 rc_service: cfg_server 21297:notify_rc start_wps_method_ob
Nov  8 14:15:32 rc_service: cfg_server 21298:notify_rc stop_wps_method_ob
```

**Comment by gnuton** [comment]
please use ethernet backhaul for the first association.

**Comment by philbo** [comment]
I didn't think that was supported for the DSL versions due to the lack of WAN port?

**Comment by philbo** [comment]
For future reference I managed to get it paired wirelessly using the official Asus firmware on router and node, then upgrade the router to Merlin afterwards

**Comment by gnuton** [comment]
yes you can do that too, but if you do not reset to factory when you flash marlin, something else could be broken
:D rule of thumb: always reset to factory after flashing
