### ISSUE TITLE
New Feature - https Filter with time slots

### ISSUE THREAD

**Issue by Matt-One** [gnuton/asuswrt-merlin.ng#28]
Ciao, mi chiedevo se fosse possibile aggiungere una feature per bloccare l'accesso a determinati siti in determinate fasce d'orario e non solo bloccare tutti i siti di intrattenimento, non adatto ai minori ecc. come si fa in AiProtection - Filtri Web & App
In pratica vorrei poter bloccare per esempio solo youtube (o tutti i siti streaming & intrattenimento se non si possono bloccare singolarmente) a mia nipote in determinate fasce d'orario e non h24.

Grazie e Buon anno :)

------------------------------------------------------------------------------------------------------------

Hi, I was wondering if it was possible to add a feature to block access to some sites of my interest  in certain time slots and not just block h24 to all entertainment sites, porn sites etc. like in AiProtection - Web & App Filters
In practice I would like to block for example only YouTube (or all streaming and entertainment sites if you cannot block them individually) to my niece in certain time slots and not 24 hours a day.

Thank you and happy new year :)

**Comment by gnuton** [comment]
Ciao,
Non vorrei aggiungere nessuna nuova feature addizionale a quella offerta dal software upstream (asus erlin e asus wrt). Motivo di questa scelta e' la piu facile gestione degli aggiornamenti da parte mia e maggiore qualita nel software rilasciato.
Se sei interessato a quest a feature sicuramente puoi aggiungerla al tuo router personale tramite script. Chiedi sul forum sul come fare. Non avrai un interfaccia web, ma cmq ci riesci sicuramente.
Ciao e buon anno a te.
