### ISSUE TITLE
New Release Gnuton Build AX82U

### ISSUE THREAD

**Issue by asterictnl-lvdw** [gnuton/asuswrt-merlin.ng#280]
**Is your feature request related to a problem? Please describe. **
Is there any view on when the new AX82U Build is going to be released? I had to fall back on the normal build because of problems with the latest Gnuton AX82U build (non-DSL)

**Describe the solution you'd like**
A new build with the latest updates and fixes implemented

**Describe alternatives you've considered**
Using the stable ASUS Build for now to avoid any issues

**Comment by gnuton** [comment]
Hi,
I am already testing 388 builds. The alpha for most of the models will be available soon.
BTW please use the chat for questions or the forum.
Thanks a lot!
