### ISSUE TITLE
Wireguard Server and Client on XT8

### ISSUE THREAD

**Issue by luisyamashiro** [gnuton/asuswrt-merlin.ng#282]
Hi, it is possible to add wireguard protocol to the vpn server and client gui?

It would be really great to have that, and also the possibility to make one of the clients as an default connection, so if there is a new hardware that uses the wifi, it's automatically routed to that vpn client. 

Thanks!

**Comment by gnuton** [comment]
Wireguard is already available on the current stable and the GUI should be available in the next 388 images
