### ISSUE TITLE
388.1_0-gnuton0_alpha1 Feedback (TUF-AX5400)

### ISSUE THREAD

**Issue by swiffer** [gnuton/asuswrt-merlin.ng#285]
Thanks releasing first alpha based on 388 series! I see several menus missing in the VPN section.

What is the difference between the two files / which one should be used?

- TUF-AX5400_388.1_0-gnuton0_alpha1_cferom_puresqubi.w
- TUF-AX5400_388.1_0-gnuton0_alpha1_puresqubi.w

**Router Model Affected**
TUF-AX5400

**Firmware Version Affected**
388.1_0-gnuton0_alpha1

**Is this bug present in upstream Merlin releases too?**
No

**Describe the bug**
VPN: menus (e.g. when on /Advanced_VPN_OpenVPN.asp) and/or menu entries (VPN Director) are missing

**Screenshots**
![grafik](https://user-images.githubusercontent.com/2990373/202980561-76361e99-f871-44e8-9de0-ab3026093664.png)
![grafik](https://user-images.githubusercontent.com/2990373/202980605-74b0eb5f-e707-472c-9f4e-8bdad3444c22.png)
![grafik](https://user-images.githubusercontent.com/2990373/202980738-41a80eba-8aea-42d3-8a1f-8dd3b46d3eb5.png)
![grafik](https://user-images.githubusercontent.com/2990373/202980812-80a09c82-8522-480d-a241-e4db3701e3ea.png)
![grafik](https://user-images.githubusercontent.com/2990373/202980933-1e02ddb9-5a8a-46d5-8617-7416c849b6c5.png)

**Comment by gnuton** [comment]
Thanks for reporting,
TUF-AX5400_388.1_0-gnuton0_alpha1_cferom_puresqubi.w <--- with  CFE (pronuced cafe', it's the Broadcom bootloader)
TUF-AX5400_388.1_0-gnuton0_alpha1_puresqubi.w <--  this doesn't update the bootloader

I would most probably get rid of TUF ui in 388 and I am not sure if I would make TUF UI enabled images too.
This first alphas do still has TUF UI.
I will try to collect feedback for it and take a decision...

**Comment by swiffer** [comment]
For me would be fine to use the default ui. Rmerl seems to offer rog Variants in addition now.

Ok, thanks - is one or the other recommended? Do you know what happens when using the default Firmware? (Incl. Or excl. The cferom)?

**Comment by DervilRus** [comment]
I also do not know which option is better in which case

**Comment by micron888** [comment]
TUF-AX5400_388.1_0-gnuton0_beta1_tuf_puresqubi.w - dnsfilter and VPN director broken 
TUF-AX5400_388.1_0-gnuton0_beta1_puresqubi.w - dnsfilter replace with dns director. VPN tab is available.

**Comment by gnuton** [comment]
@micron888 so TUF is broken and the standard gui looks fine, correct?

**Comment by micron888** [comment]
Standard gui look ok, other than some cosmetic issue indicated on #292

**Comment by Rovasteen** [comment]
For CFE vs non-CFE, there is always risk when you flash the CFE bootloader.  It would be nice to know if the CFE is actually being updated in those builds because flashing the same CFE again adds risk with no benefit.  If the CFE Is actually being updated, it would be nice to get some notes which state what is in the CFE update.

**Comment by gnuton** [comment]
close as it's an old issue not present in the latest releases
