### ISSUE TITLE
The WPS tab is missing.

### ISSUE THREAD

**Issue by hammerjoe** [gnuton/asuswrt-merlin.ng#288]
**Router Model Affected** RT-AX82U
Models: (eg: DSL-AX82U/RT-AX82U/...)

**Firmware Version Affected**
[388.1_0-gnuton0_alpha1](https://github.com/gnuton/asuswrt-merlin.ng/releases/tag/388.1_0-gnuton0_alpha1)

**Is this bug present in upstream Merlin releases too?**
No

**Describe the bug**
The WPS tab is missing from the WAN options.

**To Reproduce**

**Expected behavior**

**Screenshots**
If applicable, add screenshots to help explain your problem or remove this section

**Comment by gnuton** [comment]
Hi,
The WPS tab is in Wireless 
http://router.asus.com/Advanced_WWPS_Content.asp
and that's the right place for it.

**Comment by gnuton** [comment]
![image](https://user-images.githubusercontent.com/576580/203489836-7aa4ee9b-498b-446d-8f38-d8e2e240229d.png)

**Comment by hammerjoe** [comment]
Thanks. 
I was pretty sure I checked all the tabs but somehow missed it...
