### ISSUE TITLE
DSL-AX82U DSL modem doesn't work if SNR values are modified

### ISSUE THREAD

**Issue by gnuton** [gnuton/asuswrt-merlin.ng#290]
**Router Model Affected**
DSL-AX82U

**Firmware Version Affected**
388.01 gnuton firmware

**Is this bug present in upstream Merlin releases too?**
no
**Describe the bug**
The DSL Modem doesn't work if the SNR values are enabled.

The problem: the DSL-AX82U comes with two DSL modem drivers. The new one doesn't support manual SNR adjustment anymore because the vendor sees this as an obsolete feature.
On 388.1, If the user enables SNR, the kernel module gets loaded again with an old modem driver.
This mechanism doesn't seem to correctly work on my builds.
Investigation is ongoing.

** Temporary fix **
In case SNR is enabled and before flashing 388.1 please check that "Stability Adjustment" is disabled in https://router.asus.com/Advanced_ADSL_Content.asp
![image](https://user-images.githubusercontent.com/576580/209070800-07d5d297-c12b-427b-a2f8-d14a6c6bd918.png)
After setting back the manual "stability adjustment" setting to disabled, please reboot your unit.

**Comment by gnuton** [comment]
DSL Modems seems not to correctly work when SNR is set to something different than 0

-dslx_snrm_offset=0
+dslx_snrm_offset=112

In order for the modem to get seen again, you want to set back the SNR to disabled and then reboot the unit, this makes all working again.

Root cause of this is under investigation.

**Comment by gnuton** [comment]
Inolved kernel modules
/proc/sys/net/ipv4/conf/dsl0# lsmod | grep dsl
adsldd                512980  0 
bcmxtmcfg              95175  1 adsldd

**Comment by gnuton** [comment]
rgrep dslx_snrm_offset
Binary file rc/prebuild/DSL-AX82U/dsl_fb.o matches
Binary file rc/prebuild/DSL-AC68U/dsl_fb.o matches
rc/dsld.c:	cur_record->snrm = nvram_get_int("dslx_snrm_offset");
rc/dsl.c:	p->snrm = nvram_get_int("dslx_snrm_offset");
shared/defaults.c:	{ "dslx_snrm_offset", "0", CKN_STR8, CKN_TYPE_DEFAULT, CKN_ACC_LEVEL_DEFAULT, CKN_ENC_DEFAULT, 0 },	/* Paul add 2012/9/24 */
Binary file dsl_drv_tool/tp_init/prebuild/tp_init matches

**Comment by gnuton** [comment]
I have noticed all images comes with two DSL drivers.
one is the newest one and the other one ins /etc/adsl1 is an old one which is used as fallback in case SNR is changed.
this driver is A2pv6L047f1, 
The reason for having two drivers is that chipset vendors will not support this feature in new driver since it is non-statndard.

**Comment by gnuton** [comment]
root@DSL-AX82U:/tmp/home/root# md5sum /rom/etc/adsl/adsl_phy.bin
b571853775ffaf3751627ca3fab3bb7d  /rom/etc/adsl/adsl_phy.bin
root@DSL-AX82U:/tmp/home/root# md5sum /rom/etc/adsl1/adsl_phy.bin
46060171e3674dfca17e72342f8fc877  /rom/etc/adsl1/adsl_phy.bin

**Comment by gnuton** [comment]
not working driver
# find / -name "adsl*"
/lib/modules/4.1.52/extra/adsldd.ko
/rom/etc/adsl
/rom/etc/adsl/adsl_phy.bin
/rom/etc/adsl1
/rom/etc/adsl1/adsl_phy.bin
/tmp/adslcfg.dat
/tmp/adsl
/tmp/etc/adsl

**Comment by gnuton** [comment]
working driver
```
 find / -name adsl*
/lib/modules/4.1.52/extra/adsldd.ko
/rom/etc/adsl
/rom/etc/adsl/adsl_phy.bin
/rom/etc/adsl1
/rom/etc/adsl1/adsl_phy.bin
/sys/module/adsldd
/sys/module/bcmxtmcfg/holders/adsldd
/tmp/adsl
/tmp/etc/adsl1
/tmp/etc/adsl

```

**Comment by gnuton** [comment]
diff ./release/src-rt-5.04axhnd.675x/bcmdrivers/opensource/include/bcm963xx/bcmxtmcfg.h /home/aaloisio/GITonio/ASUSWRT_ORIG/__ORIG/NEW/asuswrt/release/src-rt-5.02axhnd.675x/bcmdrivers/opensource/include/bcm963xx/bcmxtmcfg.h

**Comment by gnuton** [comment]
/sys/devices/virtual/net/dsl0# ls
addr_assign_type   dev_port           link_mode          queues
addr_len           dormant            mtu                speed
address            duplex             name_assign_type   statistics
bcm_mcastrouter    flags              netdev_group       subsystem
broadcast          gro_flush_timeout  operstate          tx_queue_len
carrier            ifalias            phys_port_id       type
carrier_changes    ifindex            phys_port_name     uevent
dev_id             iflink             phys_switch_id

**Comment by gnuton** [comment]
# find / -name dsl0 -print
/proc/sys/net/ipv4/conf/dsl0
/proc/sys/net/ipv4/neigh/dsl0
find: /proc/7900: No such file or directory
/sys/devices/virtual/net/dsl0
/sys/class/net/dsl0

**Comment by gnuton** [comment]
I think I found the issue.
The problem was in the a tool which builds the ROM filesystem and that for some reason was not correctly with the old DSL firmware.

This is the latest beta image with the SNR fix.
To test it just enable "Stability adjustement" and check if you router can connect to internet through DSL
![image](https://user-images.githubusercontent.com/576580/210652954-c342d1bc-67db-4530-a9ea-ae89b45e7c2c.png)

https://output.circle-artifacts.com/output/job/4309befa-b3aa-43d0-af6f-a86183a1405b/artifacts/0/workspace/release/DSL-AX82U_388.1_0_puresqubi.w

**Comment by JustifYI** [comment]
> I think I found the issue. The problem was in the a tool which builds the ROM filesystem and that for some reason was not correctly with the old DSL firmware.
> 
> This is the latest beta image with the SNR fix. To test it just enable "Stability adjustement" and check if you router can connect to internet through DSL ![image](https://user-images.githubusercontent.com/576580/210652954-c342d1bc-67db-4530-a9ea-ae89b45e7c2c.png)
> 
> https://output.circle-artifacts.com/output/job/4309befa-b3aa-43d0-af6f-a86183a1405b/artifacts/0/workspace/release/DSL-AX82U_388.1_0_puresqubi.w

Great, changing the SNR now works properly!

**Comment by djt7787** [comment]
Yeah! Works perfectly on mine too, seems to stable. Thanks again gnuton 🍻

**Comment by gnuton** [comment]
sorry for the wait guys this was bug was A LOT of digging....

**Comment by gnuton** [comment]
the fix is now in the master line and it will be part of the next images
