### ISSUE TITLE
System log flooded with bsd errors

### ISSUE THREAD

**Issue by wbennett640** [gnuton/asuswrt-merlin.ng#295]
**Router Model Affected**
Models: RT-AX82U/

**Firmware Version Affected**
388.1.0-gnuton beta 1

**Describe the bug**
Continuous bsd errors in system log

**Comment by DJREMIXED** [comment]
You mean bad errors or what does BSD mean. It’s not Microsoft Windows (blue screen of Death) :)

**Comment by gnuton** [comment]
@wbennett640 can you share yout logs after resetting your router?

**Comment by wbennett640** [comment]
It looks like it was related to having "Auto select channel including DFS channels" activated on the 5GHz wireless settings. Once I deactivated it the BSD errors disappeared.

**Comment by gnuton** [comment]
Closing this as WON'T FIX.
