### ISSUE TITLE
Flow cache disabled with Wireguard

### ISSUE THREAD

**Issue by micron888** [gnuton/asuswrt-merlin.ng#299]
**Router Model Affected**
Models: (TUF-AX5400)

**Firmware Version Affected**
[Unstable: 388.1_0-gnuton0_beta1](https://github.com/gnuton/asuswrt-merlin.ng/releases/tag/388.1_0-gnuton0_beta1)

**Is this bug present in upstream Merlin releases too?**
Not sure

**Describe the bug**
Flow cache turn off with wireguard active

**Comment by Gruven** [comment]
It doesn't work with Broadcom chip, so this is not a bug. https://github.com/ZebMcKayhan/WireguardManager#disable-flowcache
