### ISSUE TITLE
What is the file size of TUF-AX5400 388.1_0-gnuton0_beta1?

### ISSUE THREAD

**Issue by sakasoon** [gnuton/asuswrt-merlin.ng#300]
Nice to meet you.
I am downloading 388.1_0-gnuton0_beta1.zip, but the download is still not finished after 1.5 GB. What is the file size?

**Comment by neil1962** [comment]
https://github.com/gnuton/asuswrt-merlin.ng/releases

Under Assests you will size the file size it is 48 or 48.6 MB

**Comment by sakasoon** [comment]
I was trying to download the Source code by mistake. I am glad you told me about it.
One more point I would like to know.
TUF-AX5400_388.1_0-gnuton0_beta1_puresqubi.w
TUF-AX5400_388.1_0-gnuton0_beta1_tuf_puresqubi.w
What is the difference between these two files? I don't know which one to use.

**Comment by neil1962** [comment]
The Tuf one would be the he yellow type of web interface, the other would the be the standard merlin web gui

**Comment by neil1962** [comment]
My preference would be the TUF-AX5400_388.1_0-gnuton0_beta1_puresqubi.w.

**Comment by neil1962** [comment]
I am not a fan of the TUF web gui, too colorfull for me, but you can try try both and select your preference.

**Comment by sakasoon** [comment]
I could see the difference between the two.
First trying TUF-AX5400_388.1_0-gnuton0_beta1_puresqubi.w.
Thanks!!
