### ISSUE TITLE
5Ghz WIFI unstable in 388.1_0-gnuton0_beta2

### ISSUE THREAD

**Issue by Rovasteen** [gnuton/asuswrt-merlin.ng#302]
TUF-AX5400 flashed to 388.1_0-gnuton0_beta2.  WIFI in the 5Ghz band drops, reconnects and drops again.  Seems cyclic.

Using default professional settings.  Basic settings are:

- 20/40/80/160 MHz Auto
- tick box set for Enable 160 MHz
- Control channel Auto
- tick box set for Auto select channel including DFS channels
- Extension channel Auto
- Authentication Method WPA2/WPA3 Personal
- WPA Encryption AES

After disconnecting over and over again, flashed back to 386.07_2-gnuton1 which is stable.  5Ghz WIFI immediately stable on 386.07_2-gnuton1. 

2.4 Ghz seems stable on both 388.1_0-gnuton0_beta2 and 386.07_2-gnuton1.

The fault reported is unstable WIFI in the 5Ghz band on the 388.1_0-gnuton0_beta2 build.  WIFI in the 5Ghz band drops, reconnects and drops again.

**Comment by gnuton** [comment]
do you have any log?

**Comment by qqw1231** [comment]
TUF AX 3000 also appeared you this problem, said no one fixed

**Comment by GaselK** [comment]
I have zero problems with 5Ghz. (Beta 2). Maybe you should try manual channel setting,

**Comment by ThrnSC87** [comment]
No issue here on tuf ax5400 running on a ax client and a few ac devices no issue whatsoever.

**Comment by Rovasteen** [comment]
Both 386.07_2-gnuton1 and 388.1_0-gnuton0_beta2 are using Broadcom wireless drivers 17.10 RC157.2809 so it probably isn't the build.  I will play around with this and reopen if I can recreate..

**Comment by Williams789** [comment]
This may seem a little different from the above, but in my case, when ISP ip spoofing was enabled, the Wi-Fi device could not be downloaded or slowed down to 800 kbps.(wireless LAN devices have a faster normal range speed)

Both 386.07_2-gnuton1 and 388.1_0-gnuton0_beta2 are the same in my tuf-ax5400.
