### ISSUE TITLE
TUF5400 GUI issue

### ISSUE THREAD

**Issue by micron888** [gnuton/asuswrt-merlin.ng#308]
**Router Model Affected**
Models: TUF-5400

**Firmware Version Affected**
388.1 beta 2

**Is this bug present in upstream Merlin releases too?**
Not sure

Ethernet port display
![image](https://user-images.githubusercontent.com/59114523/210020355-11c870ec-13c3-42c6-a3cc-5b1b9c83a839.png)

**Comment by gnuton** [comment]
This issue is due to browser cache.
Open the page in incognito and you will see it will be correctly displayed

**Comment by micron888** [comment]
thanks.. it works after clearing cache. thanks
