### ISSUE TITLE
Question: Does the firmware support AiMesh?

### ISSUE THREAD

**Issue by JimmyWuMadchester** [gnuton/asuswrt-merlin.ng#31]
As the mainline Asuswrt-Merlin 384.13 adds full support for AiMesh, does latest release v384.14_2-gnuton1 supports AiMesh?

I checked your previous releases that mentioned AiMesh. It seems you have disabled it from WebUI?

**Comment by gnuton** [comment]
The latest releases have AiMesh enabled.
