### ISSUE TITLE
Asus TUF AX5400 Cannot change icon for devices

### ISSUE THREAD

**Issue by bobyang3** [gnuton/asuswrt-merlin.ng#313]
**Router Model Affected**
TUF AX5400 

**Firmware Version Affected**
[386.07_2-gnuton1](http://router.asus.com/Advanced_FirmwareUpgrade_Content.asp)

**Is this bug present in upstream Merlin releases too?**
No

**Describe the bug**
I cannot change the icon. (currently, I use Asus app to change it)

**To Reproduce**
1. Go to 'Network Map'
2. Click on 'View List'

**Expected behavior**
I can change the icon.

**Screenshots**
![image](https://user-images.githubusercontent.com/2717137/210404194-972a07cb-1ee8-4850-afd3-5b9b861015c2.png)

**Comment by gnuton** [comment]
I am not sure TUF UI supports it.
You can flash the no_tuf image. 
it should work there.

**Comment by GaselK** [comment]
This is no bug. You can not change icon from that list. Icons can change (in ui, tuff or not) from the right list "Client status"
![2023-01-05](https://user-images.githubusercontent.com/100087871/210836903-2e45b4cb-da4c-43b8-a051-cf411bb35be0.png)

**Comment by bobyang3** [comment]
> This is no bug. You can not change icon from that list. Icons can change (in ui, tuff or not) from the right list "Client status" ![2023-01-05](https://user-images.githubusercontent.com/100087871/210836903-2e45b4cb-da4c-43b8-a051-cf411bb35be0.png)

thanks! I guess I need to update it first because I don't have "client status" in 386.


![image](https://user-images.githubusercontent.com/2717137/210906033-60c57de7-10c2-4e62-96d9-5e78e7d6cf74.png)
