### ISSUE TITLE
TUF-AX3000RAM has been growing. What's the matter

### ISSUE THREAD

**Issue by qqw1231** [gnuton/asuswrt-merlin.ng#315]
![IMG_20230105_135758](https://user-images.githubusercontent.com/110271812/210712144-b62688f3-fbc3-4231-abec-b7569ab57df4.jpg)

**Comment by gnuton** [comment]
normal on linux systems. do not be worried. 
get worried if it grows constantly and reaches 100%
71% is way below a warning point (80%) and far away from anythinc critical.
