### ISSUE TITLE
no 5ghz Guest Wifi available

### ISSUE THREAD

**Issue by gittyuphaz** [gnuton/asuswrt-merlin.ng#325]
**Router Model Affected**
Models: RT-AX92U
Firmware Version Affected**
388.xx Includes 388.1-gnuton0_beta2

**Is this bug present in upstream Merlin releases too?**
Unsure. I updated to wrt merlin after install

**Describe the bug**
Unable to see 5ghz networks on guest network page. Only 2.5ghz and Facebook WiFi Appear.

**To Reproduce**
I have 2 of these routers in aimesh mode.
1. Go to Guest Network
2. See no 5ghz

**Expected behavior**
Scross down you should be able to dd guest got 5ghz

**Screenshots**

![Capture](https://user-images.githubusercontent.com/122751119/212565853-7c43bdec-9e90-47cc-93f1-a3f3c0dcf2c9.PNG)

**Comment by gnuton** [comment]
Hi,
have you reset to factory after updating from stock?

**Comment by gittyuphaz** [comment]
I just tried that and can see the 5ghz guest option after unfortunately, if I then restore my router settings backup file it disappeared again.

**Comment by gnuton** [comment]
@gittyuphaz stock and merlin do not have compatible settings. If this is what you are trying to do you basically can't without running in issues like this.
Can i close this issue?

**Comment by gittyuphaz** [comment]
Hi, makes sense. thanks for the great support. plesase go ahead and close. All the best and thanks for your hard work on this fork!
