### ISSUE TITLE
Support request - router with wrong ID

### ISSUE THREAD

**Issue by qqw1231** [gnuton/asuswrt-merlin.ng#326]
![IMG_20230118_130608](https://user-images.githubusercontent.com/110271812/213089189-d5c65a1c-5e82-4979-8f7c-9bc2cf97e882.jpg)

**Comment by qqw1231** [comment]
AX 3000 here is raised

**Comment by gnuton** [comment]
please in SSH run

envrams set odmpid=ASUS
envram commit
reboot
