### ISSUE TITLE
tuf ax3000

### ISSUE THREAD

**Issue by qqw1231** [gnuton/asuswrt-merlin.ng#327]
TUF AX3000
![IMG_20230119_145103](https://user-images.githubusercontent.com/110271812/213375390-ee2ff930-4dd2-45e8-aaa1-ded2c896e686.jpg)
AX86 PRO
![IMG_20230119_145158](https://user-images.githubusercontent.com/110271812/213375450-02c491f1-3a02-4ef2-b444-aa8ca2fa48d1.jpg)

**Comment by gnuton** [comment]
what is this about? missing gradient?

**Comment by gnuton** [comment]
The gradient is correct
![image](https://user-images.githubusercontent.com/576580/213475127-5f1f16cb-6189-4c5f-99f6-8bc359eccbc1.png)
