### ISSUE TITLE
Unable to install Merlin on RT-AX82U V2

### ISSUE THREAD

**Issue by asoluter** [gnuton/asuswrt-merlin.ng#357]
**Router Model Affected**
Models: RT-AX82U V2

**Firmware Version Affected**
388.1  (RT-AX82U_388.1_0-gnuton1_puresqubi.w)

**Is this bug present in upstream Merlin releases too?**
Yes (The latest available 388.1 one and tested on a couple of older 386.x ones)

**Describe the bug**
Upon uploading the latest stable firmware, router says:
```
Firmware upgrade unsuccessful. This may result from incorrect image or error transmission. Please check the version of firmware and try again.
```
The update file MD5 hash matches the github reference one.
Currently installed firmware is the latest stock one: 3.0.0.4.388_22525

**To Reproduce**
1. Go to 'Administration->Firmware Upgrade' page
2. Click on 'Manual firmware update->Upload'
3. Select 'RT-AX82U_388.1_0-gnuton1_puresqubi.w'

**Expected behavior**
Successful installation

**Comment by gnuton** [comment]
V2 is not supported yet.
I may think to support it from the next release..

**Comment by kchen7e** [comment]
> V2 is not supported yet.
> I may think to support it from the next release..

AX3000 V2 is not mentioned in the latest _Unstable: 388.2-gnuton0_beta1_ yet, is there any update please?

**Comment by gnuton** [comment]
@kchen7e I do have plans to support it by this year

**Comment by SMOL25** [comment]
Where can I buy rt ax82u v2? I'm from Portugal.

**Comment by lawtj93** [comment]
Hi, I want to pull the trigger on the ax82u v2 but just want to confirm with you if you're still planning to support it by end of the year? Appreciate all your efforts across the project!

**Comment by gnuton** [comment]
there is a beta available. there are still some issues which will be fixed once i get how to fix them.
I will close this issue since there is a dedicated issue on github related to work left on V2.
