### ISSUE TITLE
RT-AX92U

### ISSUE THREAD

**Issue by misokouji** [gnuton/asuswrt-merlin.ng#361]
**Router Model Affected**
Models: RT-AX92U

**Firmware Version Affected**
 386.8_0

**Is this bug present in upstream Merlin releases too?**
I do not know yet.

**Describe the bug**
I could install merlin version from ASUS original and later I changed back to ASUS latest version to check something.
Then try to install merlin again but always fail and cannot install merlin version any longer.
I didnot try latest one yet. 

**To Reproduce**
1. Go to 'firmwaer update'
2. Click on 'update'

**Comment by gnuton** [comment]
reset the route to factory and try again
