### ISSUE TITLE
TUF-AX3000 V2

### ISSUE THREAD

**Issue by mattjonesuk** [gnuton/asuswrt-merlin.ng#367]
**Is your feature request related to a problem? Please describe.**
I would like a version that is compatible with the TUF-AX3000 V2 router please. 

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by gnuton** [comment]
Please vote for it in the page https://github.com/gnuton/asuswrt-merlin.ng/issues/140 
Thanks a lot

**Comment by DevangerTM** [comment]
Please support TUF-AX3000 v2
