### ISSUE TITLE
388.2 beta1 on ET8/RT-AXE95Q - firmware update only shows main router and no remote mesh nodes.

### ISSUE THREAD

**Issue by CHF-UK** [gnuton/asuswrt-merlin.ng#374]
Hi gnuton,

With 388.2 beta 1, the only issue i've found is only the main router is shown in the firmware upgrade screen, the 3 remote nodes dont show (1 wires, 2 wireless).

![image](https://user-images.githubusercontent.com/121666800/235301512-4ce543c5-91aa-486c-81c0-6334895f2997.png)

![image](https://user-images.githubusercontent.com/121666800/235301801-8eb6d946-8a2e-4c15-9b07-deb458f3779b.png)

Other than that, this appears a great release.  Uptime currently just short of 24 hours and everything connected wirelessly seems to have a lot more reliable connection with clients no longer being randomly disconnected for minutes at a time.  Everything seems stable even if pushed relatively hard. 

![image](https://user-images.githubusercontent.com/121666800/235302008-6756409a-1763-4a69-86a8-690fb5ad4e6e.png)

**Comment by bconrad0321** [comment]
I can confirm on my ET8 as well.

**Comment by paul-hostetler** [comment]
This is also an issue in 388.2 beta 2. The firmware upgrade webpage only shows the main node. The iOS app does show both nodes.

**Comment by gnuton** [comment]
fix in https://github.com/gnuton/asuswrt-merlin.ng/tree/BUG-374_merlin-function-missing-in-www-sysdep

**Comment by gnuton** [comment]
tested and confirmed 4830eb669921b0b90b083467f7279b608c874ba7 fix the issue
