### ISSUE TITLE
请问ax5400 v2的固件什么时候有

### ISSUE THREAD

**Issue by Tiberiusjhh** [gnuton/asuswrt-merlin.ng#382]
请问ax5400 v2的固件什么时候有？谢谢

**Comment by gnuton** [comment]
Please speak english. thanks

**Comment by ratelgogo** [comment]
When will the firmware of ax5400 v2 be available？tks

**Comment by gnuton** [comment]
What's the AX5400 v2? can you link me to the asus webpage showing the product?

**Comment by ratelgogo** [comment]
I do not know, maybe it is another name of TUF-AX5400, but newer 😃
