### ISSUE TITLE
TUF-Ax5400 Traffic stats gui

### ISSUE THREAD

**Issue by micron888** [gnuton/asuswrt-merlin.ng#387]
Unstable: 388.2_2-gnuton0_beta2
TUF AX-5400
GUI isue
![image](https://github.com/gnuton/asuswrt-merlin.ng/assets/59114523/032eceaa-3b3a-4c8a-8986-970ce64221e6)

**Comment by gnuton** [comment]
What's the problem it doesn't show data or just broken UI?

**Comment by micron888** [comment]
No on/off button
Cannot show data

**Comment by Nehaxak** [comment]
Can confirm. Same problem here, same router, same latest beta.

Agreed to privacy. Same issue.
Withdrew from privacy. Same issue.

Fresh install, same issue.

Just tried a few of the above to test.

Just seems like a gui issue, gui button/switch missing to enable/disable.

**Comment by gnuton** [comment]
have you noticed the same issue in the beta1?

**Comment by micron888** [comment]
Same in beta 1

**Comment by Nehaxak** [comment]
Issue was not there for me in the beta 1.

**Comment by gnuton** [comment]
duplicate of https://github.com/gnuton/asuswrt-merlin.ng/issues/403
