### ISSUE TITLE
Firmware for DSL-AC68VG

### ISSUE THREAD

**Issue by Cure1111** [gnuton/asuswrt-merlin.ng#39]
I have an **ASUS DSL-AC-68VG**. Do you know if your firmware works there or what needs to be adjusted?
current firmware is: **Version 5.00.08**_build272 and not 384.16_0
[Firmware_DSL-AC68VG.zip](https://github.com/gnuton/asuswrt-merlin.ng/files/4674353/Firmware_DSL-AC68VG.zip)

**Comment by gnuton** [comment]
Merlin cannot run on that router. Sorry.
