### ISSUE TITLE
[RT-AXE95Q ZenWifi ET8][388.1_0-gnuton1] Speed cut half off with WireGuard enabled.

### ISSUE THREAD

**Issue by Sraw** [gnuton/asuswrt-merlin.ng#393]
**Router Model Affected**
Models: RT-AXE95Q ZenWifi ET8

**Firmware Version Affected**
388.1_0-gnuton1

**Is this bug present in upstream Merlin releases too?**
N/A, the upstream Merlin release doesn't support ET8 at all.

**Describe the bug**
The wireless speed is cut half off with WireGuard enabled. For example, ideally, the download speed for my 6G network is around 900 Mbps, but with the WireGuard enabled, it can only reach about 430 Mbps. The same thing happens to the 5G network. I didn't test the 2.4G cause I mostly don't use it.

Also, I didn't test the other VPN servers.

**To Reproduce**
1. Test the network speed using fast.com with WireGuard disabled.
2. Test the network speed using fast.com with WireGuard enabled.
3. See the difference.

**Expected behavior**
It shouldn't affect the wireless speed.

**Screenshots**
N/A

**Comment by Sp0Xik** [comment]
388.1 disables NAT acceleration when using Wireguard. Use 388.2 there it's fixed.
