### ISSUE TITLE
[RT-AXE95Q Zenwifi ET8] iOS Device List Disappears When Only Primary Node Configured

### ISSUE THREAD

**Issue by phostetl** [gnuton/asuswrt-merlin.ng#396]
**Router Model Affected**
Models: RT-AXE95Q

**Firmware Version Affected**
388.2_2 Gnuton Beta

**Is this bug present in upstream Merlin releases too?**
Unknown

**Describe the bug**
I have a two-node system.  I removed the secondary node and the list of connected clients in the iOS app was empty.   Connected clients did show in the web interface.

**To Reproduce**
1. Remove all nodes leaving only the primary node.
2. Open iOS app.
3. Device list is empty.
4. See the error

**Expected behavior**
The list should match the web interface.

**Screenshots**
If applicable, add screenshots to help explain your problem or remove this section

**Comment by phostetl** [comment]
I found this because I was having some problems with the Wi-Fi connection periodically.  I suspected it might be a backhaul issue.  After I removed the other node I noticed the issue.  I readded the node and the problem disappeared.  I'm now running a wired backhaul which seems to have improved the Wi-Fi stability.

**Comment by gnuton** [comment]
can I close this issue?

**Comment by phostetl** [comment]
Please close the issue.
