### ISSUE TITLE
Guest network page seems broken/bugged, Zenwifi XT8, RT-AX95Q, 388.2_2_0

### ISSUE THREAD

**Issue by jazha** [gnuton/asuswrt-merlin.ng#414]
**Router Model Affected**
Models: (eg: ZenWifi XT8, RT-AX95Q)

**Firmware Version Affected**
RT-AX95Q_388.2_2_0-gnuton1_puresqubi

**Is this bug present in upstream Merlin releases too?**
I'm not sure

**Describe the bug**
The page to setup Guest Network(s) seems to be broken

**To Reproduce**
1. Login to router
2. Click Guest network
3. Page Looks like the pictures attached

**Expected behavior**
I expect the page to make sense, as it is now, it looks broken and unintuitive.

**Screenshots**
![1](https://github.com/gnuton/asuswrt-merlin.ng/assets/3653177/ede1dec4-537a-468e-aafa-d9bd8f299df3)
![2](https://github.com/gnuton/asuswrt-merlin.ng/assets/3653177/ef3716c4-be34-4501-a2ea-0f9c219bcfbd)

**Comment by gnuton** [comment]
does it look any better if you open the page in an incognito browser?

**Comment by jazha** [comment]
> does it look any better if you open the page in an incognito browser?

Sorry for the late response. It does not look any different in incognito mode

**Comment by Wyehoota** [comment]
Click one of the "enable" buttons, and set/accept values - see if that then looks more like you expected. In you grab, all guest networks are disabled.

**Comment by jazha** [comment]
I'm away for the weekend, will check when I'm back. 

However the landing page should not look like that, the design is highly confusing and unintuitive, and I suggest it is changed so you actually know what you click enable for, and maybe remove the extra(?) buttons with enable. Having 3 buttons of each wireless seems excessive. 

Anyway, I will check back on sunday evening probably, try to click enable to see.

**Comment by jazha** [comment]
I see now, there are 3 possible guest networks per wifi channel or something. 3 for 2.4Ghz, 3 for 5Ghz-1 and 3 for 5Ghz-2.

It was just not very intuitive, and it might be the way it looks in the official software too, I dont know. Anyway, clicking the buttons provide the interface I expected. Not really a bug, more UI improvement could be done to explain that button 1 is network 1 etc.
