### ISSUE TITLE
Mixed bridged/routed mode

### ISSUE THREAD

**Issue by ja2k2o** [gnuton/asuswrt-merlin.ng#42]
**Is your feature request related to a problem? Please describe.**
Boy, this will be a long one… Generally, most people run their DSL boxes in routed mode with NAT, which for most cases works just fine. But if you have two or more devices in the LAN there might be cases when a service on the WAN side can't distinguish those devices from each other. This is the case for e.g. Nintendo Switch game servers. I have two Switch consoles but can join online games with only one at a time — which means my kids are not able to play the same game together. 

**Describe the solution you'd like**
I'd like to be able to set individual ethernet ports to function in either routed on bridged mode. Currently the setting (Advanced Settings > WAN > Interner Connection > WAN Connection Type) is global. The setting should not affect Wireless. This way I could set one ethernet port to bridged mode (and thus, having ISP's IP addresses behind that port) connected to a separate wifi station and routed NAT (with my local private IP addresses) with the rest.

**Describe alternatives you've considered**
I first tried to set up a DMZ, but it does not solve the issue — both consoles are still behind the NAT. Another option was to change the mode from routed (PPPoE) to Bridged, but my ISP only allows five IPv4 addresses and no IPv6 (I've complained about his for at least 10 years now) which is completely inadequate. 

**Additional context**
Of course the ultimate solution to my issue would be my ISP finally providing IPv6 but that's unlikely. :(  I could also buy another DSL box and run that in bridged mode and the daisy chain AC68U behind it as a basic router but that's not very elegant.

**Comment by gnuton** [comment]
Hi and thanks for reporting this request feature,
I believe you could achieve what you want using a script, but I would not create a web ui for this since I would try to keep this as close as possible to current Merlin.
Please, ask for support at https://www.snbforums.com/ quite sure you will get what you want.
