### ISSUE TITLE
Unable install on Asus AX-82U

### ISSUE THREAD

**Issue by bdkacz** [gnuton/asuswrt-merlin.ng#423]
**Router Model Affected**
Models: RT-AX82U v1

**Firmware Version Affected**
388.2.2

**Is this bug present in upstream Merlin releases too?**
I don't know

**Describe the bug**
I'm unable to flash the firmware  from factory to this  using webui - I get  "please wait updating" and no progress bar

**To Reproduce**
1. Go to Administration
2. Click on Update firmware
3. Click browse
4. Select file and start flashing

Should I flash it using asus firmware restoration utility ?

**Screenshots**
![Firmware update](https://github.com/gnuton/asuswrt-merlin.ng/assets/6986901/a5c1847f-3a92-49cd-a468-64bb634adb34)

**Comment by bdkacz** [comment]
I also try install once again stock firmware and after a while the flashing bar is displayed and flashed successfully. Next I try one again upload this firmware and..the same stuck on "Please wait"

**Comment by gnuton** [comment]
are you sure you have a v1?

**Comment by bdkacz** [comment]
Yes, I checked x2 -  on label H/W ver 1.0

When I downgrade to 3.0.0.4.388.22525 and then try flash Your firmware the progress bar goes to 100% and after re-login there is still stock firmware

**Comment by bdkacz** [comment]
Ups...

On top of  label : 

Model rt-ax82u v2

But near S/N I have  H/W Ver: 1.0 LOL
