### ISSUE TITLE
What's the difference between puresqubi and tuf_puresqubi ?

### ISSUE THREAD

**Issue by sangju41** [gnuton/asuswrt-merlin.ng#427]
Hello,

I'm using TUF AX5400 v1 router with original firmware.
I want to migrate to merlin firmware. I notice that there are two versions of firmwares namely puresqubi and tuf_puresqubi.
What are the difference between these two ? What version should I use to ?

Thanks in advance.

**Comment by DervilRus** [comment]
puresqubi  - standart asus interface (gray/blue)
tuf_puresqubi - tuf interface (yellow/black)

**Comment by gnuton** [comment]
Closed since this question has been answered correctly by @DervilRus
