### ISSUE TITLE
Model XT8 and RT-AX82U both of them have a problem with link as AI Mesh Mode.

### ISSUE THREAD

**Issue by hunterpl** [gnuton/asuswrt-merlin.ng#435]
**Router Model Affected**
Models: ( RT-AX82U and XT8)

**Firmware Version Affected**
388.4_0-gnuton0_alpha1

**Is this bug present in upstream Merlin releases too?**
Yes

**Describe the bug**
After upgrade one main router first, so which was RT-AX82U was upgraded successfully, everything was fine, but, when I started upgrade the second router, which was linked as a node, it was successfully upgraded but does not started any more, just blinking blue all the time, I just made a several test with both of routers and switch them even from the scratch [ reset to hardware default ], the result is always the same, they can not be linked with AI Mesh Mode, not possible, but when I configure them separetly as normal router everything works as expected, only not possible link as AI Mesh Mode.

**To Reproduce**
1. Go to asus router normal login
2. Click on AIMesh
3. Add AIMesh node as new router, even if it was blinked I tried reset to default, same result can not be pair, all the time failed.

**Expected behavior**
I made XT8 as primary router and working fine, but when I wanted to make AX-82U as second node in AI Mesh mode, does not work, all the time blinked, broken config or something, but firmware is installed successfully.

**Screenshots**
there is no need a screenshots.

**Comment by gnuton** [comment]
Thanks I will look at what's wrong.
The problem this alpha firmware seems to not work for mesh nodes.  Please correct me if I am wrong.
Question: are the master and node connected with a cable or via wireless?

**Comment by hunterpl** [comment]
> Thanks I will look at what's wrong. The problem this alpha firmware seems to not work for mesh nodes. Please correct me if I am wrong. Question: are the master and node connected with a cable or via wireless?

Yes Mesh node does not work only tested for wireless, did not tested with lan, but I think will be the same results.

**Comment by gnuton** [comment]
actually it's not the same, binding two wireless devices is way more complex than connecting two devices connected through ethernet. Usually there is not packet encryption over ethernet nor scanning and pairing.. over ethernet it's mostly plug and play.

**Comment by hunterpl** [comment]
Yes this is correct information, but this is not possible if first attempt is configuration via phone and use app from asus router via WIFI, so if WIFI does not work I can not switch to Lan :C

**Comment by gnuton** [comment]
Asus app is not supported. It may work, but it's not supported.
I never tried to pair via Wifi and then switch to ethernet, but the other way around works.

**Comment by JonnyVR1** [comment]
I've tried pairing with both wire and wireless, neither work on 388.4, even for nodes that existed before the update, they show as offline

**Comment by JonnyVR1** [comment]
Works as of the latest beta, @gnuton this can be closed

**Comment by hunterpl** [comment]
Yes working for the latest firmware, great job.

**Comment by gnuton** [comment]
👍 awesome I will close this.
