### ISSUE TITLE
388.4_0-gnuton0_alpha1 main router client counts, lists, and statuses showing 0/nothing/empty

### ISSUE THREAD

**Issue by shiang-luong** [gnuton/asuswrt-merlin.ng#438]
**Router Model Affected**
Models: xt8

**Firmware Version Affected**
388.4_0-gnuton0_alpha1

**Is this bug present in upstream Merlin releases too?**
No

**Describe the bug**
The client list isn't showing up or being populated.  Dirty upgrade from 388.2_2_0-gnuton1

**To Reproduce**
1. Log into Asus router
2. On main home page you will see 0 for clients
3. When you click on the client 'view list', there is no clients listed
4. When you click on number 0, no clients are listed on the right hand side under 'Client Status'

**Expected behavior**
User should be able to see list of clients in the views mentioned above

**Screenshots**
![Screenshot 2023-07-27 2 50 38 PM](https://github.com/gnuton/asuswrt-merlin.ng/assets/48106860/7aa73edf-c5d8-4ad3-a23f-9ef9b919563c)

**Comment by tclam662** [comment]
Got the same problem with my xt8 on 388.4_0-gnuton0_alpha1, have to revert it back to 388.2.2

**Comment by shiang-luong** [comment]
> Got the same problem with my xt8 on 388.4_0-gnuton0_alpha1, have to revert it back to 388.2.2

I'm glad it isn't just me.

**Comment by disconnectome** [comment]
ax5400 same, ok

**Comment by micron888** [comment]
latest beta is ok
Release: 3004.388.4_0-gnuton0_beta1

**Comment by shiang-luong** [comment]
Agreed, this can be closed.  It is fixed in the beta
