### ISSUE TITLE
Is there a chance for Asus TUF Gaming AX3000 V2?

### ISSUE THREAD

**Issue by RemixPL1994** [gnuton/asuswrt-merlin.ng#441]
Is there a chance for Asus TUF Gaming AX3000 V2?

**Comment by DevangerTM** [comment]
I would need too.

**Comment by Rovasteen** [comment]
Me too.  This router would be great with Gnuton Asus Merlin support.

**Comment by metacorn** [comment]
Yeah, it would be awesome!

**Comment by gnuton** [comment]
Please do not hopen issue for new model support requests.
Use the appropriate page or the chat
https://discord.com/channels/1155054060848807976/1155059826427170816
