### ISSUE TITLE
Where is a Beta version of 388.4.0

### ISSUE THREAD

**Issue by neil1962** [gnuton/asuswrt-merlin.ng#449]
**Router Model Affected**
RT-AX82U

**Firmware Version Affected**
Latest Alpha

**Is this bug present in upstream Merlin releases too?**
Cannot test, but I don’t see similar reported issues in Merlins firmware, using the same ASUS GPL code, across routers in which he supports.

**Describe the bug**
Many, my 2 cents worth, Network listing, does not work, no clients are being listed, always blank, can though see clients via wireless log.  Cannot bind a client to a node. Connecting nodes is hit and miss even using an Ethernet connection. On upgrading from gnuton current stable release to latest alpha via a GUI dirty upgrade, corruption occurred in the client names in the network listing, before all client names just disappeared, and became blank on a reboot of the router. Not stable, all my nodes are using current ASUS stock firmware, constant drops with clients, reverted to latest current gnutom stable release, all network became stable again. Have tried multiple WPS resets, clearing browers cache, etc, does not fix the problems. I have to say this is the worst Alpha firmware I have seen from gnuton. I have been keeping my eye with different issues being reported with the latest Alpha firmware release and I am also not seeing any response from gnuton for a while now for these reported for issues. Whats going on?

**Comment by dacootmeister** [comment]
following this thread.... have not upgraded from 388.2_2-gnuton1 bcause of reported issues

**Comment by gnuton** [comment]
Thanks for testing @neil1962.
I will try to address al these issue. The beta will come soon.

**Comment by gnuton** [comment]
@neil1962 This a beta image for RT-AX82U V1. 
https://output.circle-artifacts.com/output/job/af759e87-352d-491a-8766-9d6aa96ea7c7/artifacts/0/workspace/release/RT-AX82U_3004_388.4_beta3_puresqubi.w 

I am not connected through it and it works fine after a dirty flash.
I have not tested AI Mesh although.

**Comment by dacootmeister** [comment]
> Thanks for testing @neil1962. I will try to address al these issues. The beta will come soon.

Thanks, will keep a close eye on it for the ZenWiFi_XT8 (base model: RT-AX95Q)

**Comment by shiang-luong** [comment]
I am also patiently waiting for the new beta ZenWiFi_XT8 (base model: RT-AX95Q)

**Comment by jef00** [comment]
![image](https://github.com/gnuton/asuswrt-merlin.ng/assets/16373048/0572fea5-1d06-4a2f-9283-52cd8cf1f530)
the name scheme is some different because i compiled myself is that correct @gnuton ? Its runs smooth on the RT-AX95Q!!

**Comment by shiang-luong** [comment]
> ![image](https://github.com/gnuton/asuswrt-merlin.ng/assets/16373048/0572fea5-1d06-4a2f-9283-52cd8cf1f530)
> the name scheme is some different because i compiled myself is that correct @gnuton ? Its runs smooth on the RT-AX95Q!!

If it works, I'm going to need to try that!!  Thanks

**Comment by jef00** [comment]
no problem @shiang-luong

**Comment by jef00** [comment]
the name scheme is changed that was stupid of me it is in the changelog. @gnuton question if i installed the compiled version is it then possible to check for firmware updates?

**Comment by gnuton** [comment]
The new schema version change comes from upstream. The ability to  look for updates is made of client and server parts. I need to test if it properly works. So building from source code is not an issue for that.

**Comment by jef00** [comment]
@gnuton thankyou for you response!! aah yes i see!. take your take for testing that out,  I am asking because i have built it and installed but if i want to check for updates i get this error:

![image](https://github.com/gnuton/asuswrt-merlin.ng/assets/16373048/e21dffe2-db12-4535-8ec8-1091a1fe27b1)

maybe i did something wrong when i compiled, i did 
#cd release/src-rt-5.02axhnd.675x
#make rt-ax95q

can you tell me if i miss something sorry to bother you

**Comment by gnuton** [comment]
I just need to fix something there. That was low prio, I noticed that last night, again, I have to fix it. The entire code for the version checking has changed due to new versioning schema. As for the timeline for the fix, it will be one of the last things I will fix before releasing the stable

**Comment by jef00** [comment]
@gnuton i can completely understand! thankyou for explaining and take your time!:)

**Comment by gnuton** [comment]
the beta is out. 
Closing this
