### ISSUE TITLE
388.4_Beta3 Slave nodes unavailable for firmware upgrade from Console UI.

### ISSUE THREAD

**Issue by DiMENZi0N** [gnuton/asuswrt-merlin.ng#452]
**Router Model Affected**
Models: Asus RT-AXE95Q (Zenwifi ET8)

**Firmware Version Affected**
388.4_beta3

**Is this bug present in upstream Merlin releases too?**
Unknown

**Describe the bug**
Firmware upgrade for slave nodes in Mesh network is not present.

**To Reproduce**
Login to Master Console.
Goto Firmware upgrade page.
ET8 AiMesh Slave is not present to select for upgrade.

**Expected behavior**
I expect to see my attached slave nodes to be available to flash firmware from the Master UI.

**Screenshots**
![image](https://github.com/gnuton/asuswrt-merlin.ng/assets/71680377/59c09e76-b155-448d-90f7-63e634e6657b)

![image](https://github.com/gnuton/asuswrt-merlin.ng/assets/71680377/63901fc4-50fe-4b15-85f3-f2bf238c8d56)

**Comment by DiMENZi0N** [comment]
Heads up this issue still remains in new firmware

![image](https://github.com/gnuton/asuswrt-merlin.ng/assets/71680377/6469ba9d-a21f-4f34-8451-6029e631c74d)

**Comment by gnuton** [comment]
fixed 72db9aa48ec3e873d0158239f30b6a629186f21f
