### ISSUE TITLE
RT-AX82U will not upgrade

### ISSUE THREAD

**Issue by Enigma1282** [gnuton/asuswrt-merlin.ng#454]
**Router Model Affected**
ModelsRT-AX82U
The web UI, after i attempt to upgrade to the merlin firmware, the UI will say "Please wait... Applying settings" and just stick there. nothing else will happen.

**Comment by gnuton** [comment]
Can you show me the output of 
nvram get productid

**Comment by Enigma1282** [comment]
RT-AX82U_388.2_2_0-gnuton1_puresqubi.w is the first one i attempted. I also attempted to use RT-AX82U_388.4_0-gnuton0_alpha1_puresqubi.w. Also I may sound dumb but what is " the output of
nvram get productid"

**Comment by elliotberry** [comment]
Not dumb at all. i just had to figure it out myself. Enable SSH on the router first, then SSH in and run that command. People say "nvram get productid" and they don't explain any context whatsoever

**Comment by Enigma1282** [comment]
"rt-ax82u_v2" is what the command brings back.

**Comment by Enigma1282** [comment]
"rt-ax82u_v2" is what the command brings back.

**Comment by hammerjoe** [comment]
> "rt-ax82u_v2" is what the command brings back.

It looks like you have V2 of the router and the image available is for V1. I think there is a V2 image somewhere.

**Comment by gnuton** [comment]
V2 is not supported yet. 
It will be supported soon btw. I already have working images, they are just not public yet.

@elliotberry good point. I will improve the documentation. thanks for pointing out!
