### ISSUE TITLE
TUF-5400 VPN tabs empty

### ISSUE THREAD

**Issue by darkdex52** [gnuton/asuswrt-merlin.ng#457]
**Router Model Affected**
Models: [TUF-AX5400 v1](https://www.asus.com/Networking-IoT-Servers/WiFi-Routers/ASUS-Gaming-Routers/TUF-Gaming-AX5400/)

**Firmware Version Affected**
[388.4_0-gnuton0_alpha1](https://github.com/gnuton/asuswrt-merlin.ng/releases/tag/388.4_0-gnuton0_alpha1)

**Is this bug present in upstream Merlin releases too?**
No

**Describe the bug**
After updating from 3.88.2 to 3.88.4, VPN Server and VPN Client tabs are completely empty and non-interactable.

**Screenshots**
https://i.imgur.com/Pm7SZoD.png
https://i.imgur.com/nJ4d5dU.png

**Comment by master88wi** [comment]
+1

**Comment by gnuton** [comment]
is this fixed in the latest beta?

**Comment by master88wi** [comment]
> is this fixed in the latest beta?

no

**Comment by gnuton** [comment]
Problem in VPN Server page
![image](https://github.com/gnuton/asuswrt-merlin.ng/assets/576580/e6f5d65f-9df1-49cc-b6d8-8861b20e4830)

**Comment by gnuton** [comment]
Problem in VPN CLient page
![image](https://github.com/gnuton/asuswrt-merlin.ng/assets/576580/f6500185-aae7-4032-9d0b-8a1c8fc98f75)

**Comment by gnuton** [comment]
Tested. There is still a bug here
![image](https://github.com/gnuton/asuswrt-merlin.ng/assets/576580/8624b532-8a36-4376-8b6c-2d0eb5a15e8a)

**Comment by gnuton** [comment]
Another issue in http://router.asus.com/Advanced_WireguardClient_Content.asp
![image](https://github.com/gnuton/asuswrt-merlin.ng/assets/576580/dd03e86e-64ba-4eba-b15b-60efca5a0b4e)

**Comment by darkdex52** [comment]
Fixed in [3004.388.4_0-gnuton0_beta2](https://github.com/gnuton/asuswrt-merlin.ng/releases/tag/3004.388.4_0-gnuton0_beta2)
