### ISSUE TITLE
Can't install Merlin to ZenWiFi XT8 v2

### ISSUE THREAD

**Issue by sanjeroHUN** [gnuton/asuswrt-merlin.ng#458]
**Router Model Affected**
Models: ZenWiFi XT8 v2

**Firmware Version Affected**
3.0.0.4.388_23285

**Describe the bug**
After selecting the RT-AX95Q_388* Merlin firmware for upload to my Zenwifi XT8 (V2) router the "Please wait, applying settings" title appears, but nothing else happens.
Am I right, that the Merlin version is currently not compatible with the V2 version of the Zenwifi XT8 router? Please try to make it compatible. :)

Thank you!

**Comment by Dodgydrains** [comment]
I don't think the V2 is compatible with Merlin, only V1

**Comment by gnuton** [comment]
Correct only V1 is supported for now

**Comment by sanjeroHUN** [comment]
Thanks! I will send it back due to the high latency peaks... For gaming it is unusable...

**Comment by gnuton** [comment]
closing this since it' a new model request.
