### ISSUE TITLE
App Connection Issue

### ISSUE THREAD

**Issue by micron888** [gnuton/asuswrt-merlin.ng#460]
Models:TUF-AX5400 v1

Firmware Version Affected
DEV_3004.388.4+RT-AX82U_V2_TEST_PARALLEL2

Is this bug present in upstream Merlin releases too?
388.2_2 is ok

Describe the bug
Asus Router App cannot connect from WAN
LAN ok

**Comment by gnuton** [comment]
If I got it right you are saying the web interface is not visible from a
public IP. Did I get it right?

**Comment by micron888** [comment]
I am able to access the login page from wan but run into login issues on both web or Asus app.

**Comment by micron888** [comment]
![Uploading Screenshot_20230916_210907_ASUS Router.jpg…]()

**Comment by gnuton** [comment]
what about accessing the router from WAN with a browser? does it work?

**Comment by micron888** [comment]
Nope, it doesn't work
login page keep showing up after I signin

**Comment by gnuton** [comment]
Did you see anything in the logs? Have you tried to reset to factory? Does it help? This feels to be something related to something broken due to settings which are not compatible with the new binaries

**Comment by micron888** [comment]
I will do a reset this weekend, and report finding

**Comment by micron888** [comment]
Ir seem to work magically today without doing anything.. Closing
