### ISSUE TITLE
Misssing (?) RT-AX92U_3004_3004.388.4_0-gnuton0_beta1_ubi.w 

### ISSUE THREAD

**Issue by Gkozd** [gnuton/asuswrt-merlin.ng#463]
No RT-AX92U_3004_3004.388.4_0-gnuton0_beta1_ubi.w  for RT-AX92U in Assets.

**Comment by gnuton** [comment]
Fixed ! :D
![image](https://github.com/gnuton/asuswrt-merlin.ng/assets/576580/75906f29-f501-4396-b82a-9c317e478e6c)
