### ISSUE TITLE
In 3004.388.4_0-gnuton0_beta1 for RT-AX92U *.w file is missing

### ISSUE THREAD

**Issue by juan-f-rico** [gnuton/asuswrt-merlin.ng#464]
Hi Antonio,
The last beta for RT-AX92U, 3004.388.4_0-gnuton0_beta1, doesn't have *.w file. Can you generate it, please?
Thanks for your great work.

**Comment by gnuton** [comment]
Hi @juan-f-rico 
If you have V1 please download this
RT-AX82U_3004_3004.388.4_0-gnuton0_beta1_puresqubi.w
in case of v2 get this
RT-AX82U_V2_3004_3004.388.4_0-gnuton0_beta1_nand_squashfs.pkgtb

**Comment by gnuton** [comment]
You are right. yes I will build  it

**Comment by gnuton** [comment]
RT-AX92U_3004_3004.388.4_0-gnuton0_beta1_ubi.w has been added 
please check https://github.com/gnuton/asuswrt-merlin.ng/releases/tag/3004.388.4_0-gnuton0_beta1
