### ISSUE TITLE
Link per il download del firmware (Gnuton) non corretto

### ISSUE THREAD

**Issue by BoostOver** [gnuton/asuswrt-merlin.ng#467]
**Router Model Affected**
Tutti

**Firmware Version Affected**
Tutti

**Is this bug present in upstream Merlin releases too?**
Non fa testo

**Describe the bug**
http://router.asus.com/Advanced_FirmwareUpgrade_Content.asp
Nell’ultima nota viene riportato il link (a mio avviso errato)….. https://www.asuswrt-merlin.net/download/

**Expected behavior**
Il link corretto dovrebbe essere:
https://github.com/gnuton/asuswrt-merlin.ng

**Comment by gnuton** [comment]
Su TUF UI, il check nn va devo controllarlo.

![image](https://github.com/gnuton/asuswrt-merlin.ng/assets/576580/8076036a-fb00-40b6-94ab-5313c1d4ad9d)

**Comment by BoostOver** [comment]
Si anche da me non funziona, ma non era questo quello che intendevo.
Sono le note al centro della pagina….mi sembra nota 4z

**Comment by mrbardman** [comment]
English? Please...

**Comment by BoostOver** [comment]
> English? Please...

How i can translate your English you can translate my language.
Don’t stop your brain.

**Comment by mrbardman** [comment]
Never mind.

**Comment by gnuton** [comment]
Fix ff803ceeabb4d74f8584ba7467da7b6e5ff90d60

**Comment by BoostOver** [comment]
![IMG_6423](https://github.com/gnuton/asuswrt-merlin.ng/assets/35013017/14d900e0-11f6-4e02-bdd4-7630ac928e30)
A mio parere la nota 4 non è corretta.
Se uno clicca si ritrova sulla pagina Merlin.

**Comment by gnuton** [comment]
![image](https://github.com/gnuton/asuswrt-merlin.ng/assets/576580/3b2cf4a0-60d3-4587-839c-060730cc1fdd)
fixed
