### ISSUE TITLE
kernel module ftdi_sio.ko

### ISSUE THREAD

**Issue by areqq** [gnuton/asuswrt-merlin.ng#482]
I need ftdi_sio.ko module for RT-AX82U

**Comment by gnuton** [comment]
would this be useful for others too?
if not you can build the firmare image by yourself of use circle ci for it.

**Comment by areqq** [comment]
I think so, it's a module that allows you to connect many popular USB devices, such as Smartcard readers or USB relay module.
The module is only  234KB.

**Comment by gnuton** [comment]
I cannot see this as a mainstream feature.
