### ISSUE TITLE
TUF-AX3000_3004_388.4_0-gnuton1_puresqubi.w - is incredibly unstable 

### ISSUE THREAD

**Issue by Ichimikichiki** [gnuton/asuswrt-merlin.ng#487]
**Router Model Affected**
TUF-AX3000 

**Firmware Version Affected**
3004_388.4_0-gnuton1_puresqubi

**Describe the bug**
Freezes for about 45 seconds out of every 90 seconds

Tried flashing 20 times. Tried flashing back 40 times, but can't get it to stay connected long enough to complete. I did a hard reset and was able to flash back to previous version and it worked fine. But just thought I'd try again, and same issue. Latest update is completely unusable. Takes no less than 50 refresh attempts to load each page. Same thing with ssh. Freezes and you have to make a new connection in a new terminal window. Over and over and over.

**Comment by gnuton** [comment]
Was the previous version working fine? I will check it

**Comment by gnuton** [comment]
Did you tested the latest beta too? Do you have the same issue?

**Comment by Ichimikichiki** [comment]
I did. And to a lesser extent. Only about 10% of the instability.

There are no logged events when this occurs.

**Comment by gnuton** [comment]
I am testing the _tuf image and so far so good. 
To test if it freezes I ssh on the router and ping www.google.it

**Comment by gnuton** [comment]
Tested a few hours.. not an issue with the _tuf image. I will test the non tuf one.

**Comment by gnuton** [comment]
@Ichimikichiki can you please define a test plan I can execute to assess the instability of this image?

**Comment by Ichimikichiki** [comment]
> I am testing the _tuf image and so far so good. To test if it freezes I ssh on the router and ping [www.google.it](http://www.google.it)

It even freezes while ssh'd into the router. I have to open a new session.

I'm looking for another router. I'm just gonna toss it.

**Comment by gnuton** [comment]
@Ichimikichiki the docker image works as I used it locally and on the cloud. 
The tuf image works to. I have to check the other one. 
The  problem happens on your router. so the question is.. what happens:?
the only thing to understand what's wrong is to check your logs.

**Comment by gnuton** [comment]
Get docker images already built with a docker pull. No reason to build your docker image unless you wanna develop the docker image. All docker and tug images are built on the cloud by circleci. If you fork the repo and enable circleci you do not need to setup anything on your local machine. No pain.

**Comment by Ichimikichiki** [comment]
So we can close this now.
