### ISSUE TITLE
TUF-AX3000 missing tabs on tuf fw

### ISSUE THREAD

**Issue by alfky12** [gnuton/asuswrt-merlin.ng#490]
**Router Model Affected**
TUF-AX3000

**Firmware Version Affected**
TUF-AX3000_3004_388.4_0-gnuton1_tuf_puresqubi

**Is this bug present in upstream Merlin releases too?**
Don't know

**Is this bug present in non-tuf release too?**
Neither I know

**Is this bug present in alpha/beta release too?**
I never try beta, just stable version.

**Describe the bug**
Missing tabs:
1. Traffic classification
2. VPN - Status
That's all I've found so far.
All the missing tabs can still be accessed via a direct link if you/browser still remember them.

**To Reproduce**
Traffic classification tab should be in the Adaptive QoS menu.
VPN - Status tab should be in the VPN menu.

**Expected behavior**
That tabs should be on their respective menus.

I didn't want to try on non-tuf fw because someone reported a very unstable system.
And oh, a little extra, the tools menu doesn't have a wrench icon.
Sorry for bad english, not my native language.

**Comment by gnuton** [comment]
this is a regression I will check and fix this.

**Comment by alfky12** [comment]
Or maybe, since this is just a webui, can you just make a temporary fix in the form of a tampermonkey userscript to add the missing icon and tabs?

**Comment by alfky12** [comment]
Sorry, I clicked the wrong button

**Comment by gnuton** [comment]
http://router.asus.com/Advanced_VPNStatus.asp
![image](https://github.com/gnuton/asuswrt-merlin.ng/assets/576580/ee70daa4-4828-4780-b8d2-eae1fe5f1854)
and 
http://router.asus.com/QoS_Stats.asp missing
![image](https://github.com/gnuton/asuswrt-merlin.ng/assets/576580/30533a25-f40e-4b66-b61b-0527cb8fa25a)

on TUF are
![image](https://github.com/gnuton/asuswrt-merlin.ng/assets/576580/33e98c1a-e30c-46e7-91ee-4b09b8921d62)

and
![image](https://github.com/gnuton/asuswrt-merlin.ng/assets/576580/3f047b4c-635d-4fd0-bb89-e134e8e439c9)

**Comment by gnuton** [comment]
fixed in f22f512d04

**Comment by gnuton** [comment]
test image https://app.circleci.com/pipelines/github/gnuton/asuswrt-merlin.ng/1684/workflows/d545468e-b410-4b15-932d-2e94dccb14b9
