### ISSUE TITLE
TUF AX6000 not supported

### ISSUE THREAD

**Issue by mohdforever** [gnuton/asuswrt-merlin.ng#492]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

please considering TUF AX6000 as a popular router that deserve supporting by this project.

thank you so much in advance

**Comment by gnuton** [comment]
Asus won't be able to provide a sample for this. So it won't be able to support it.
