### ISSUE TITLE
XT8:Only 3 of the 4 CPU cores show utilization.

### ISSUE THREAD

**Issue by robbbaxley** [gnuton/asuswrt-merlin.ng#494]
**Router Model Affected**
Asus XT8 v1

**Firmware Version Affected**
RT-AX95Q_3004_388.4_0-gnuton1

**Is this bug present in upstream Merlin releases too?**
No

**Describe the bug**
Only 3 of the 4 CPU cores show utilization. 

**To Reproduce**
1. Install firmware version: RT-AX95Q_3004_388.4_0-gnuton1
2. Click on Network Map > Status (Tab under system status)
3. View Processor utilization graph
4. See error: Core 1, 2, and 3 show utilization. Core 4 does not. Utilizing Asus firmware, all 4 cores show utilization. Also, the 3 cores are working much harder than I am used to seeing.

**Expected behavior**
All 4 cores to be utilized

**Screenshots**
![Web capture_13-11-2023_214930_10 0 1 200](https://github.com/gnuton/asuswrt-merlin.ng/assets/150712747/8e3c4882-8422-4810-9558-72fb22d583ba)

**Comment by gnuton** [comment]
Thanks for reporting this may be a regression. I will look at it.

**Comment by robbbaxley** [comment]
I don't know if this makes any difference, but I have 5 routers in AP-only mode, all hardwired to the switch. This is a mix of 3 XT8's and 2 XT9's.

**Comment by gnuton** [comment]
I do not recall if this was a visualization issue or just the way the cores are scheduled for this hardware.
I will check and get back.
In any case I won't be worried too much, because if it's a visualization bu it will be fxed. if this is the standard way for this router to work.. then it's by design.

**Comment by robbbaxley** [comment]
If you wish, I can put the original Asus firmware back on the hardware and take screenshots or a short video of all 4 cores being utilized. Since I am only using these as AP's I am not noticing any throughput issues and no user has complained. 

I am also able to assist you in tracking down the issue if you want. I am a hardware guy, and don't know software very well but I am happy to help!

**Comment by gnuton** [comment]
I think the CPU usage widget is not in the stock firmware. 
If there is a problem is a visualization problem if you ssh into the router and you install enteware you should be able to check the cpu usage with htop command

**Comment by gnuton** [comment]
I have not investigated this yet, but I have noticed TUF-AX3000 has same issue.
The last bar doesn't show any activity sign.
BTW http://router.asus.com/Tools_Sysinfo.asp has "CPU Load Average (1, 5, 15 mins)" which shows the average usage and at least on TUF the last core average is not 0

**Comment by robbbaxley** [comment]
gnuton, the CPU widget is in the stock Asus firmware. Would you like me to reload it on one of my AP's and screenshot it for you?

**Comment by gnuton** [comment]
This doesn't seem to be an issue.
if you like to get confirmation feel free to check the stock firmware too.
I will close the ticket. 
https://www.snbforums.com/threads/ax56u-386-1-cpu-core-4-not-being-used.70017/

I will reopen if the issue if confirmed, but for not it's not
