### ISSUE TITLE
Strange CPU behavior

### ISSUE THREAD

**Issue by Barmagler** [gnuton/asuswrt-merlin.ng#505]
**Router Model Affected**
Models: TUF-AX5400

**Firmware Version Affected**
3004.388.5_0-gnuton0_beta1, 3004.388.4_0-gnuton1

**Is this bug present in upstream Merlin releases too?**
No

**Describe the bug**
There is very strange situation.
I had stable version 388.2_2_0-gnuton1 but today suddenly updated to 3004.388.5_0-gnuton0_beta1.
After reboot noticed that CPU1 and CPU2 make spikes to 25-35% with no traffic at all.
Ok, I made update to stable version, 3004.388.4_0-gnuton1 but situation still same.

I belive than I was at 388.2_2_0-gnuton1 it was 5% CPU maximum.

**To Reproduce**
1. Go to 'Network map'
2. Click on 'System status -> Status'
3. Watch CPU graphic

**Expected behavior**
I really don't understand: there is problem with my router or 388.2_2_0-gnuton1 has problem with CPU graphic?

**Screenshots**
![Screenshot_64](https://github.com/gnuton/asuswrt-merlin.ng/assets/67556236/4d502f5c-f620-4acb-a36a-f213df5f7e76)

**Comment by gnuton** [comment]
can you install htop and report back the processes causing these spikes?

**Comment by Barmagler** [comment]
Gotcha!
/usr/sbin/awsiot

![Screenshot_67](https://github.com/gnuton/asuswrt-merlin.ng/assets/67556236/67c4fb54-9924-46ae-ac2b-8e4a1267f8f3)

**Comment by Barmagler** [comment]
Actually it's much more better now.
My bad, I really forgot make reset.

Now only two processes make 5-7% - networkmap and cfg_server

![Screenshot_69](https://github.com/gnuton/asuswrt-merlin.ng/assets/67556236/5f948b03-0135-495a-be21-d6883ea5bffc)
