### ISSUE TITLE
Broken layout in Adeptive QoS page - TUF-AX3000 3004.388.5_0-gnuton0_beta1

### ISSUE THREAD

**Issue by qqw1231** [gnuton/asuswrt-merlin.ng#507]
![IMG_20231213_163750](https://github.com/gnuton/asuswrt-merlin.ng/assets/110271812/f5a2a085-fb5c-4c77-a94b-30da210c1705)

Up and down not centered
![Image_1702456557647](https://github.com/gnuton/asuswrt-merlin.ng/assets/110271812/0f9974cd-be08-44f5-8a0a-e9b96bd35071)

**Comment by 572289049** [comment]
版本号是？如果你不喜欢，可以使用TUF的皮肤版本。

**Comment by qqw1231** [comment]
> 版本号是？如果你不喜欢，可以使用TUF的皮肤版本。

3004.388.5_0-gnuton0_beta1

**Comment by gnuton** [comment]
@qqw1231 do you get the same issue changing the language to english?

**Comment by micron888** [comment]
TUF-AX5400 ok with both english and chinese
![image](https://github.com/gnuton/asuswrt-merlin.ng/assets/59114523/1870bf0d-9e7b-4daf-a629-caf9b3eeadaa)
![image](https://github.com/gnuton/asuswrt-merlin.ng/assets/59114523/eee24e37-dab5-45e4-94d9-65998db265e7)

**Comment by qqw1231** [comment]
> TUF-AX5400中英文都可以 ![image](https://private-user-images.githubusercontent.com/59114523/290975293-1870bf0d-9e7b-4daf-a629-caf9b3eeadaa.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDI3MTc2MTUsIm5iZiI6MTcwMjcxNzMxNSwicGF0aCI6Ii81OTExNDUyMy8yOTA5NzUyOTMtMTg3MGJmMGQtOWU3Yi00ZGFmLWE2MjktY2FmOWIzZWVhZGFhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMTYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjE2VDA5MDE1NVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTA5NGM5MTUwYzY0ZTc5Yjg1ZTViN2U4MzQxZjVjYTg3ZDNkNTk0NTZmOTM1YTY2NDFkMmIwYTZkMmQxMTg0MWUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.qLCvhpV5-V3HwUCOiJDwJCcr-S_8xrNoxVwqZSpOEys) ![image](https://private-user-images.githubusercontent.com/59114523/290975300-eee24e37-dab5-45e4-94d9-65998db265e7.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDI3MTc2MTUsIm5iZiI6MTcwMjcxNzMxNSwicGF0aCI6Ii81OTExNDUyMy8yOTA5NzUzMDAtZWVlMjRlMzctZGFiNS00NWU0LTk0ZDktNjU5OThkYjI2NWU3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMTYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjE2VDA5MDE1NVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWVkM2E5NzAxZGM4Yzc1MmQwYzliMTEyZWFhNjg4ZjZmOGI4OGZkMjVlMDI4ZWJhOGMzYjYyYzE3NzA4ODFhM2ImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.t-6EUl3qeQLq47-Ev8xtAu_Aj1AnCu5VQnms8g0jNvY)

Please provide a complete picture and let me see where there are spaces in Tufax 3000.

**Comment by qqw1231** [comment]
> TUF-AX5400 ok with both english and chinese ![image](https://private-user-images.githubusercontent.com/59114523/290975293-1870bf0d-9e7b-4daf-a629-caf9b3eeadaa.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDI3MTc5MDIsIm5iZiI6MTcwMjcxNzYwMiwicGF0aCI6Ii81OTExNDUyMy8yOTA5NzUyOTMtMTg3MGJmMGQtOWU3Yi00ZGFmLWE2MjktY2FmOWIzZWVhZGFhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMTYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjE2VDA5MDY0MlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTczNjNkNDI2YzRlZmFlOTRhOTI5MjY2ZGZlZTJiZTk3MGRiMjIzNTMyNmYyNTEzY2MxMDRkNzdkMzM2ZWRmNTEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.GZ2636gSCy0c7kBxd8QBKIzq8uiwfOs7tZ_1_8EZGyM) ![image](https://private-user-images.githubusercontent.com/59114523/290975300-eee24e37-dab5-45e4-94d9-65998db265e7.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDI3MTc5MDIsIm5iZiI6MTcwMjcxNzYwMiwicGF0aCI6Ii81OTExNDUyMy8yOTA5NzUzMDAtZWVlMjRlMzctZGFiNS00NWU0LTk0ZDktNjU5OThkYjI2NWU3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMTYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjE2VDA5MDY0MlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTNmNTc4MDI2Y2IyMDM1N2I1NmIzMjAxZmUzODY3NGQ4YWMwNDg1ZWY5NjdmZWNkZjJmYzM3ZWY3OWRmZjk1ZWUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.F_FD5nhdXxrUWcRzIcjSciZxS23Xd95ZTH2f4kGjuL0)

Where is a large space in the first picture, I marked it with a circle.

**Comment by qqw1231** [comment]
> @qqw1231你会遇到同样的问题吗？

The circle I drew means there is a lot of emptiness

**Comment by micron888** [comment]
35devices connected :D no emptiness
![image](https://github.com/gnuton/asuswrt-merlin.ng/assets/59114523/962e3fe1-5eef-4d22-ad14-5c0f4965f4be)

**Comment by gnuton** [comment]
I cannot reproduce it. Can you test this in an incognito browser?

**Comment by tony8077616** [comment]
@gnuton I also have the same problem with the layout doesn't with enough space to show
Use with 3004.388.5_0-gnuton0_beta1

Microsoft Edge 120.0.2210.91
![image](https://github.com/gnuton/asuswrt-merlin.ng/assets/9822340/51e78db5-0b91-487a-bead-79e6075ecb7b)
![image](https://github.com/gnuton/asuswrt-merlin.ng/assets/9822340/b9bac84d-9a89-4599-91a2-c9c45fccde55)

Same with Google Chrome canary 122.0.6203.0
![image](https://github.com/gnuton/asuswrt-merlin.ng/assets/9822340/855caded-bf8b-4061-89a2-1916796759f6)
![image](https://github.com/gnuton/asuswrt-merlin.ng/assets/9822340/a851ff32-db86-425c-81ca-d145f3cdbc4a)

**Comment by swwwong** [comment]
@tony8077616 

This UI  ''BUG'' also same in the asuswrt factory software.

**Comment by tony8077616** [comment]
> @tony8077616 
> 
> This UI  ''BUG'' is same in the asuswrt factory software,it have a fix UI size

Got it, Thanks.

**Comment by gnuton** [comment]
fix 2588d458b97d21e4900f7f5f8d50a3127916f9ee
