### ISSUE TITLE
DSL-AC68U

### ISSUE THREAD

**Issue by NoRRt** [gnuton/asuswrt-merlin.ng#515]
Hello brother - you program to update DSL-AC68U model
you have? It has been a long time since the pre version

[Unstable: 3004.388.4_0-gnuton0_beta1](https://github.com/gnuton/asuswrt-merlin.ng/releases/tag/3004.388.4_0-gnuton0_beta1) Pre-release

**Comment by gnuton** [comment]
Please do not open tickets for questions. Use the chat. The DSL-AC68U is reaching its end of life and it s in maintenance mode stuck on the 386. The latest one is 386 10.
