### ISSUE TITLE
🙏 Please Add 464XLAT (CLAT) support

### ISSUE THREAD

**Issue by vihatsoft** [gnuton/asuswrt-merlin.ng#525]
**Is your feature request related to a problem? Please describe.**
Recently i changed my ISP to ipv6 only internet provider. My current ISP is Jio 5G (india). Jio is ipv6 only internet provider. like T-mobile. all major domain work fine. but, can't reach to 1.1.1.1, 8.8.8.8 or any ipv4 address. 
I use 5G CPE with asus router. 

**Describe the solution you'd like**
After search on google. and i find router need 464XLAT (CLAT) support. When try openwrt with 464XLAT (CLAT) then successfully reach 1.1.1.1. i install merlin firmware to my GT-AX11000 and TUF-AX5400 routers. but currently not support 464XLAT (CLAT).

**Additional context**
I have spend too much money on router GT-AX11000 and TUF-AX5400. But unfortunately not support 464XLAT (CLAT). Jio is biggest Tier 1 ISP in india with 426.2 million users. 

Many user having this problem. So, i request to you **please add 464XLAT (CLAT) support for GT-AX11000**. 

With good hope. thank you,

**Comment by gnuton** [comment]
I do not support GT-AX11000.
Please refeer to https://www.asus.com/support/FAQ/113990 for configuring IPV6
