### ISSUE TITLE
ASUS DSL-AX82U AiCloud 2.0 - AiCloud Sync

### ISSUE THREAD

**Issue by SuperACc2024** [gnuton/asuswrt-merlin.ng#527]
Hi dear
AiCloud 2.0 - Can one drive(microsoft) and drive (gmail) add-ons be made in the AiCloud Sync section?

thanx 
Best regards

**Comment by gnuton** [comment]
Hi @SuperACc2024 
Unfortunately AICloud is proprietary sofware and it belongs to ASUS.
You can see more info here https://www.snbforums.com/threads/aicloud-2-0-smart-sync-google-drive.44905/
