### ISSUE TITLE
Bug/Feature? USB not recognised by mesh router

### ISSUE THREAD

**Issue by johnmhedge** [gnuton/asuswrt-merlin.ng#528]
**Is your feature request related to a problem? Please describe.**
My brand new Sandisk not recognised

**Describe the solution you'd like**
I'd like to be able to use the Sandisk as a network repository

**Additional context**
ASUS RT-AX92U Mesh router

**Comment by gnuton** [comment]
Hi John,
if your USB drive is not recognized ther are different options.
There are very very few chance this is a softare issue.

If you can provide some logs we can see what's the problem. Usually if it's an external hard drive, you need to provide more power (eg using a powereed USB hub).

**Comment by johnmhedge** [comment]
Hi Antonio,
Thanks for the prompt response.
Maybe I'm showing my technology illiteracy. I'd just assumed plugging in a
USB stick was all that was required. They are certainly not powered.
Regards,
John
