### ISSUE TITLE
There are some issues with the ax3000 wan interface 388.6

### ISSUE THREAD

**Issue by ikunfans** [gnuton/asuswrt-merlin.ng#534]
lost some option
![1](https://github.com/gnuton/asuswrt-merlin.ng/assets/109742728/b7b5a801-37c7-4ff9-ac15-fe9b696dcd9f)

**Comment by neil1962** [comment]
Which option/s are missing?

**Comment by ikunfans** [comment]
> Which option/s are missing?

in picture,  its "wan type" and "801q".  and lost dot option. 
i also flash merlin interface fireware. i find some options is diferent with tuf .....

**Comment by gnuton** [comment]
fixed 70ae016468e57f2f7994029b69943172d7e9ada6
