### ISSUE TITLE
TUF-AX5400 banner display not centered in 388.6 Beta 2

### ISSUE THREAD

**Issue by Rovasteen** [gnuton/asuswrt-merlin.ng#538]
Minor fault.  Banner display formatting is not centered in Beta 2.

3004.388.6_0-gnuton0_beta1 displays correctly.

3004.388.6_0-gnuton0_beta2 banner is not displayed correctly.

![Banner](https://github.com/gnuton/asuswrt-merlin.ng/assets/80790409/1d308c51-ec78-47bc-affe-1989b2898f29)

**Comment by micron888** [comment]
TUF-AX5400. same issue

3004.388.6_0-gnuton0_beta1 displays correctly.
3004.388.6_0-gnuton0_beta2 banner is not displayed correctly.

**Comment by gnuton** [comment]
Thanks a lot for reporting I fixed the TUF. But it broke the default.:(

**Comment by Rovasteen** [comment]
OK I can man up and switch to the TUF.   :)  I think anyway that as you increase models supported you should only support TUF or default build but not both.   Thanks!

**Comment by gnuton** [comment]
duplicate https://github.com/gnuton/asuswrt-merlin.ng/issues/537
