### ISSUE TITLE
TUF-AX3000 firmware tuf UI version has UI bug

### ISSUE THREAD

**Issue by Jacky10X** [gnuton/asuswrt-merlin.ng#540]
It seems not only the stock one has the UI bug but also the TUF one has the UI bug too.

![image](https://github.com/gnuton/asuswrt-merlin.ng/assets/8656910/62270736-7739-4089-81d8-e4f6218b54a2)

**Comment by gnuton** [comment]
version?

**Comment by Jacky10X** [comment]
> version?
Sorry, forgot to mention it.
Version: 3004.388.6_0-gnuton0_beta2

**Comment by sojusnik** [comment]
Would it be possible to use the stock ASUS UI, or another more minimalistic UI, instead of the gamer UI that the TUF-AX3000 V2 has as default, with the official release of the merlin firmware for his router?

**Comment by gnuton** [comment]
This was fixed
