### ISSUE TITLE
AX-86U Wİ-Fİ 

### ISSUE THREAD

**Issue by cemburakengin** [gnuton/asuswrt-merlin.ng#557]
Models: RT-AX86U

Hello,

When using the factory firmware on my RT-AX86U device, I can comfortably join online meetings from any room in my house. However, when using the Merlin Firmware, I encounter issues during online meetings such as echoing of my voice or intermittent disruptions in audio quality with sounds getting mixed up. I have experienced this issue across all Merlin versions. Is there a solution we can come up with for this?

Thank you,
Regards,

**Comment by gnuton** [comment]
AX86U is not supported.
