### ISSUE TITLE
Bring back (?) WiFi radar on unsupported routers (RT-AX82U V1)

### ISSUE THREAD

**Issue by F640** [gnuton/asuswrt-merlin.ng#558]
**Is your feature request related to a problem? Please describe.**
I had been able to use WiFi Radar feature in my router (RT-AX82U v1), but in the most recent firmware update this feature seems to be missing.

**Describe the solution you'd like**
Bring back WiFi radar feature if it's possible.

**Describe alternatives you've considered**
none

**Additional context**
I know this feature is unsupported in this router, but i still want it back.

**Comment by gnuton** [comment]
version of the firmware?

**Comment by F640** [comment]
I don't remember it, but last time i used this feature around 388.2 version, probably. Just wanted to revisit this feature 2 days ago and that feature has gone.

**Comment by gnuton** [comment]
I meant what's the version of the firmware you have now tested that doesn't have this feature?

**Comment by F640** [comment]
Sorry about that, here it is: 3004.388.6-gnuton1

**Comment by gnuton** [comment]
Wifi Radar has been removed from all builds because it was unmaintained by broadcom.
