### ISSUE TITLE
Skynet not working on TUF-AX3000 V2/ RT-AX58U_V2

### ISSUE THREAD

**Issue by gnuton** [gnuton/asuswrt-merlin.ng#559]
![image](https://github.com/gnuton/asuswrt-merlin.ng/assets/576580/6f287921-3a27-4e55-9716-ea5789bf9806)
Skynet not able to run on TUF-AX3000_V2

**Comment by gnuton** [comment]
Linked to https://github.com/gnuton/asuswrt-merlin.ng/issues/123

**Comment by gnuton** [comment]
Linux kernel configs 

release/src-rt-5.04axhnd.675x/kernel/linux-4.19/config_base.6a.62118G:# CONFIG_IP_SET is not set
release/src-rt-5.04axhnd.675x/kernel/linux-4.19/config_base.6a.6750:# CONFIG_IP_SET is not set <--- THIS
release/src-rt-5.04axhnd.675x/kernel/linux-4.19/config_base.6a.4912:# CONFIG_IP_SET is not set
release/src-rt-5.04axhnd.675x/kernel/linux-4.19/config_base.6a.6756:# CONFIG_IP_SET is not set
release/src-rt-5.04axhnd.675x/kernel/linux-4.19/config_base.6a.47622:# CONFIG_IP_SET is not set
release/src-rt-5.04axhnd.675x/kernel/linux-4.19/config_base.6a.6855:# CONFIG_IP_SET is not set
release/src-rt-5.04axhnd.675x/kernel/linux-4.19/config_base.6a.6756_nowl:# CONFIG_IP_SET is not set

**Comment by gnuton** [comment]
Test images
https://github.com/gnuton/asuswrt-merlin.ng/actions/runs/8412377915
Note the link works only if logged in github

**Comment by l0r3n75** [comment]
Same bug still occuring

**Comment by gnuton** [comment]
new test images here
https://github.com/gnuton/asuswrt-merlin.ng/actions/runs/8478486819

**Comment by l0r3n75** [comment]
Experiencing some weird errors still can't start skynet
![Uploading image.png…]()

**Comment by gnuton** [comment]
@l0r3n75 cannot see the image. please come with logs

**Comment by gnuton** [comment]
@l0r3n75 any update?

**Comment by l0r3n75** [comment]
I couldn't get it working

**Comment by blooddrunk99** [comment]
I am having a similar issue on rt- ax58v2. I would be happy to provide log, I am unaware how to get log.

**Comment by chaosmaou** [comment]
Same issue on the RT-AX3000 V2, which uses the RT-AX58U_V2 firmware. Happens in the latest stable 3004_388.6_2-gnuton1. Fairly sure it's the exact same issue as this, hence I didn't post a duplicate.

**Comment by Adamm00** [comment]
This is also the case for the GT-BE98 (src-rt-5.04axhnd.675x)

**Comment by novusB** [comment]
Same issue confirmed. I don't have the TUF but I do have the V2 version.

_____________________________________________

 Skynet install aborted,
 IPSet extension not supported, please
 update router to latest Firmware version.
_____________________________________________

 Enter amtm option  i
 amtm 4.8 FW               by thelonelycoder

 ASUS RT-AX3000 HW: armv7l Kernel: 4.19.183
 FW: 3004.388.6_2-gnu..

**Comment by gnuton** [comment]
Please check these test images and let me know if it owrks now https://github.com/gnuton/asuswrt-merlin.ng/actions/runs/9434553478

**Comment by gnuton** [comment]
Fixed works
![image](https://github.com/gnuton/asuswrt-merlin.ng/assets/576580/f499d34d-a8bc-401b-979f-9519b97bf340)

**Comment by gnuton** [comment]
The fix will be part of the next release or please check the images above
