### ISSUE TITLE
lower NVRAM usage

### ISSUE THREAD

**Issue by rochmind** [gnuton/asuswrt-merlin.ng#565]
**Is your feature request related to a problem? Please describe.**
Updating from 388.4 to 388.6, noticed avg 20% increase in RAM (67% avg to 89%). I have tried to reboot and clear some settings but not sure if this is related to the version update. I have added a mid-week reboot in the schedule added instead of just the one on weekend.

**Describe the solution you'd like**
A recommendation for optimum/lean settings - I have upgraded to RT-AX92U due to warnings on nvram usage from the RT-AC68U and I am concerned this may go down the same path. (still use it as aimesh node in the garage/shed with only 2 clients at most. Our household avg about ~28 devices connected at any point in time during the day. 

**Describe alternatives you've considered**
Downgrading back to 388.4 but that would have to wait until another time to do just in case have to do a reset

**Additional context**
Some unused features/settings may take some memory like qos, vpn, etc. so that may lower usage

**Comment by Katana1074** [comment]
Hi there...

Asuswrt is designed to use up to 97% of available memory, RT-AC68U is now end of life....

Post on smallnetbuilder, you will receive more support there,

Dirty flashing from 388.4 to 388.6 firmware could produce a lot of the issues you have,

Search for Nuclear reset https://www.snbforums.com/threads/major-issues-w-rt-ac86u.56342/page-4#post-495710

Regards
