### ISSUE TITLE
Title problem

### ISSUE THREAD

**Issue by qqw1231** [gnuton/asuswrt-merlin.ng#566]
![Screenshot_2024-03-31-17-05-53-711_com android browser-edit](https://github.com/gnuton/asuswrt-merlin.ng/assets/110271812/05c83db6-9634-4f50-998d-e10148ac9023)

**Comment by qqw1231** [comment]
0----1

**Comment by gnuton** [comment]
Thanks I see the problem! good catch

**Comment by gnuton** [comment]
Fixed 3fa535489a8dcc11cc7951a3fe2e05e2d8f44cc6
