### ISSUE TITLE
Traffic Analyzer - Statistic data not showing

### ISSUE THREAD

**Issue by vihatsoft** [gnuton/asuswrt-merlin.ng#568]
**Router Model Affected**
Models: GT-AX11000

**Firmware Version Affected**
3004.388.6_2

**Describe the bug**
Traffic Analyzer - Statistic data not showing after update. All clients traffic and user traffic always show zero.  after downgrade to 3004.388.6 start working fine.

**Comment by Katana1074** [comment]
Hi There.....

GT-AX11000 is not supported by Gnuton here....

Please use the following forum link on smallnetbuilder for support

https://www.snbforums.com/threads/asuswrt-merlin-3004-388-6-is-now-available.88559/

Regards

**Comment by gnuton** [comment]
@RMerl FYI
