### ISSUE TITLE
TUF AX5400 Redirect webui

### ISSUE THREAD

**Issue by doggi87** [gnuton/asuswrt-merlin.ng#573]
**Router Model Affected**
Models: TUF AX5400

**Firmware Version Affected**
3004.388.6_0-gnuton1 and 3004.388.6_2-gnuton1

**Is this bug present in upstream Merlin releases too?**
Don't know

**Describe the bug**
Redirect webui access to www.asusrouter.com under Administration -> System is broken again. 
Redirect worked on version: 3004.388.5_0-gnuton1

**To Reproduce**
1. Go to Administration 
2. Click on System 
3. Scroll down to Redirect webui access to www.asusrouter.com
4. Doesn't work if you change to yes or no

**Comment by gnuton** [comment]
Hi @doggi87
Can you please link the bug where this was fixed?

**Comment by doggi87** [comment]
Hi,

It was fixed in

https://github.com/gnuton/asuswrt-merlin.ng/releases/tag/3004.388.5_0-gnuton1

Regards.

Den tors 25 apr. 2024 09:27Antonio Aloisio ***@***.***> skrev:

**Comment by doggi87** [comment]
Awesome, thanks for the update!

Den sön 5 maj 2024 09:18Antonio Aloisio ***@***.***> skrev:
