### ISSUE TITLE
TUF AX5400 - Logout button not aligned

### ISSUE THREAD

**Issue by doggi87** [gnuton/asuswrt-merlin.ng#575]
Router Model Affected
Models: TUF AX5400

Firmware Version Affected
3004.388.6_0-gnuton1 and 3004.388.6_2-gnuton1

Is this bug present in upstream Merlin releases too?
Don't know

**Describe the bug**
The button for Logout is not centered and if you see the picture you can click on the red marked dot and not on the text. Text should be centered.

**Screenshots**
If applicable, add screenshots to help explain your problem or remove this section
![Alignment for Logout is bad](https://github.com/gnuton/asuswrt-merlin.ng/assets/96024500/8c7e5569-1c62-4c8e-bf8b-f4350ce23e9f)

**Comment by gnuton** [comment]
do you see the same issue if you browse it in incognito mode?

**Comment by gnuton** [comment]
Fix 1
file:///home/aaloisio/Pictures/Screenshots/Screenshot%20from%202024-04-25%2023-55-29.png

**Comment by gnuton** [comment]
Fix 2
![image](https://github.com/gnuton/asuswrt-merlin.ng/assets/576580/b2ffd3f8-dbd8-4bea-942e-adb360e5a763)

**Comment by gnuton** [comment]
commit 0f811d381e7c82a756c74522a2a01c54b6575943

**Comment by gnuton** [comment]
Fix b27fcb6a3026293709bba98807a8dda1b3d2638e

**Comment by gnuton** [comment]
merged to master
