### ISSUE TITLE
ipv6 leaks

### ISSUE THREAD

**Issue by nithingowda** [gnuton/asuswrt-merlin.ng#582]
If we turn on VPN fusion, IPv6 still leaks. Add a feature to disable IPv6 on when VPN fusion is enabled.

**Comment by gnuton** [comment]
ipv6 fusion is not supported by merlin

**Comment by alfky12** [comment]
I think s/he means VPN Director. And yes, ipv6 leaks. I use wireguard.
tuf-ax3000 v1 here with 3004.388.6_2-gnuton1_tuf firmware.
@gnuton
