### ISSUE TITLE
3004.388.7_1-gnuton0_beta1 Two questions.

### ISSUE THREAD

**Issue by qqw1231** [gnuton/asuswrt-merlin.ng#588]

**Comment by qqw1231** [comment]
![Screenshot_2024-05-10-22-27-05-792_com android browser-edit](https://github.com/gnuton/asuswrt-merlin.ng/assets/110271812/67b92350-fdfa-44ac-9f44-bd60d954952a)
![Image_1715351641158](https://github.com/gnuton/asuswrt-merlin.ng/assets/110271812/49aa3b10-297a-4e41-a9e4-0095309251dc)

**Comment by qqw1231** [comment]
Figure 1 Login and password account login are not the same length.

Figure 2: The frame does not leave a gray low color.

**Comment by qqw1231** [comment]
Figure 1 is the mobile phone login.

**Comment by gnuton** [comment]
The login button is correct. This is the layout
![image](https://github.com/gnuton/asuswrt-merlin.ng/assets/576580/15004122-2c5d-4f72-8012-1b278478eda1)

**Comment by gnuton** [comment]
Also the open NAT colors are intented to be like that.. 
The features comes from ROG and AFAIK the intention was to keep show it.
