### ISSUE TITLE
Asus RT-AX82U V2 no update with new gnuton firmware

### ISSUE THREAD

**Issue by Raul-Flores** [gnuton/asuswrt-merlin.ng#590]
**Router Model Affected**
Models: AX82U V2

**Firmware Version Affected**
Versión de firmware:[3.0.0.4.388_24232]
new version i try to install RT-AX82U_V2_3004_388.6_2-gnuton1_nand_squashfs.pkgtb

**Is this bug present in upstream Merlin releases too?**
No

**Describe the bug**
I want to update my Asus AX82U router. When I upload the image correctly, even the progress bar appears indicating that it's updating, but at the end of the process, it restarts without loading the new Asus image with Merlin. I'm not sure what could be happening, as it doesn't give me an error; it simply doesn't load the image. Regards.

**To Reproduce**
1. Go to system
2. upgrade new image
3. waith
4. no update

**Expected behavior**
asus AX82U with new image merlin

**Screenshots**
no image, only the router no update with this new firmware, not reason.

**Comment by BoostOver** [comment]
Same on dsl ax82u

**Comment by huwu2705** [comment]
The bug is known, try 388.7_1 beta

[https://github.com/gnuton/asuswrt-merlin.ng/issues/577](url)
