### ISSUE TITLE
3004.388.7_1-gnuton0_beta1 Skynet &QoSCake issues

### ISSUE THREAD

**Issue by Nullvoid3771** [gnuton/asuswrt-merlin.ng#596]
**Router Model Affected**
RT-AX58U v2 (CA) 

**Firmware Version Affected**
388.7_1

**Is this bug present in upstream Merlin releases too?**
No

**Describe the bug**

Skynet’s IPtables never load and fail. 

Cake QoS doesn’t seem to make any difference to bufferbloat despite the setting mirroring my main router.  

**Expected behavior**
A+ in bufferbloat score in Cake QoS 
Skynet iptables loaded so I can add my custom blocklist, but can’t because it fails to load up tables.

**Comment by gnuton** [comment]
duplicat of https://github.com/gnuton/asuswrt-merlin.ng/issues/559
