### ISSUE TITLE
TUF-AX3000 v2 WIFI hangs

### ISSUE THREAD

**Issue by Rovasteen** [gnuton/asuswrt-merlin.ng#597]
This is the 2nd time I have encountered this issue.  It appears to be with both 3004.388.6_2-gnuton1 and  3004.388.7_beta1.  After running the router for about a week, the WIFI just dies.  Attached are log files of what was happening when this occurred.

**Comment by CPngN** [comment]
To be fair, that seems to be the MO for the ET8's... 😕

**Comment by Rovasteen** [comment]
Have not observed this fault on release 3004.388.7_1-gnuton1 from date June 10, 2024 over an extended time period of 12 days so far.  Will reopen the fault if this happens again.
