### ISSUE TITLE
WireGuard not working?!

### ISSUE THREAD

**Issue by feiercrack** [gnuton/asuswrt-merlin.ng#598]
**Router Model Affected**
RT-AX82U v1

**Firmware Version Affected**
3004.388.6_2-gnuton1
**Is this bug present in upstream Merlin releases too?**
IDK

**Describe the bug**
after downloading an wg config from surfshark, my ip adress is not masked with ip from surfshark, after enabling wg client in the vpn section
i still have the ip from my isp - vodafone germany 

![80804b9dd8319b86080aa85dcff0f86e](https://github.com/gnuton/asuswrt-merlin.ng/assets/47046040/4f7ac3de-dfcf-4bbb-9d0c-b7ea40757461)

![9d15ed52129798edcd11bc6410490266](https://github.com/gnuton/asuswrt-merlin.ng/assets/47046040/ddff9aac-215a-48b8-aa27-52f1508a3f02)

it was working with original RT-AX82U_3.0.0.4_388_24232-gf74229b_puresqubi just before i upgrade it with your merlin

do i have to setup anything else? 
i might forgot something to set... Idk, this is my 1st encounter with merlin, so please tell me what to do. 
ty! cheers^^

**Comment by alfky12** [comment]
Add new rule in VPN Director tab.

**Comment by feiercrack** [comment]
> Add new rule in VPN Director tab.

wow, awesome. that worked^^

ty!

**Comment by alfky12** [comment]
If you use IPv6, check whether there is a leak or not.
