### ISSUE TITLE
[REQUEST] add minidlna opus patch

### ISSUE THREAD

**Issue by Keltere** [gnuton/asuswrt-merlin.ng#6]
Hi, i would suggest to add [this patch](https://sourceforge.net/p/minidlna/patches/170/) for minidlna to enable opus support.
[Here](https://github.com/RMerl/asuswrt-merlin/wiki/Applying-patches-to-source-files) there is an example how to apply the patch.

**Comment by gnuton** [comment]
Hi! 
I would prefer if these changes would come from upstream (merlin). If you get it merged there it will be available to DSL builds too.

**Comment by Keltere** [comment]
Nevermind, minidlna needs opus to be present otherwise it won't work.
