### ISSUE TITLE
DNS Filter missing DNSFilter.asp 404 error

### ISSUE THREAD

**Issue by novusB** [gnuton/asuswrt-merlin.ng#603]
**Router Model Affected**
Models: AX3000 V2 RT-AX58U_V2

**Firmware Version Affected**
3004.388.7_1-gnuton1

**Is this bug present in upstream Merlin releases too?**
Unknown

**Describe the bug**
Trying to install unbound addon, unbound sees that "DNSFilter" is disabled, directs user to "DNSFilter.asp" when trying to naviagate to DNSFilter, receiving 404 error.

**To Reproduce**
1. Go to https://routeraddress/DNSFilter.asp
2. See 404 error

**Expected behavior**
See the DNS Filter page, or ability to install unbound addon.

**Comment by Nullvoid3771** [comment]
Not a bug. I believe DNSfilter.asp was replaced with /DNSDirector.asp upstream from RMerlin.
