### ISSUE TITLE
Any way to increase 4tb limit?

### ISSUE THREAD

**Issue by ajalberd** [gnuton/asuswrt-merlin.ng#613]
**Is your feature request related to a problem? Please describe.**
I love the ability to make a SMB share on the router itself, however my14TB drive cannot mount, seems like a partition limit unfortunately

**Describe the solution you'd like**
Able to export the 14TB drive in router menu

**Describe alternatives you've considered**
n/a :(

**Additional context**
My filesystem has the same attributes of a 4tb one that I CAN mount, making this even stranger. 

`Filesystem features:      has_journal ext_attr resize_inode dir_index filetype extent 64bit flex_bg sparse_super large_file huge_file dir_nlink extra_isize metadata_csum`

![image](https://github.com/gnuton/asuswrt-merlin.ng/assets/20324292/6feca134-4977-42c1-b2cd-10fa29f7da15)
![image](https://github.com/gnuton/asuswrt-merlin.ng/assets/20324292/15df1b58-e089-4365-aa0e-79774b8d34d3)

**Comment by ajalberd** [comment]
Got it to work! I formatted using the router's `mke2fs -t ext4 -O ^has_journal /dev/sda1`

It now has these features:

`Filesystem features:      ext_attr resize_inode dir_index filetype extent flex_bg sparse_super large_file huge_file uninit_bg dir_nlink extra_isize`

**Comment by gnuton** [comment]
can this be closed?

**Comment by ajalberd** [comment]
> can this be closed?

Sure! I was curious if you had any insight on this one.

**Comment by gnuton** [comment]
You tried to mount an unsupported filesystem. What's that NTFS?
