### ISSUE TITLE
Dsl AX82U için CakeQos

### ISSUE THREAD

**Issue by SametKoyak** [gnuton/asuswrt-merlin.ng#618]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by Nullvoid3771** [comment]
Is this a request for cake on DSL-AX82U?

**Comment by gnuton** [comment]
please write in english

**Comment by SametKoyak** [comment]
So sorry I forgot to write in English. I need help with Cake Qos. I have AsusMerlin in DSL AX82U modem/router. But there is no Cake QosiPhone’umdan gönderildiAntonio Aloisio ***@***.***> şunları yazdı (2 Tem 2024 01:37):﻿
please write in english

**Comment by Nullvoid3771** [comment]
I would suggest you start a discussion at https://www.snbforums.com/ if it’s technical support you need. As it stands we don’t know what you require help with or if you’re experiencing a bug or a lack of a feature such as cake and are requesting cake be added. Apologies as I only speak English and your translation is in broken English.
