### ISSUE TITLE
Flag ATM non persiste

### ISSUE THREAD

**Issue by BoostOver** [gnuton/asuswrt-merlin.ng#62]
**Firmware Version Affected **
386.00-gnuton0_alpha8

Il flag ATM in http://192.168.1.1/QoS_EZQoS.asp non persiste dopo aver applicato/confermato il flag

**Comment by gnuton** [comment]
Confirmed. Bug is present on DSL-AX82U too

**Comment by gnuton** [comment]
It was an upstream issue this will be fixed once I merge the code from upstream
https://github.com/RMerl/asuswrt-merlin.ng/commit/50e97f1c8aa1f6a30113272f15ea24df7b6b9337

**Comment by gnuton** [comment]
This should be fixed in the latest alpha.

**Comment by gnuton** [comment]
is this confirmed?
