### ISSUE TITLE
VPN Server - Others's UI and VPN Client - PP2P/L2TP's UI are bugged

### ISSUE THREAD

**Issue by Jacky10X** [gnuton/asuswrt-merlin.ng#625]
**Router Model Affected**
Models: TUF-AX3000

**Firmware Version Affected**
3004.388.8_0-gnuton0_alpha1, 3004.388.7_1-gnuton1

**Is this bug present in upstream Merlin releases too?**
Unknown

**Describe the bug**
The VPN -- VPN Server -- Others UI is bugged. 
TUF theme and stock theme both have this issue.
Sometimes the UI is text only. Sometimes it is TUF UI. (Both Stock and TUF)

**To Reproduce**
1. Go to VPN
2. Click on VPN Server
3. Click on Others
4. UI is bugged.

**Expected behavior**
The UI should be normal

**Screenshots**

![螢幕擷取畫面 2024-07-08 205848](https://github.com/gnuton/asuswrt-merlin.ng/assets/8656910/66731149-951a-4ebf-bc2e-0251279200a2)

![螢幕擷取畫面 2024-07-08 212435](https://github.com/gnuton/asuswrt-merlin.ng/assets/8656910/b3b1aae2-99e7-4d49-a76d-76f57abb24fa)

**Comment by gnuton** [comment]
this problem is due to  your browser cache.

**Comment by Jacky10X** [comment]
@gnuton That is weird. I have cleaned the browser cache (edge) and the problem is persistent. I also install Firefox and the GUI is still bugged.

**Comment by gnuton** [comment]
I will give it a look. Is this happening only on that page?

**Comment by Jacky10X** [comment]
> I will give it a look. Is this happening only on that page?

Yes, only on that page.

**Comment by Jacky10X** [comment]
@gnuton 
Sorry to bother you 
I just found the VPN Client --> PP2P/L2TP also has a similar issue. (Stock Theme using TUF UI).

![image](https://github.com/user-attachments/assets/0ba37a6d-c78f-4f30-ac15-a99409ed36d0)

**Comment by gnuton** [comment]
Tested and it works for me. 
I cannot reproduce it.

**Comment by Jacky10X** [comment]
I guess it's my browser problem while I am using the TUF theme firmware. But the Stock Theme has some UI bugs. Such as using the TUF UI button. Maybe it is related to Stock firmware? By the way, thanks for checking it.

**Comment by gnuton** [comment]
I have closed this, but if you need more help feel free to keep wriiting here.
I can reopen it if we manage to understand if this can be reproduced. But as far as I see this is not a bug for now.
3004.388.7_1-gnuton1 is a stable release and no body has complained abou it either.. unlikely this is a problem of the firmware

If you browse tuf and not tuf UI with same browser the browser caches the CSS and this generates artifact as you have noticed (bad renders, wrong ui elements...)

TUF UI theme has some small bugs, but nothing major.
