### ISSUE TITLE
Temperature Menu disappeared after updating to 388.7_1  (RT-AX92U)

### ISSUE THREAD

**Issue by Vaiperu** [gnuton/asuswrt-merlin.ng#633]
**Router Model Affected**
RT-AX92U

**Firmware Version Affected**
388.7_1-gnuton1

**Is this bug present in upstream Merlin releases too?**
?

**Describe the bug**
The Temperature Menu disappeared after updating to 388.7_1

**To Reproduce**
1. Go to 'Administration'

**Expected behavior**
Temperature Tab is visible

**Screenshots**
If applicable, add screenshots to help explain your problem or remove this section
![image](https://github.com/user-attachments/assets/59f376ee-e2a8-4030-aec7-e6057b3bc02d)

**Comment by gnuton** [comment]
The temperature should be now in http://router.asus.com/Tools_Sysinfo.asp

**Comment by Vaiperu** [comment]
Thanks!
