### ISSUE TITLE
WiFi Network list and active clients are not correctly displayed on sysinfo page on GT-BE98

### ISSUE THREAD

**Issue by mattheweli** [gnuton/asuswrt-merlin.ng#635]
**Router Model Affected**
Models: GT-BE98

**Firmware Version Affected**
3006.102.1_1-gnuton0_beta1

**Is this bug present in upstream Merlin releases too?**
Probably not

**Describe the bug**
In the sysinfo page on Tools section the WiFi Network are listed. I disabled 5GHz-2 WiFi network, but it's marked as active with client connected. In the reality the client is connected to 6GHz network. I suspect this is due to the different WiFi architecture of the GT-BE98Pro

**To Reproduce**
1. Go to Tools section
2. Click on sysinfo
3. Scroll down to Network

**Expected behavior**
The active WiFi network should be listed correctly

**Screenshots**
![Screenshot 2024-07-18 152830](https://github.com/user-attachments/assets/7423873d-c1c9-4ee0-a35a-f708895049c2)

**Comment by mattheweli** [comment]
I added a pull request for this:

![image](https://github.com/user-attachments/assets/82df7bd8-1c7c-417e-8095-2e3db5184fcc)

**Comment by gnuton** [comment]
I merged tthe pull request! thanks @mattheweli !

**Comment by gnuton** [comment]
tested te latest build and this was fixed
