### ISSUE TITLE
DNS Director Web page crashes when adding a new entry on GT-BE98

### ISSUE THREAD

**Issue by mattheweli** [gnuton/asuswrt-merlin.ng#636]
**Router Model Affected**
Models: GT-BE98

**Firmware Version Affected**
3006.102.1_1-gnuton0_beta1

**Is this bug present in upstream Merlin releases too?**
No, it's fixed in 3e36b02 (also for TOR page)

**Describe the bug**
In DNS Director web page on LAN section, when you try to add any new entry, the web page crashes because of the wrong syntax of some vars/methods (pls, see commit 3e36b02 in Merlin upostream for details)

**To Reproduce**
1. Go to LAN Section
2. Click on DNS Director
3. Try to add any new entry and click on apply

**Expected behavior**
The DNS Director web page should not crash when a new entry is added

**Comment by gnuton** [comment]
merged 3e36b02 to master.

**Comment by gnuton** [comment]
tested no console errors
