### ISSUE TITLE
Asus AX58U v2 possible sollution?

### ISSUE THREAD

**Issue by iLLiac4** [gnuton/asuswrt-merlin.ng#644]
Hi. Does someone has any advice how can I and if it is worth at all to try to solve it.
I have got few  AX58U v2 routers that when power is connected the lights blinks and then only power led is turned on. There is no reaction press and holding WPS button so no reset to default and pressing/holding  reset does not activate  recovery console.

Is there any hope or should I just bin them? Is this a hardware issue or. is it software issue if someone hay any experience?

Thank you and have a nice day.

**Comment by gnuton** [comment]
Dear @iLLiac4  this issues are supposed to be opened for firmare issues and they distract me from deliver the firmware.
If you use the chat or also chatgpt you can get simple answers to your questions.
Try to recover the firmware unlikely problem is hardware. Just try multiple options several times.
This is one.
https://www.asus.com/support/faq/1000814/

I won't reply to issues for support like this. please use the forum or the chat.
