### ISSUE TITLE
Wireless setting "Apply" button does not work in Access point mode

### ISSUE THREAD

**Issue by ttickell** [gnuton/asuswrt-merlin.ng#647]
**Router Model Affected**
ZenWifi XT8 / RT-AX95Q

**Firmware Version Affected**
RT-AX95Q_3004_388.7_1-gnuton1_puresqubi.w

**Is this bug present in upstream Merlin releases too?**
No - fully functional on RC-AC86U running 386.14

**Describe the bug**
Wireless settings cannot be changed in the GUI.  Apply button doesn't work on pages:
/Advanced_Wireless_Content.asp - main or professional tabs
/index.asp - wireless tab of system status

**To Reproduce**
Go to above mention pages, try to change any wireless setting, hit Apply - nothing happens.

**Expected behavior**
The apply button should take action save/apply/reload etc.

**Screenshots**
Screenshots won't show this - can provide a screen capture video?

**Comment by ttickell** [comment]
Screen recording of behavior in both Safari and Firefox - terrible quality to meet upload size limitation.

**Comment by gnuton** [comment]
This happens in access point mode,
it's a known issue

**Comment by gnuton** [comment]
This issue will be fixed as part of https://github.com/gnuton/asuswrt-merlin.ng/issues/542
