### ISSUE TITLE
Bug Report ASUS

### ISSUE THREAD

**Issue by BoostOver** [gnuton/asuswrt-merlin.ng#65]
**Firmware Version Affected **
386.00-gnuton0_alpha8

Appare il fumetto che avvisa di riportare bug direttamente ad ASUS linka alla pagina http://192.168.1.1/Advanced_Feedback.asp inesistente.

**Comment by BoostOver** [comment]
Il problema rimane in alpha9

**Comment by gnuton** [comment]
![image](https://user-images.githubusercontent.com/576580/105648674-f99af500-5eac-11eb-9bc0-3c770cba0c39.png)

**Comment by gnuton** [comment]
Dev notes:
- String is defined in ASUSGATE_note7
- code asuswrt-merlin.ng/release/src-rt/router/www/notification.js
- clicking feedback trigges the action setTimeout('document.noti_experience_Feedback.submit();'
- the form  is defined here
  state.js:	banner_code +='<form method="post" name="noti_experience_Feedback" action="/start_apply.htm" target="hidden_frame">\n';
- The code which redirect to missing(?) page is  document.noti_experience_Feedback.submit() (which is defined above).
  That function is defined as follow:  redirectFeedback:function(){location.href = 'Advanced_Feedback.asp';},

**Comment by gnuton** [comment]
![image](https://user-images.githubusercontent.com/576580/107161186-57463b80-699b-11eb-8bb2-dec86d7c65c4.png)

**Comment by gnuton** [comment]
I believe this issue will go away once we switch off FRS_FEEDBACK=y flat in target.mak.
https://github.com/gnuton/asuswrt-merlin.ng/blob/DEV_master/release/src-rt/target.mak#L11
Unfortuntely the there are some linker issue that prevent us to easily switch if off and some fixes in the makefiles are needed for this to happen

**Comment by gnuton** [comment]
Fixed in Beta4
