### ISSUE TITLE
Can't install TUF-AX3000 V2 firmwares

### ISSUE THREAD

**Issue by sojusnik** [gnuton/asuswrt-merlin.ng#664]
**Router Model Affected**
TUF-AX3000 V2

**Firmware Version Affected**
all versions

**Is this bug present in upstream Merlin releases too?**
can't check, because Merlin doesn't support TUF-AX3000 V2

**Describe the bug**
I want to upgrade from stock to this firmware, but when going in the web UI to "firmware upgrade", then uploading the most recent firmware, I see the updating process going from 1% to 99%, then the window reloads without any notifications about a successful upgrade or the like, asking my username and password to log in, where I see the old interface with the old stock firmware version number (which is the [most recent](https://www.asus.com/networking-iot-servers/wifi-routers/asus-gaming-routers/tuf-gaming-ax3000-v2/helpdesk_bios?model2Name=TUF-Gaming-AX3000-V2) one):

![grafik](https://github.com/user-attachments/assets/5fbf745c-23be-4a2d-a045-9ccc3ccc3def)

I've tried using Firefox and Brave Browser, factory resetting the router (through the web UI and by rebooting and holding the WPS button) before and after upgrading and tried installing all 3 stable releases (all are "non-tuf" with ASUS' default interface)

https://github.com/gnuton/asuswrt-merlin.ng/releases/download/3004.388.8_2-gnuton1/TUF-AX3000_V2_3004_388.8_2-gnuton1_nand_squashfs.pkgtb
https://github.com/gnuton/asuswrt-merlin.ng/releases/download/3004.388.7_1-gnuton1/TUF-AX3000_V2_3004_388.7_1-gnuton1_nand_squashfs.pkgtb
https://github.com/gnuton/asuswrt-merlin.ng/releases/download/3004.388.6_2-gnuton1/TUF-AX3000_V2_3004_388.6_2-gnuton1_nand_squashfs.pkgtb

but without any success.

**To Reproduce**
1. Go to "firmware upgrade" in the web UI
2. Click on "upload" to select the firmware
3. Wait until the upgrade process has finished
4. Observe that the old stock firmware is still installed

**Expected behavior**
The new firmware should be installed.

**Comment by gnuton** [comment]
Hi @sojusnik can you show us the logs?
It's important to tell which version of the firmware you have tested
