### ISSUE TITLE
RT-AX82U Can't find VPN function in Web UI

### ISSUE THREAD

**Issue by minimoonleaf** [gnuton/asuswrt-merlin.ng#675]
**Router Model Affected**
Models: RT-AX82U

**Firmware Version Affected**
3004.388.8_2-gnuton1

**Is this bug present in upstream Merlin releases too?**
I don't know

**Describe the bug**
Can't find VPN function in Web UI

**To Reproduce**
1. Login Web UI
2. Find VPN function.

**Expected behavior**
Have the VPN function can choice.

**Screenshots**
![螢幕擷取畫面 2024-09-05 222727](https://github.com/user-attachments/assets/67ed3810-59bf-4ae0-a170-736e1866c6db)

**Comment by Rovasteen** [comment]
You might clear your browser cache.  Sometimes the browser gets stuffed up and clearing the cache will allow the Web UI to display correctly.

**Comment by gnuton** [comment]
When your ASUS router is in access point (AP) mode, it generally doesn't handle VPN functions like it would in its default router mode. AP mode is designed to extend your network's wireless coverage and provide more LAN ports, but it offloads most routing features—like NAT (Network Address Translation), firewall, and VPN configuration—to the main router.

In AP mode, the ASUS router with Merlin firmware typically disables the VPN options, as those are routing functions, and the device is no longer acting as the primary router. The VPN setup would need to be done on the main router or another device in the network if the ASUS router is in AP mode.

If you need VPN functionality on the ASUS router, you'd need to switch it back to router mode or use a dedicated VPN client on devices connected to the access point.
