### ISSUE TITLE
ZenWiFi XT8 Can't apply Wireless changes in Access Point mode

### ISSUE THREAD

**Issue by sao321** [gnuton/asuswrt-merlin.ng#681]
**Router Model Affected**
ZenWiFi XT8

**Firmware Version Affected**
388.8_2

**Is this bug present in upstream Merlin releases too?**
No

**Describe the bug**
Can't apply any change for wireless settings

**To Reproduce**
1. Go to Wireless
2. Change anything
3. Click Apply
4. Nothing happens

**Expected behavior**
Expect changes to apply

**Screenshots**
N/A

**Comment by gnuton** [comment]
Duplicate: https://github.com/gnuton/asuswrt-merlin.ng/issues/542
