### ISSUE TITLE
Vpn not working

### ISSUE THREAD

**Issue by ZliTebra** [gnuton/asuswrt-merlin.ng#693]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by ZliTebra** [comment]
Hello everyone, I'm a new member on the forum. I'm on the latest FW and vpn doesn't work on it.  I would appreciate your help

**Comment by gnuton** [comment]
Hi,
no support requests here please.
Please use the forum or the chat.
