### ISSUE TITLE
WtFast

### ISSUE THREAD

**Issue by ZliTebra** [gnuton/asuswrt-merlin.ng#694]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by ZliTebra** [comment]
Is it possible to install the WTFast option for the Tuf ax5400?

**Comment by BoostOver** [comment]
Asus no longer supports WtFast how app inside router.

**Comment by ZliTebra** [comment]
I don't know where you got that information from, but all newer Asus routers have that option.

**Comment by BoostOver** [comment]
> I don't know where you got that information from, but all newer Asus routers have that option.

Simple…..from Asus Website

**Comment by ZliTebra** [comment]
It's a simple upgrade for someone who knows how @gnuton and I would appreciate it if the next firmware update would have that option for the TUF AX5400 as well.

**Comment by BoostOver** [comment]
> You didn't understand something well. My friend has a Gt axe16000 and uses WTFast with no problem. I know people who have older model routers and use WTfast. Asus still has a contract with that company. Even the old RT AX88U model has the WTFast option.
> 
> https://youtu.be/EKGQ6tVpcic?si=x-WUUwfO5UZY866i

Againnnnnnnnnnnnnnnnnnnn:
https://www.asus.com/support/faq/1015726/
In the router the button is only a link to wtfast.
All router in the world can work with wtfast!

**Comment by ZliTebra** [comment]
Okay.  But you can't say that all Asus routers have stopped working with WTFast.  You can say that only some are affected.  As far as I can see, others are working quite normally.

**Comment by BoostOver** [comment]
> Okay. But you can't say that all Asus routers have stopped working with WTFast. You can say that only some are affected. As far as I can see, others are working quite normally.

https://www.asus.com/support/faq/1015726/
https://www.asus.com/support/faq/1015726/
https://www.asus.com/support/faq/1015726/
https://www.asus.com/support/faq/1015726/
https://www.asus.com/support/faq/1015726/
https://www.asus.com/support/faq/1015726/
https://www.asus.com/support/faq/1015726/
https://www.asus.com/support/faq/1015726/
Asus no longer supports WtFast how app inside router.
Asus no longer supports WtFast how app inside router.
Asus no longer supports WtFast how app inside router.
Asus no longer supports WtFast how app inside router.
Asus no longer supports WtFast how app inside router.
Asus no longer supports WtFast how app insiderouter.

**Comment by ZliTebra** [comment]
Ok. What is next? FlexQoS for Tuf AX5400?

**Comment by BoostOver** [comment]
> Ok. What is next? FlexQoS for Tuf AX5400?
Te lo scrivo in Italiano.
Non capisci niente.
Buon Natale

**Comment by ZliTebra** [comment]
I love U 👯‍♂️
