### ISSUE TITLE
OSPF

### ISSUE THREAD

**Issue by TheSnipes** [gnuton/asuswrt-merlin.ng#696]
I’m always frustrated when I cannot use OSPF (Open Shortest Path First) on my TUF-AX3000 V2 router with the gnuton Merlin firmware. OSPF is essential for my network configuration and management, and the lack of support limits my ability to efficiently route traffic in my network.
I would like the gnuton Merlin firmware to include support for OSPF. This would allow me to utilize dynamic routing protocols to improve network performance and reliability, especially in complex network environments.
Adding OSPF support would greatly enhance the functionality of the gnuton Merlin firmware for users who require advanced routing capabilities. This feature would be particularly beneficial for small to medium-sized networks that rely on dynamic routing protocols.

Thank you very much in advance!

**Comment by gnuton** [comment]
OSPF is not natively supported in ASUSWRT-Merlin's interface, but  it can be implemented by installing and configuring routing daemons like Quagga or FRR via entware. This gives advanced users the flexibility to use enterprise-level routing protocols on consumer-grade hardware.
