### ISSUE TITLE
Add vlan support

### ISSUE THREAD

**Issue by MarcoCITA** [gnuton/asuswrt-merlin.ng#71]
**Is your feature request related to a problem?** Yes
**A clear and concise description of what the problem is.**
Isolate iot devices and pc.

**Describe the solution you'd like**
Have a vlan setup page if it's possible.

**Comment by gnuton** [comment]
what about using guest network for that + isolation?

**Comment by gnuton** [comment]
Closed since this is a feature that we already have

**Comment by gnuton** [comment]
It's available on PRO routers
https://www.asus.com/us/support/faq/1049415/

**Comment by gnuton** [comment]
for not pro:
https://www.snbforums.com/threads/how-to-use-vlans-on-your-non-pro-asus-router-with-386-or-388-code-no-scripting-required.85850/
