### ISSUE TITLE
Gaming Improvements 🎮🕹️ TUF AX5400

### ISSUE THREAD

**Issue by ZliTebra** [gnuton/asuswrt-merlin.ng#714]
Is there a possibility to make a Geo-Filter for the Asus router like the Netduma R3 has!?

https://youtube.com/shorts/nLuCUF2wwNI?si=lBno-gGMIA43bU1e

Can you do anything related to Gaming in any of the next Firmware? In every new Firmware you release, there is nothing improved and new for Gaming.  My router is called TUF GAMING, but it is not worthy of that name because its gaming functions are bad and everything is very simple.
Do anything new related to Gaming. Be creative and imaginative. Thanks a lot!

**Comment by BoostOver** [comment]
Gnuton non ne fai una giusta🤣
Questo gli spieghi le cose e non le comprende

**Comment by ZliTebra** [comment]
Man, you are becoming a real temptation for my brain. You are chasing me around the forums and leaving stupid comments.  Come on, take a break from me for 2 days, please.  hahahaha

**Comment by gnuton** [comment]
@BoostOver che ho fatto?

**Comment by gnuton** [comment]
@ZliTebra @BoostOver is respetable and experienced person and he is joking with you.

I do have really little time and no interest in gaming at all to promise you anything on this area

**Comment by ZliTebra** [comment]
I went back to the official Asus Firmware, it's much more stable, and there was an update in November. I honestly don't even know what you could do for Gaming. It requires a little more work and skills.
