### ISSUE TITLE
Midnight Commander not starting

### ISSUE THREAD

**Issue by cseryz** [gnuton/asuswrt-merlin.ng#718]
Hello guys,
I have [3004.388.8_2-gnuton1] on my RT-AX58U v2, 
I wanted to install mc, "ipkg install mc"
I got this error message during install:
"
Configuring glib
Generating /opt/share/glib-2.0/schemas/gschemas.compiled
/tmp/mnt/Cseryz_WD/asusware.arm/bin/glib-compile-schemas: can't resolve symbol 'pthread_key_create'
postinst script returned status 1
ERROR: glib.postinst returned 1
"
If i would run, receiving this:
"/tmp/mnt/Cseryz_WD/asusware.arm/bin/mc: symbol 'atan2': can't resolve symbol
"
My HDD is with NTFS filesystem, not sure if it matters.

Since i would keep using Download Manager, i cannot install entware.

Can someone help how to resolve and able to run mc ?
Thanks

**Comment by gnuton** [comment]
that means you have missing libraries.
