### ISSUE TITLE
The url on the "WAN" tab is error

### ISSUE THREAD

**Issue by osmanelitok** [gnuton/asuswrt-merlin.ng#73]
**Firmware Version Affected **

 386.00_0-gnuton0_alpha9

**Is this bug present in upstream Merlin releases too?**

No

**Describe the bug**

The url on the "WAN" tab is "http://192.168.1.1/Advanced_VDSL_Content.asp?chg_pvc=0" while it should be "http://192.168.1.1/Advanced_WAN_Content.asp".

**Expected behavior**

There are more options when "http://192.168.1.1/Advanced_WAN_Content.asp".

**Screenshots**

![wan-vdsl](https://user-images.githubusercontent.com/65765917/106339366-69dbb900-62a7-11eb-9553-abbf12b1f7af.PNG)
![wan](https://user-images.githubusercontent.com/65765917/106339372-6ea06d00-62a7-11eb-84a9-39c74f7751a2.PNG)

**Comment by gnuton** [comment]
When you press WAN on the left side bar, you should be redirected to 
1. Advanced_WAN_Content.asp if Wan type is "Ethernet Wan"
![image](https://user-images.githubusercontent.com/576580/106908198-614c0e00-66ff-11eb-8a48-c64d98c2e3e5.png)
2. Advanced_VDSL_Content.asp if wan type is DSL/VDSL
![image](https://user-images.githubusercontent.com/576580/106908731-da4b6580-66ff-11eb-9e81-679b63810deb.png)

3. Advanced_DSL_Content.asp if wan type is DSL/ADSL
![image](https://user-images.githubusercontent.com/576580/106908803-edf6cc00-66ff-11eb-97e5-3fb64b55e1d6.png)

Everything works as expected for me.

**Comment by osmanelitok** [comment]
When VDSL is active, "Router Security Assessment" sends to "http://192.168.1.1/Advanced_WAN_Content.asp" for "UPnP service disabled" option. There are more features in the WAN option. If it is supposed to be this way, there is no problem.
