### ISSUE TITLE
Speed test Upload problem occurred in browsers

### ISSUE THREAD

**Issue by osmanelitok** [gnuton/asuswrt-merlin.ng#76]
**Firmware Version Affected **

386.00_0-gnuton0_alpha9

**Is this bug present in upstream Merlin releases too?**

No

**Describe the bug**

- Speed test Upload problem occurred in browsers.

For example,

Edge (Chromium) Upload 1mbps
Google Chrome Upload 3 mbps
Internet Explorer Upload 6 mbps
Windows Speed Test App Upload 7 mbps

I've done these tests over and over. All the same 70mbps download is okay but there is a problem with the upload.

**Screenshots**

![chrome](https://user-images.githubusercontent.com/65765917/106340478-005da980-62ab-11eb-9bf2-abf27f4ff684.PNG)
![Ekran Alıntısı](https://user-images.githubusercontent.com/65765917/106340482-018ed680-62ab-11eb-86ff-9b71e3b167e8.PNG)
![ie](https://user-images.githubusercontent.com/65765917/106340485-02c00380-62ab-11eb-9811-44b9babd8c7a.PNG)
![app](https://user-images.githubusercontent.com/65765917/106340477-fe93e600-62aa-11eb-8802-971deb583f8b.PNG)

**Comment by gnuton** [comment]
can you check this too?
 http://router.asus.com/AdaptiveQoS_InternetSpeed.asp
 The speed here will be the one measured by the router and not affected by any issue you can have in your internal network

**Comment by osmanelitok** [comment]
yes there is no problem here. different results appear in each browser. This problem does not happen with software versions before this. maybe it's a problem with QOS.

![spedtest](https://user-images.githubusercontent.com/65765917/106340976-9cd47b80-62ac-11eb-9bb4-f94b404393bb.PNG)

**Comment by gnuton** [comment]
It seems like Edge suffers of this issue on its own.
https://techcommunity.microsoft.com/t5/windows-10-servicing/ms-edge-on-chrome-basis-is-too-slow-during-the-speed-test-in-the/m-p/1546258
not sure about others browsers yet. I do use chrome and i do get same speed as in the router.

**Comment by osmanelitok** [comment]
because everything works normally in alpha 8 version when there are same browsers. When I install alpha 9 the problems come back.

**Comment by osmanelitok** [comment]
In addition, I have no download problems, I have a upload.

**Comment by osmanelitok** [comment]
I just got the Google Chrome update and installed it. the problem is completely fixed. There is no problem at the moment. Thx.
