### ISSUE TITLE
Wireless settings are working but not showing this.

### ISSUE THREAD

**Issue by osmanelitok** [gnuton/asuswrt-merlin.ng#77]
**Firmware Version Affected **

 386.00_0-gnuton0_alpha9

**Is this bug present in upstream Merlin releases too?**

No

**Describe the bug**

When I change the wireless network settings, all the settings are active, but when I open the page again everything stays the same.

For example; When I do Channel bandwidth 20 Mhz and Control Channel 11, the settings become active. The modem broadcasts on channel 11 and transmits it to other aimesh products.

However, when I come back to http://192.168.1.1/Advanced_Wireless_Content.asp, everything seems to be not set at all.

**Screenshots**

![Ekran Görüntüsü - 2021-01-30 05-18-41](https://user-images.githubusercontent.com/65765917/106344562-8550bf00-62bb-11eb-9440-9806e24292f5.png)

**Comment by gnuton** [comment]
it works for me. Wondering if this is an issue related to something got messed up in the nvram of your router or what.

**Comment by gnuton** [comment]
Confirmed as working for @Zendilar too
https://www.snbforums.com/threads/dsl-ac68u-asuswrt-merlin-386-x-alphas-for-dsl-ac68u-are-now-available.68295/page-4#post-660642

**Comment by gnuton** [comment]
@osmanelitok have you managed to get this working in an incognito window?

**Comment by osmanelitok** [comment]
> @osmanelitok have you managed to get this working in an incognito window?

yes. it works in incognito window but not in normal window.

**Comment by zendilar** [comment]
I try to follow your instructions and opened a privet window on firefox  but with no success, then I opened chrome on an incognito tab but  the same thing happen, after the apply button is hit nothing stays. Or is me that I am looking at the wrong place, I suppose that the list of any game that is configured is going to be at the top or at the bottom, is that correct?

Zendilar
 

    Στις Τρίτη, 9 Φεβρουαρίου 2021, 11:53:25 π.μ. EET, ο χρήστης Antonio Aloisio <notifications@github.com> έγραψε:  
 
 


@osmanelitok have you managed to get this working in an incognito window?

**Comment by zendilar** [comment]
I try to follow your instructions and opened a privet window on firefox  but with no success, then I opened chrome on an incognito tab but the same thing happen, after the apply button is hit nothing stays. Or is me that I am looking at the wrong place, I suppose that the list of any game that is configured is going to be at the top or at the bottom, is that correct?

**Comment by osmanelitok** [comment]
yes it worked with chrome and incognito window even I can see it from the phone. Apart from these, the page is reset as if no settings were made in all browsers.
