### ISSUE TITLE
Spectrum plot doesn't show up

### ISSUE THREAD

**Issue by BoostOver** [gnuton/asuswrt-merlin.ng#78]
**Firmware Version Affected **
386.01-gnuton0_beta1

**Is this bug present in upstream Merlin releases too?**
Non posso testare

**Describe the bug**
Non viene mostrato lo spettro dsl

**To Reproduce**
http://192.168.1.1/Main_Spectrum_Content.asp    /Riesegui scansione

**Comment by gnuton** [comment]
The problems seems to be realated to this:

http://router.asus.com/ajax_signals.asp 

returns empty arrays

bpc_us = [];
bpc_ds = [];
snr_us = [];
snr_ds = [];

**Comment by gnuton** [comment]
The problem seems to be related to missing binaries

AX82U
router/dsl_autodet/
router/dsl_diag/

DSL-AC68U
router/spectrum

**Comment by gnuton** [comment]
Fixed on DSL-AC68U, still broken on DSL-AX82U
![image](https://user-images.githubusercontent.com/576580/107718740-e83c5000-6cd6-11eb-9377-bce867b2b478.png)

**Comment by BoostOver** [comment]
Grazie.

**Comment by gnuton** [comment]
let's keep this open since this affect DSL-AX82U

**Comment by gnuton** [comment]
I will re-open this since this is still a bug in DSL-AX82U.

**Comment by gnuton** [comment]
Fix: https://github.com/gnuton/asuswrt-merlin.ng/commit/f0cadea9148ee614ce5a4cbd49b937db8f69e825
