### ISSUE TITLE
Web Access from WAN shuts down

### ISSUE THREAD

**Issue by osmanelitok** [gnuton/asuswrt-merlin.ng#79]
**Firmware Version Affected **

386.01 beta 1

**Is this bug present in upstream Merlin releases too?**

No

**Describe the bug**

Although I do enable the "Enable Web Access from WAN" option, modem the settings are deleted every time it restarts and it becomes deactivated.

**To Reproduce**

http://192.168.1.1/Advanced_System_Content.asp  
**Enable Web Access from WAN** \Yes
and modem reboot.

**Screenshots**

![2](https://user-images.githubusercontent.com/65765917/107431124-1420cf80-6b37-11eb-87d7-9c1bc1422dc0.PNG)

**Comment by gnuton** [comment]
Tested and it works for me. Cannot reproduce.

**Comment by dave14305** [comment]
The Skynet firewall add-on for Merlin will disable WAN access if “Secure Mode” is enabled in the Skynet menus. Is Skynet installed? It would indicate in the syslog if it was responsible for disabling the insecure settings.

**Comment by osmanelitok** [comment]
yes skynet was installed.  I removed it and it was fixed.
